// English → Chinese commodity name mapping
// Auto-generated from D:\workspace\commodity-zh-map.properties
const EN_TO_ZH: Record<string, string> = {
  "AcryliPlex Composite": "亚克力络合物复合材料",
  "Agricium": "艾格瑞金属",
  "Agricium (Ore)": "艾格瑞矿石",
  "Agricultural Supplies": "农业用品",
  "Altruciatoxin": "仁木毒",
  "Aluminum": "铝",
  "Aluminum (Ore)": "铝矿石",
  "Amioshi Plague": "阿米什瘟疫",
  "Ammonia": "氨",
  "Aphorite": "紫钠水晶",
  "Apoxygenite": "氧石",
  "Argon": "氩气",
  "Aslarite": "阿斯莱晶体",
  "Astatine": "砹",
  "Atlasium": "巨神合金",
  "Beradom": "冰蓝珀",
  "Beryl": "绿柱石",
  "Beryl (Raw)": "绿柱石（粗制）",
  "Bexalite": "贝沙电气石",
  "Bexalite (Raw)": "贝沙电气石（粗制）",
  "Bioplastic": "生物塑料",
  "Blue Bilva": "蓝木橘",
  "Borase": "波射石",
  "Borase (Ore)": "波射矿石",
  "Carbon": "碳",
  "Carbon-Silk": "碳绸",
  "Carinite": "科力晶",
  "Chlorine": "氯气",
  "Cobalt": "钴",
  "Compboard": "电路板",
  "Construction Materials": "建筑材料",
  "Copper": "铜",
  "Copper (Ore)": "铜矿石",
  "Corundum": "刚玉",
  "Corundum (Raw)": "刚玉（粗制）",
  "Decari Pod": "德卡利孢囊",
  "Degnous Root": "德古尼斯藻根",
  "Detatrine": "得他啶",
  "Diamond": "钻石",
  "Diamond (Raw)": "钻石（粗制）",
  "Diamond Laminate": "钻石层压板",
  "Diluthermex": "稀热树脂",
  "Distilled Spirits": "蒸馏酒精",
  "Dolivine": "暗橄榄石",
  "Dopple": "多普勒",
  "Dymantium": "代曼合金",
  "DynaFlex": "高韧材料",
  "E'tam": "艾坦药草",
  "Elespo": "俄列斯泼",
  "Feynmaline": "熵瞬晶",
  "Fireworks": "烟花",
  "Fluorine": "氟",
  "Freeze": "冻滞",
  "Fresh Food": "新鲜食品",
  "Gasping Weevil Eggs": "窒息象鼻虫卵",
  "Glacosite": "冰碛棉",
  "Glacosite (Raw)": "冰碛棉（粗制）",
  "Glow": "光热",
  "Gold": "金",
  "Gold (Ore)": "金矿石",
  "Golden Medmon": "黄金麦德蒙果",
  "Hadanite": "哈丹水晶",
  "Heart of the Woods": "森林之心",
  "Helium": "氦",
  "Hephaestanite": "火神石",
  "Hephaestanite (Raw)": "火神石（粗制）",
  "HexaPolyMesh Coating": "六边形涂层",
  "Human Food Bars": "人类食品棒",
  "Hydrogen": "氢",
  "Hydrogen Fuel": "氢燃料",
  "Inert Materials": "惰性物质",
  "Iodine": "碘",
  "Iron": "铁",
  "Iron (Ore)": "铁矿石",
  "Jaclium (Ore)": "杰金矿石",
  "Janalite": "加纳石",
  "Jumping Limes": "跳跳橙",
  "Kopion Horn": "寇骈犬角",
  "Laranite": "砬兰石",
  "Laranite (Raw)": "砬兰石（粗制）",
  "Lastaprene": "耐用橡胶",
  "Lindinium": "林登金",
  "Lindinium (Ore)": "林登金矿石",
  "Luminalia Gift": "光灯节礼物",
  "Lycara": "莱护材料",
  "Mala": "玛拉毒素",
  "Marok Gem": "啼笑鸟胃石",
  "Maze": "迷宫",
  "MedPens": "医疗笔",
  "Medical Supplies": "医疗用品",
  "Mercury": "汞",
  "Methane": "甲烷",
  "Neograph": "新石墨",
  "Neon": "霓虹",
  "Nitrogen": "氮",
  "Omnapoxy": "环氧脂",
  "Organics": "有机物",
  "Osoian Hides": "奥索安皮革",
  "Ouratite": "欧拉特烃",
  "OxyPens": "氧气笔",
  "Oza": "奥扎橘",
  "Partillium": "帕缇利气",
  "Pitambu": "皮坦布果",
  "Potassium": "钾",
  "Pressurized Ice": "高压冰",
  "Processed Food": "加工食品",
  "Prota": "普罗塔菌",
  "Quantainium": "量子矿",
  "Quantainium (Raw)": "量子矿（粗制）",
  "Quantum Fuel": "量子燃料",
  "Quartz": "石英",
  "Quartz (Raw)": "石英（粗制）",
  "Ranta Dung": "兰塔有机粪便",
  "Raw Ice": "原冰",
  "Recycled Material Composite": "再生复合材料",
  "Revenant Pod": "亡魂果荚",
  "Revenant Tree Pollen": "亡魂树花粉",
  "Riccite": "愈金",
  "SLAM": "冠军",
  "Sadaryx": "萨达瑞晶",
  "Saldynium (Ore)": "烁迪银矿石",
  "Sarilus": "沙鲁斯",
  "Savrilium": "萨维里金属",
  "Savrilium (Ore)": "萨维里金属矿石",
  "Scrap": "废料",
  "Ship Ammunition": "舰船弹药",
  "Ship ammunition - size 1": "舰船弹药 - 尺寸 1",
  "Ship ammunition - size 2": "舰船弹药 - 尺寸 2",
  "Ship ammunition - size 3": "舰船弹药 - 尺寸 3",
  "Ship ammunition - size 4": "舰船弹药 - 尺寸 4",
  "Ship ammunition - size 5": "舰船弹药 - 尺寸 5",
  "Ship ammunition - size 6": "舰船弹药 - 尺寸 6",
  "Ship ammunition - size 7": "舰船弹药 - 尺寸 7",
  "Ship decoy countermeasures": "舰船诱饵弹反制措施",
  "Ship noise countermeasures": "舰船噪声场反制措施",
  "Silicon": "硅",
  "Silnex": "高级航空陶瓷",
  "Souvenirs": "纪念品",
  "Steel": "钢铁",
  "Stileron": "稀钛铁",
  "Stims": "斯酊姆烟草",
  "Stone Bug Shell": "石虫壳",
  "Sunset Berries": "日落浆果",
  "Taranite": "塔兰导电石",
  "Taranite (Raw)": "塔兰导电石（粗制）",
  "ThermalFoam": "热泡沫塑料",
  "Thrust": "猛冲",
  "Tin": "锡",
  "Titanium": "钛",
  "Titanium (Ore)": "钛矿石",
  "Torite": "托瑞特金属",
  "Tritium": "氚",
  "Tungsten": "钨",
  "Tungsten (Ore)": "钨矿石",
  "Uncut SLAM": "未加工的冠军",
  "Waste": "垃圾",
  "WiDoW": "黑寡妇",
  "Xa'Pyen": "夏潘合金",
  "Year of the Dog Envelope": "狗年红包",
  "Zeta-Prolanide": "Z-普罗兰化合物",
  "Zip": "滋滋",
  "mobyGlass Personal Computers": "mobyGlass 个人电脑",
};

export function getZhName(enName: string): string {
  return EN_TO_ZH[enName] || enName;
}
