// Location names from 地名对照.xlsx + DB-matched entries
const LOCATION_EN_TO_ZH: Record<string, string> = {
  "\"Buckets\"": "“水桶”",
  "\"Buckets\" on Lyria": "莉瑞雅上的“水桶”",
  "\"Elsewhere\"": "\"别处\"",
  "\"Elsewhere\" on Lyria": "莉瑞雅上的\"别处\"",
  "\"Launch Pad\"": "“发射台”",
  "\"Launch Pad\" on Lyria": "莉瑞雅上的“发射台”",
  "\"Lost and Found\"": "失物招领处",
  "\"Lost and Found\" on Wala": "瓦菈上的“失物招领处”",
  "\"The Necropolis\"": "\"墓地\"",
  "\"The Necropolis\" on microTech": "微科星上的\"墓地\"",
  "\"The Orphanage\"": "\"孤儿院\"",
  "\"The Orphanage\" on Lyria": "莉瑞雅上的\"孤儿院\"",
  "\"The Pit\"": "\"坑地\"",
  "\"The Pit\" on Lyria": "莉瑞雅上的\"坑地\"",
  "\"Utopia\"": "“乌托邦”",
  "\"Utopia\" on Yela": "耶拉上的“乌托邦”",
  "\"Wheeler's\"": "\"车夫驿站\"",
  "\"Wheeler's\" on Lyria": "莉瑞雅上的\"车夫驿站\"",
  "Abandoned Section": "废弃区域",
  "Aberdeen": "阿伯丁",
  "Aberdeen Cave": "阿伯丁洞穴",
  "Aberdeen wreck site": "阿伯丁上的残骸地点",
  "Account Management Office": "账户管理部门办公室",
  "Account Management Office on the Admin Center near Orison": "位于奥里森行政中心内的账户管理部门办公室",
  "Adair's Retreat": "阿黛尔幽居",
  "Adair's Retreat on Euterpe": "欧忒耳佩上的阿黛尔幽居",
  "Adir Cave": "阿迪尔洞穴",
  "Adira Falls Apartments": "阿迪拉瀑布公寓楼",
  "Adira Falls Apartments in Area18": "18区的阿迪拉瀑布公寓楼",
  "Admin Center": "行政中心",
  "Admin Center at Inspiration Park near Orison": "奥里森灵感园区内的行政中心",
  "Afterlife": "来生",
  "Afterlife on Yela": "耶拉上的“来生”",
  "Ako's Return": "阿克弯",
  "Ako's Return on Wala": "瓦菈上的阿克弯",
  "Ambitious Dream Station at Crusader's L1 Lagrange point": "位于十字军的L1拉格朗日点的雄心伟梦站",
  "ArcCorp": "弧光星",
  "ArcCorp Mining Area 045": "弧光集团采矿站 045",
  "ArcCorp Mining Area 045 on Wala": "瓦菈上的弧光集团采矿站-045",
  "ArcCorp Mining Area 048": "弧光集团采矿站 048",
  "ArcCorp Mining Area 048 on Wala": "瓦菈上的弧光集团采矿站-048",
  "ArcCorp Mining Area 056": "弧光集团采矿站 056",
  "ArcCorp Mining Area 056 on Wala": "瓦菈上的弧光集团采矿站-056",
  "ArcCorp Mining Area 061": "弧光集团采矿站 061",
  "ArcCorp Mining Area 061 on Wala": "瓦菈上的弧光集团采矿站-061",
  "ArcCorp Mining Area 141": "弧光集团采矿站 141",
  "ArcCorp Mining Area 141 on Daymar": "戴玛尔上的弧光集团采矿站-141",
  "ArcCorp Mining Area 157 on Yela": "耶拉上的弧光集团采矿站-157",
  "ArcCorp Mining Area157": "弧光集团采矿站 157",
  "ArcCorp Processing Center 115": "弧光集团加工中心 115",
  "ArcCorp Processing Center 115 on Wala": "瓦菈上的弧光集团加工中心-115",
  "ArcCorp Processing Center 123": "弧光集团加工中心 123",
  "ArcCorp Processing Center 123 on Wala": "瓦菈上的弧光集团加工中心-123",
  "ArcCorp Security Post 011": "弧光安保站011",
  "ArcCorp Security Post 011 on Lyria": "莉瑞雅上的弧光安保站011",
  "ArcCorp Security Post 017": "弧光安保站017",
  "ArcCorp Security Post 017 on Lyria": "莉瑞雅上的弧光安保站017",
  "ArcCorp Security Post 024": "弧光安保站024",
  "ArcCorp Security Post 024 on Lyria": "莉瑞雅上的弧光安保站024",
  "ArcCorp Security Post 029": "弧光安保站029",
  "ArcCorp Security Post 029 on Lyria": "莉瑞雅上的弧光安保站029",
  "ArcCorp Security Post 033": "弧光安保站033",
  "ArcCorp Security Post 033 on Lyria": "莉瑞雅上的弧光安保站033",
  "ArcCorp Security Post 038": "弧光安保站038",
  "ArcCorp Security Post 038 on Lyria": "莉瑞雅上的弧光安保站038",
  "ArcCorp Security Post 042": "弧光安保站042",
  "ArcCorp Security Post 042 on Lyria": "莉瑞雅上的弧光安保站042",
  "ArcCorp Security Post 045": "弧光安保站045",
  "ArcCorp Security Post 045 on Lyria": "莉瑞雅上的弧光安保站045",
  "ArcCorp Security Post 052": "弧光安保站052",
  "ArcCorp Security Post 052 on Lyria": "莉瑞雅上的弧光安保站052",
  "ArcCorp Security Post 059": "弧光安保站059",
  "ArcCorp Security Post 059 on Lyria": "莉瑞雅上的弧光安保站059",
  "ArcCorp Security Post 060": "弧光安保站060",
  "ArcCorp Security Post 060 on Lyria": "莉瑞雅上的弧光安保站060",
  "ArcCorp Security Post 066": "弧光安保站066",
  "ArcCorp Security Post 066 on Wala": "瓦菈上的弧光安保站066",
  "ArcCorp Security Post 074": "弧光安保站074",
  "ArcCorp Security Post 074 on Wala": "瓦菈上的弧光安保站074",
  "ArcCorp Security Post 078": "弧光安保站078",
  "ArcCorp Security Post 078 on Wala": "瓦菈上的弧光安保站078",
  "ArcCorp Security Post 087": "弧光安保站087",
  "ArcCorp Security Post 087 on Wala": "瓦菈上的弧光安保站087",
  "ArcCorp Security Post 089": "弧光安保站089",
  "ArcCorp Security Post 089 on Wala": "瓦菈上的弧光安保站089",
  "ArcCorp Security Post 092": "弧光安保站092",
  "ArcCorp Security Post 092 on Wala": "瓦菈上的弧光安保站092",
  "ArcCorp Security Post 094": "弧光安保站094",
  "ArcCorp Security Post 094 on Wala": "瓦菈上的弧光安保站094",
  "ArcCorp Security Post 101": "弧光安保站101",
  "ArcCorp Security Post 101 on Wala": "瓦菈上的弧光安保站101",
  "ArcCorp Security Post 108": "弧光安保站108",
  "ArcCorp Security Post 108 on Wala": "瓦菈上的弧光安保站108",
  "ArcCorp Security Post 111": "弧光安保站111",
  "ArcCorp Security Post 111 on Wala": "瓦菈上的弧光安保站111",
  "ArcCorp's Daymar facility": "弧光集团在戴玛尔上的设施",
  "ArcCorp's Yela facility": "弧光集团在耶拉上的设施",
  "ArcCorp's mining outpost on Daymar": "弧光集团在戴玛尔上的采矿站",
  "Area 18": "18区",
  "Area18 on ArcCorp": "弧光星上的18区",
  "Arial": "艾瑞尔",
  "Arial Cave": "艾瑞尔洞穴",
  "Arid Reach": "涸泽",
  "Arid Reach on Pyro II": "派罗II上的涸泽",
  "Ashburn Channel Aid Shelter": "阿什本通道援助避难所",
  "Ashburn Channel Aid Shelter on Cellin": "赛琳上的阿什本通道援助避难所",
  "Ashland": "灰烬之地",
  "Ashland on Pyro 5a": "派罗5a上的灰烬之地",
  "Aspire Grand": "志远大厦",
  "Aspire Grand in New Babbage": "新巴贝奇的志远大厦",
  "Aston Ridge Aid Shelter": "阿斯顿岭援助避难所",
  "Aston Ridge Aid Shelter on Yela": "耶拉上的阿斯顿岭援助避难所",
  "Astor's Clearing": "阿斯特空地",
  "Astor's Clearing on microTech": "微科星上的阿斯特空地",
  "Attritus OLP": "碎料 激光站",
  "Attritus Orbital Laser Platform above Daymar": "戴玛尔上的碎料 轨道激光平台",
  "Attritus PAF-I": "碎料 校准站-I",
  "Attritus PAF-II": "碎料 校准站-II",
  "Attritus PAF-III": "碎料 校准站-III",
  "Attritus Platform Alignment Facility I on Daymar": "戴玛尔上的碎料 平台校准设施I",
  "Attritus Platform Alignment Facility II on Daymar": "戴玛尔上的碎料 平台校准设施II",
  "Attritus Platform Alignment Facility III on Daymar": "戴玛尔上的碎料 平台校准设施III",
  "August Dunlow Spaceport": "奥古斯特·顿洛空港",
  "August Dunlow Spaceport in Orison": "奥里森的奥古斯特·顿洛空港",
  "BWD-A1 on Brushwood Platform near Orison": "位于奥里森附近布拉什伍德平台上的BWD-A1",
  "BWD-A2 on Brushwood Platform near Orison": "位于奥里森附近布拉什伍德平台上的BWD-A2",
  "BWD-B on Brushwood Platform near Orison": "位于奥里森附近布拉什伍德平台上的BWD-B",
  "BWD-C on Brushwood Platform near Orison": "位于奥里森附近布拉什伍德平台上的BWD-C",
  "BWD-D on Brushwood Platform near Orison": "位于奥里森附近布拉什伍德平台上的BWD-D",
  "BWD-E on Brushwood Platform near Orison": "位于奥里森附近布拉什伍德平台上的BWD-E",
  "BWD-F on Brushwood Platform near Orison": "位于奥里森附近布拉什伍德平台上的BWD-F",
  "BWD-G on Brushwood Platform near Orison": "位于奥里森附近布拉什伍德平台上的BWD-G",
  "BWD-H on Brushwood Platform near Orison": "位于奥里森附近布拉什伍德平台上的BWD-H",
  "Baijini Point": "拜基尼空间站",
  "Baijini Point above ArcCorp": "弧光星上的拜基尼空间站",
  "Balto's Blind": "巴尔托盲点",
  "Balto's Blind on Lyria": "莉瑞雅上的巴尔托盲点",
  "Barton Flats Aid Shelter on Aberdeen": "阿伯丁上的巴顿公寓援助庇护所",
  "Beautiful Glen Station at Crusader's L5 Lagrange point": "位于十字军的L5拉格朗日点的美丽峡谷站",
  "Benson Mining": "本森矿站",
  "Benson Mining Outpost": "本森采矿前哨站",
  "Benson Mining on Yela": "耶拉上的本森矿站",
  "Bevic Convention Center": "贝维克会展中心",
  "Bevic Convention Center in Area18 on ArcCorp": "弧光星上的18区的贝维克会展中心",
  "Blackrock Exchange": "黑岩交易所",
  "Blackrock Exchange on Pyro VI": "派罗VI上的黑岩交易所",
  "Blighter's Run": "鄙坡",
  "Blighter's Run on Calliope": "卡利俄佩上的鄙坡",
  "Bloodshot Ridge": "血腥岭",
  "Bloodshot Ridge on microTech": "微科星上的血腥岭",
  "Bloom": "盛放星",
  "Boondoggle": "烂尾站",
  "Boondoggle on Aberdeen": "阿伯丁上的烂尾站",
  "Borehole Station": "钻孔站",
  "Borehole Station in Levski": "列夫斯基的钻孔站",
  "Bountiful Harvest": "丰收种植站",
  "Bountiful Harvest Hydroponics": "丰收水培种植站",
  "Bountiful Harvest on Daymar": "戴玛尔上的丰收种植站",
  "Brio's Breaker Yard": "布里奥的拆船场",
  "Brio's Breaker Yard on Daymar": "戴玛尔 上的布里奥的拆船场",
  "Broken Patch": "破碎之地",
  "Broken Patch on Hurston": "赫斯顿上的破碎之地",
  "Brushwood Platform": "布拉什伍德平台",
  "Brushwood Platform at Inspiration Park near Orison": "位于奥里森的灵感园区的布拉什伍德平台",
  "Bud's Growery": "巴德种植园",
  "Bud's Growery on Euterpe": "欧忒耳佩上的巴德种植园",
  "Bueno Ravine": "布埃诺峡谷",
  "Bueno Ravine on Pyro III": "位于派罗III的布埃诺峡谷",
  "Building A on a Recreation Platform in Cloudrest Retreat": "建筑A位于云歇避风港的一个娱乐平台",
  "Building A on a Recreation Platform in Prospect Point": "建筑A位于眺望点的一个娱乐平台",
  "Building A on a Residency Platform in Empyrean Park": "建筑A位于至高庭园的一个住宅平台",
  "Building A on a Resort Platform in Cloudrest Retreat": "建筑A位于云歇避风港的一个度假平台",
  "Building A on a Resort Platform in Empyrean Park": "建筑A位于至高庭园的一个度假平台",
  "Building A on a Resort Platform in Prospect Point": "建筑A位于云歇避风港的一个度假平台",
  "Building A on an Admin Platform in Empyrean Park": "建筑A位于至高庭园的一个行政平台",
  "Building A on an Admin Platform in Prospect Point": "建筑A位于眺望点的一个行政平台",
  "Building B on a Recreation Platform in Cloudrest Retreat": "建筑B位于云歇避风港的一个娱乐平台",
  "Building B on a Recreation Platform in Prospect Point": "建筑B位于眺望点的一个娱乐平台",
  "Building B on a Residency Platform in Empyrean Park": "建筑B位于至高庭园的一个住宅平台",
  "Building B on a Resort Platform in Cloudrest Retreat": "建筑B位于云歇避风港的一个度假平台",
  "Building B on a Resort Platform in Empyrean Park": "建筑B位于至高庭园的一个度假平台",
  "Building B on a Resort Platform in Prospect Point": "建筑B位于眺望点的一个度假平台",
  "Building B on an Admin Platform in Empyrean Park": "建筑B位于至高庭园的一个行政平台",
  "Building B on an Admin Platform in Prospect Point": "建筑B位于眺望点的一个行政平台",
  "Building C on a Recreation Platform in Cloudrest Retreat": "建筑C位于云歇避风港的一个娱乐平台",
  "Building C on a Recreation Platform in Prospect Point": "建筑C位于眺望点的一个娱乐平台",
  "Building C on a Residency Platform in Empyrean Park": "建筑C位于至高庭园的一个住宅平台",
  "Building C on a Resort Platform in Cloudrest Retreat": "建筑C位于云歇避风港的一个度假平台",
  "Building C on a Resort Platform in Empyrean Park": "建筑C位于至高庭园的一个度假平台",
  "Building C on a Resort Platform in Prospect Point": "建筑C位于眺望点的一个度假平台",
  "Building C on an Admin Platform in Empyrean Park": "建筑C位于至高庭园的一个行政平台",
  "Building C on an Admin Platform in Prospect Point": "建筑C位于眺望点的一个行政平台",
  "Building D on a Recreation Platform in Cloudrest Retreat": "建筑D位于云歇避风港的一个娱乐平台",
  "Building D on a Recreation Platform in Prospect Point": "位于眺望点的娱乐平台的D楼",
  "Building D on a Residency Platform in Empyrean Park": "建筑D位于至高庭园的一个住宅平台",
  "Building D on a Resort Platform in Cloudrest Retreat": "建筑D位于云歇避风港的一个度假平台",
  "Building D on a Resort Platform in Empyrean Park": "建筑D位于至高庭园的一个度假平台",
  "Building D on a Resort Platform in Prospect Point": "建筑D位于眺望点的一个度假平台",
  "Building D on an Admin Platform in Empyrean Park": "建筑D位于至高庭园的一个行政平台",
  "Building D on an Admin Platform in Prospect Point": "建筑D位于眺望点的一个行政平台",
  "Building E on a Recreation Platform in Cloudrest Retreat": "建筑E位于云歇避风港的一个娱乐平台",
  "Building E on a Recreation Platform in Prospect Point": "建筑E位于眺望点的一个娱乐平台",
  "Building E on a Residency Platform in Empyrean Park": "建筑E位于至高庭园的一个住宅平台",
  "Building F on a Recreation Platform in Cloudrest Retreat": "建筑F位于云歇避风港的一个娱乐平台",
  "Building F on a Recreation Platform in Prospect Point": "建筑F位于眺望点的一个娱乐平台",
  "Building F on a Residency Platform in Empyrean Park": "建筑F位于至高庭园的一个住宅平台",
  "Building G on a Recreation Platform in Cloudrest Retreat": "建筑G位于云歇避风港的一个娱乐平台",
  "Building G on a Recreation Platform in Prospect Point": "建筑G位于眺望点的一个娱乐平台",
  "Building G on a Residency Platform in Empyrean Park": "建筑G位于至高庭园的一个住宅平台",
  "Building H on a Recreation Platform in Cloudrest Retreat": "建筑H位于云歇避风港的一个娱乐平台",
  "Building H on a Recreation Platform in Prospect Point": "建筑H位于眺望点的一个娱乐平台",
  "Building H on a Residency Platform in Empyrean Park": "建筑H位于至高庭园的一个住宅平台",
  "Building I on a Recreation Platform in Cloudrest Retreat": "建筑I位于云歇避风港的一个娱乐平台",
  "Building I on a Recreation Platform in Prospect Point": "建筑I位于眺望点的一个娱乐平台",
  "Building I on a Residency Platform in Empyrean Park": "建筑I位于至高庭园的一个住宅平台",
  "Bullock's Reach": "犍牛原",
  "Bullock's Reach on Pyro VI": "派罗VI上的犍牛原",
  "Burnout": "燃烬地",
  "Burnout on Lyria": "莉瑞雅上的燃烬地",
  "Cafe Musain": "缪尚咖啡馆",
  "Cafe Musain in Levski": "列夫斯基的缪尚咖啡馆",
  "Calhoun Pass Emergency Shelter": "卡洪山口紧急避难所",
  "Calhoun Pass Emergency Shelter on microTech": "微科星上的卡洪山口紧急避难所",
  "Calliope": "卡利俄佩",
  "Calliope Cave": "卡利俄佩洞穴",
  "Canard View": "鸭翼观景处",
  "Canard View on Pyro VI": "派罗VI上的鸭翼观景处",
  "Carver's Ridge": "天工岭",
  "Carver's Ridge on Pyro III": "派罗III上的天工岭",
  "Caterpillar wreck site": "毛虫残骸地点",
  "Cellin": "赛琳",
  "Cellin Cave": "赛琳洞穴",
  "Cellin's Rayari lab": "赛琳上的拉亚利研究室",
  "Cellin's Terra Mills outpost": "赛琳的泰拉磨坊前哨站",
  "Central Core & Power": "中央核心与动力区",
  "Chawla's Beach": "乔拉海滩",
  "Chawla's Beach on Pyro IV": "派罗IV上的乔拉海滩。",
  "Checkmate": "死局空间站",
  "Checkmate Clinic": "死局空间站诊所",
  "Checkmate Entrance": "死局空间站入口",
  "Checkmate Habs": "死局空间站居住区",
  "Checkmate Refinery": "死局空间站精炼站",
  "Checkmate Station": "死局空间站",
  "Checkmate at the L4 Lagrange of Pyro II": "位于派罗II的L4拉格朗日点的死局空间站",
  "Clear View Emergency Shelter": "眺望点紧急避难所",
  "Clear View Emergency Shelter on microTech": "微科星上的清晰视界紧急避难所",
  "Clio": "克利俄",
  "Clio Cave": "克利俄洞穴",
  "Clio Derelict Outpost": "克利俄废弃前哨站",
  "Comm Array ST1-02": "通讯矩阵 ST1-02",
  "Comm Array ST1-02 around Ita": "依塔附近的通讯矩阵 ST1-02",
  "Comm Array ST1-13": "通讯矩阵 ST1-13",
  "Comm Array ST1-48": "通讯矩阵 ST1-48",
  "Comm Array ST1-61": "通讯矩阵 ST1-61",
  "Comm Array ST1-92": "通讯矩阵 ST1-92",
  "Comm Array ST2-28": "通讯矩阵 ST2-28",
  "Comm Array ST2-28 around Cellin": "在赛琳附近的通讯矩阵 ST2-28",
  "Comm Array ST2-47": "通讯矩阵 ST2-47",
  "Comm Array ST2-47 around Daymar": "在戴玛尔附近的通讯矩阵 ST2-47",
  "Comm Array ST2-55": "通讯矩阵 ST2-55",
  "Comm Array ST2-55 around Crusader": "在十字军附近的通讯矩阵 ST2-55",
  "Comm Array ST2-76": "通讯矩阵 ST2-76",
  "Comm Array ST2-76 around Yela": "在耶拉附近的通讯矩阵 ST2-76",
  "Comm Array ST3-18": "通讯阵列 ST3-18",
  "Comm Array ST3-18 around Lyria": "莉瑞雅附近的通讯矩阵 ST3-18",
  "Comm Array ST3-35": "通讯阵列 ST3-35",
  "Comm Array ST3-35 around Wala": "瓦菈附近的通讯矩阵 ST3-35",
  "Comm Array ST3-90": "通讯阵列 ST3-90",
  "Comm Array ST3-90 around ArcCorp": "弧光星附近的通讯矩阵 ST3-90",
  "Comm Array ST4-22": "通信阵列 ST4-22",
  "Comm Array ST4-22 around microTech": "微科星附近的通讯矩阵 ST4-22",
  "Comm Array ST4-31": "通信阵列 ST4-31",
  "Comm Array ST4-31 around Calliope": "卡利欧佩附近的通讯矩阵 ST4-31",
  "Comm Array ST4-59": "通信阵列 ST4-59",
  "Comm Array ST4-59 around Clio": "克利俄附近的通讯矩阵 ST4-59",
  "Comm Array ST4-64": "通信阵列 ST4-64",
  "Comm Array ST4-64 around Euterpe": "欧忒耳佩附近的通讯矩阵 ST4-64",
  "Connor's": "康纳小屋",
  "Connor's on Yela": "耶拉上的康纳小屋",
  "Constellation wreck site": "星座残骸地点",
  "Consumption": "结核地",
  "Consumption on Cellin": "赛琳上的结核地",
  "Covalex Distribution Center S1DC06": "科瓦莱什配送中心 S1DC06",
  "Covalex Distribution Center S1DC06 on Hurston": "赫斯顿上的科瓦莱什配送中心S1DC06",
  "Covalex Distribution Center S1DC11": "科瓦莱什配送中心S1DC11",
  "Covalex Distribution Center S1DC11 on Hurston": "赫斯顿上的科瓦莱什配送中心S1DC11",
  "Covalex Distribution Center S1DC14": "科瓦莱什配送中心S1DC14",
  "Covalex Distribution Center S1DC14 on Hurston": "赫斯顿上的科瓦莱什配送中心S1DC14",
  "Covalex Distribution Center S3BDC01": "科瓦莱什配送中心S3BDC01",
  "Covalex Distribution Center S3BDC01 on Wala": "位于瓦菈的科瓦莱什配送中心S3BDC01",
  "Covalex Distribution Center S4DC01": "科瓦莱什配送中心S4DC01",
  "Covalex Distribution Center S4DC01 on microTech": "位于微科星的科瓦莱什配送中心S4DC01",
  "Covalex Distribution Center S4DC05": "科瓦莱什配送中心S4DC05",
  "Covalex Distribution Center S4DC05 on microTech": "位于微科星的科瓦莱什配送中心S4DC05",
  "Covalex Station Gundo": "科瓦莱什货运站-贡多",
  "Covalex Station Gundo around Daymar": "戴玛尔附近的科瓦莱什货运站-贡多",
  "Coven": "女巫结社",
  "Coven on Arial": "艾瑞尔上的女巫结社",
  "Crash Site": "坠毁地点",
  "Crusader": "十字军",
  "Cry-Astro Processing Plant 19-02": "寒宇加工厂 19-02",
  "Cry-Astro Processing Plant 19-02 on microTech": "微科星上的寒宇加工厂 19-02",
  "Cry-Astro Processing Plant 34-12": "寒宇加工厂 34-12",
  "Cry-Astro Processing Plant 34-12 on microTech": "微科星上的寒宇加工厂 34-12",
  "Cutlass wreck site": "弯刀残骸地点",
  "Cutter's Rig": "扬帆镇",
  "Cutter's Rig on Hurston": "赫斯顿上的扬帆镇",
  "Daymar": "戴玛尔",
  "Daymar Cave": "戴玛尔洞穴",
  "Daymar Derelict Outpost": "戴玛尔废弃前哨站",
  "Deakins Research Outpost": "迪金斯科研前哨站",
  "Deakins Research Outpost on Yela": "耶拉上的迪金斯科研前哨站",
  "Delamar": "戴玛尔",
  "Derelict Outpost": "废弃前哨站",
  "Devlin Scrap & Salvage": "德夫林废品回收站",
  "Devlin Scrap & Salvage on Euterpe": "欧忒耳佩上的德夫林废品回收站",
  "Dinger's Depot": "丁格仓库",
  "Dinger's Depot on Pyro IV": "派罗 IV上的丁格仓库",
  "Downlow": "秘事所",
  "Downlow on Lyria": "莉瑞雅上的秘事所",
  "Drifters": "流民营地",
  "Drifters on microTech": "微科星上的流民营地",
  "Dudley & Daughters": "达德利父女空间站",
  "Dudley & Daughters Clinic": "达德利父女空间站诊所",
  "Dudley & Daughters Entrance": "达德利父女空间站入口",
  "Dudley & Daughters Habs": "达德利父女空间站居住区",
  "Dudley & Daughters at the L4 Lagrange of Pyro VI": "派罗VI的L4拉格朗日点的达德利父女空间站",
  "Dumper's Depot": "倾卸者仓库",
  "Dunboro": "顿波罗镇",
  "Dunboro on microTech": "微科星上的顿波罗镇",
  "Dunlow Ridge Aid Shelter": "顿洛山脉援助避难所",
  "Dunlow Ridge Aid Shelter on Daymar": "戴玛尔上的顿洛山脉援助避难所",
  "Dupree Industrial Manufacturing Facility": "杜普里工业制造设施",
  "Dupree Industrial Manufacturing Facility on Hurston": "赫斯顿上的杜普里工业制造设施",
  "Eager Flats Aid Shelter": "埃格平原援助避难所",
  "Eager Flats Aid Shelter on Daymar": "戴玛尔上的埃格平原援助避难所",
  "Echo Isle": "回声岛",
  "Echo Isle on Hurston": "赫斯顿的回声岛",
  "Endgame": "终局空间站",
  "Endgame Clinic": "终局空间站诊所",
  "Endgame Entrance": "终局空间站入口",
  "Endgame Habs": "终局空间站居住区",
  "Endgame at the L3 Lagrange of Pyro VI": "位于派罗VI的L3拉格朗日点的终局空间站",
  "Endless Odyssey Station at microTech's L3 Lagrange point": "位于微科星的L3拉格朗日点的无尽漫游站",
  "Euterpe": "欧忒耳佩",
  "Euterpe Cave": "欧忒耳佩洞穴",
  "Euterpe Derelict Outpost": "欧忒耳佩废弃前哨站",
  "Everus Harbor": "埃弗勒斯空间站",
  "Everus Harbor above Hurston": "赫斯顿上空的埃弗勒斯空间站",
  "Faint Glen Station at ArcCorp's L4 Lagrange point": "位于弧光星的L4拉格朗日点的黯淡幽谷站",
  "Fairo": "法伊罗",
  "Fairo Cave": "法伊罗洞穴",
  "Faithful Dream Station at Hurston's L2 Lagrange point": "位于赫斯顿的L2拉格朗日点的坚贞梦想站",
  "Fallow Field": "休耕地",
  "Fallow Field on Pyro IV": "派罗IV上的休耕地",
  "Farro Data Center I": "法罗数据中心 I",
  "Farro Data Center I on Pyro IV": "派罗 IV上的法罗数据中心 I",
  "Farro Data Center II": "法罗数据中心 II",
  "Farro Data Center II on Pyro IV": "派罗 IV上的法罗数据中心 II",
  "Farro Data Center III": "法罗数据中心 III",
  "Farro Data Center III on Pyro IV": "派罗 IV上的法罗数据中心 III",
  "Farro Data Center IV": "法罗数据中心 IV",
  "Farro Data Center IV on Pyro IV": "派罗 IV上的法罗数据中心 IV",
  "Farro Data Center IX": "法罗数据中心 IX",
  "Farro Data Center IX on Pyro IV": "派罗 IV上的法罗数据中心 IX",
  "Farro Data Center V": "法罗数据中心 V",
  "Farro Data Center V on Pyro IV": "派罗 IV上的法罗数据中心 V",
  "Farro Data Center VI": "法罗数据中心 VI",
  "Farro Data Center VI on Pyro IV": "派罗 IV上的法罗数据中心 VI",
  "Farro Data Center VII": "法罗数据中心 VII",
  "Farro Data Center VII on Pyro IV": "派罗 IV上的法罗数据中心 VII",
  "Farro Data Center VIII": "法罗数据中心 VIII",
  "Farro Data Center VIII on Pyro IV": "派罗 IV上的法罗数据中心 VIII",
  "Farro Data Center X": "法罗数据中心 X",
  "Farro Data Center X on Pyro IV": "派罗 IV上的法罗数据中心 X",
  "Feo Canyon Depot": "费奥山谷仓库",
  "Feo Canyon Depot on Pyro 5d": "派罗 5d上的费奥山谷仓库",
  "Fetch": "密谋地",
  "Fetch on Cellin": "赛琳上的密谋地",
  "Finance Group": "财务金融部门",
  "Finance Group on the Admin Center near Orison": "位于奥里森行政中心内的财务金融部门",
  "Finn's Folly": "芬恩屋",
  "Finn's Folly on Hurston": "赫斯顿上的芬恩屋",
  "Flanagan's Ravine Aid Shelter": "弗拉纳根峪援助避难所",
  "Flanagan's Ravine Aid Shelter on Cellin": "赛琳上的弗拉纳根峪援助避难所",
  "Flight Crew Training Center": "船员培训中心",
  "Flight Crew Training Center on the Admin Center near Orison": "位于奥里森行政中心内的船员培训中心",
  "Freelancer wreck site": "自由枪骑兵残骸地点",
  "Frigid Knot": "冰结镇",
  "Frigid Knot on Pyro III": "派罗III上的冰结镇",
  "Frontier Fighters Hideout": "边境战士藏身处",
  "Frontier Fighters Hideout on Aberdeen": "阿伯丁上的边境战士藏身处",
  "Frontier Fighters Hideout on Adir": "阿迪尔上的边境战士藏身处",
  "Frontier Fighters Hideout on Ariel": "艾瑞尔上的边境战士藏身处",
  "Frontier Fighters Hideout on Calliope": "卡利俄佩上的边境战士藏身处",
  "Frontier Fighters Hideout on Cellin": "赛琳上的边境战士藏身处",
  "Frontier Fighters Hideout on Clio": "克利俄上的边境战士藏身处",
  "Frontier Fighters Hideout on Daymar": "戴玛尔上的边境战士藏身处",
  "Frontier Fighters Hideout on Euterpe": "欧忒耳佩上的边境战士藏身处",
  "Frontier Fighters Hideout on Fairo": "法伊罗上的边境战士藏身处",
  "Frontier Fighters Hideout on Fuego": "弗果上的边境战士藏身处",
  "Frontier Fighters Hideout on Hurston": "赫斯顿上的边境战士藏身处",
  "Frontier Fighters Hideout on Ignis": "伊格尼斯上的边境战士藏身处",
  "Frontier Fighters Hideout on Ita": "依塔上的边境战士藏身处",
  "Frontier Fighters Hideout on Lyria": "莉瑞雅上的边境战士藏身处",
  "Frontier Fighters Hideout on Magda": "玛格达上的边境战士藏身处",
  "Frontier Fighters Hideout on Pyro I": "派罗 I上的边境战士藏身处",
  "Frontier Fighters Hideout on Pyro II": "派罗 II上的边境战士藏身处",
  "Frontier Fighters Hideout on Pyro III": "派罗 III上的边境战士藏身处",
  "Frontier Fighters Hideout on Pyro IV": "派罗 IV上的边境战士藏身处",
  "Frontier Fighters Hideout on Pyro V": "派罗 V上的边境战士藏身处",
  "Frontier Fighters Hideout on Pyro VI": "派罗 VI上的边境战士藏身处",
  "Frontier Fighters Hideout on Vatra": "瓦塔拉上的边境战士藏身处",
  "Frontier Fighters Hideout on Vuur": "伏尔上的边境战士藏身处",
  "Frontier Fighters Hideout on Wala": "瓦菈上的边境战士藏身处",
  "Frontier Fighters Hideout on Yela": "耶拉上的边境战士藏身处",
  "Frontier Fighters Hideout on microTech": "微科星上的边境战士藏身处",
  "Frostbite": "寒霜镇",
  "Frostbite on microTech": "微科星上的寒霜镇",
  "Fuego Cave": "弗果洞穴",
  "G-HEX": "六角湾",
  "Gallete Family Farms": "加莱特家庭种植站",
  "Gallete Family Farms on Cellin": "赛琳上的加莱特家庭种植站",
  "Gallete Farms": "加莱特种植站",
  "Gaslight": "煤气灯空间站",
  "Gaslight Clinic": "煤气灯空间站诊所",
  "Gaslight Entrance": "煤气灯空间站入口",
  "Gaslight Habs": "煤气灯空间站居住区",
  "Gaslight at the L2 Lagrange of Pyro V": "派罗V的L2拉格朗日点的煤气灯空间站",
  "Ghost Hollow": "幽灵洼地",
  "Ghost Hollow on microTech": "微科星上的幽灵洼地",
  "Glaciem Ring": "冰川环带",
  "Glaciem Ring Cluster": "冰川环带小行星群",
  "Goner's Deal": "垂死者交易所",
  "Goner's Deal on Pyro IV": "派罗IV上的垂死者交易所",
  "Gonzo": "狂乱营地",
  "Gonzo on Magda": "玛格达上的狂乱营地",
  "Good Times Temple": "美好时光神庙",
  "Good Times Temple on Wala": "瓦菈上的“美好时光神庙”",
  "Gray Gardens Depot": "灰园仓库",
  "Gray Gardens Depot on Pyro I": "派罗 I上的灰园仓库",
  "Green Glade Station at Hurston's L1 Lagrange point": "位于赫斯顿的L1拉格朗日点的绿色林地站",
  "Green Imperial": "格林皇家",
  "Greycat Stanton I Production Complex-B": "灰猫斯坦顿I生产综合体-B",
  "Greycat Stanton I Production Complex-B on Hurston": "赫斯顿上的灰猫工业斯坦顿I生产综合体-B",
  "Greycat Stanton IV Production Complex-A": "灰猫斯坦顿IV生产综合体-A",
  "Greycat Stanton IV Production Complex-A on microTech": "位于微科星的灰猫工业斯坦顿IV生产综合体-A",
  "Grim HEX": "六角湾",
  "Grim HEX within Yela's asteroid belt": "耶拉的小行星带的六角湾",
  "HDES-Calthrope": "HDES-卡尔斯罗普矿洞",
  "HDES-Calthrope on Hurston": "赫斯顿上的 HDES-卡尔斯罗普矿洞",
  "HDES-Dobbs": "HDES-多布斯矿洞",
  "HDES-Dobbs on Aberdeen": "位于阿伯丁上的 HDES-多布斯矿洞",
  "HDMS-Ackley": "HDMS-阿克莱站",
  "HDMS-Ackley on Hurston": "赫斯顿上的HDMS-阿克莱站",
  "HDMS-Anderson": "HDMS-安德森站",
  "HDMS-Anderson on Aberdeen": "阿伯丁上的HDMS-安德森站",
  "HDMS-Bezdek": "HDMS-贝兹德克站",
  "HDMS-Bezdek on Arial": "艾瑞尔上的HDMS-贝兹德克站",
  "HDMS-Edmond": "HDMS-埃得蒙德站",
  "HDMS-Edmond on Hurston": "赫斯顿上的HDMS-埃德蒙德站",
  "HDMS-Hadley": "HDMS-哈德利站",
  "HDMS-Hadley on Hurston": "赫斯顿上的HDMS-哈德利站",
  "HDMS-Hahn": "HDMS-哈恩站",
  "HDMS-Hahn on Magda": "玛格达上的HDMS-哈恩站",
  "HDMS-Lathan": "HDMS-莱森站",
  "HDMS-Lathan on Arial": "艾瑞尔上的HDMS-莱森站",
  "HDMS-Norgaard": "HDMS-诺加德站",
  "HDMS-Norgaard on Aberdeen": "阿伯丁上的HDMS-诺加德站",
  "HDMS-Oparei": "HDMS-奥派雷站",
  "HDMS-Oparei on Hurston": "赫斯顿上的HDMS-奥派雷站",
  "HDMS-Perlman": "HDMS-佩尔曼站",
  "HDMS-Perlman on Magda": "玛格达上的HDMS-佩尔曼站",
  "HDMS-Pinewood": "HDMS-派恩伍德站",
  "HDMS-Pinewood on Hurston": "赫斯顿上的派恩伍德站",
  "HDMS-Ryder": "HDMS-莱德站",
  "HDMS-Ryder on Ita": "依塔上的HDMS-莱德站",
  "HDMS-Stanhope": "HDMS-斯坦霍普站",
  "HDMS-Stanhope on Hurston": "赫斯顿上的HDMS-斯坦霍普站",
  "HDMS-Thedus": "HDMS-赛达斯站",
  "HDMS-Thedus on Hurston": "赫斯顿上的HDMS-赛达斯站",
  "HDMS-Woodruff": "HDMS-伍德拉夫站",
  "HDMS-Woodruff on Ita": "依塔上的HDMS-伍德拉夫站",
  "HDOF-Palomar": "HDOF-帕洛马尔",
  "HDOF-Palomar on Hurston": "赫斯顿上的HDOF-帕洛马尔",
  "HDPC-Cassillo": "HDPC-卡西洛",
  "HDPC-Cassillo on Hurston": "赫斯顿上的HDPC-卡西洛",
  "HDPC-Farnesway": "HDPC-法内斯威",
  "HDPC-Farnesway on Hurston": "赫斯顿上的HDPC-法内斯威",
  "HDRSO-Baier": "HDRSO-贝尔站",
  "HDRSO-Baier on Hurston": "赫斯顿上的HDRSO-贝尔站",
  "HDRSO-Bardie": "HDRSO-巴蒂站",
  "HDRSO-Bardie on Hurston": "赫斯顿上的HDRSO-巴蒂站",
  "HDRSO-Bersch": "HDRSO-贝施站",
  "HDRSO-Bersch on Hurston": "赫斯顿上的HDRSO-贝施站",
  "HDRSO-Bowes": "HDRSO-鲍斯站",
  "HDRSO-Bowes on Hurston": "赫斯顿上的HDRSO-鲍斯站",
  "HDRSO-Bramen": "HDRSO-布拉曼哨所",
  "HDRSO-Brel": "HDRSO-布雷尔站",
  "HDRSO-Brel on Hurston": "赫斯顿上的HDRSO-布雷尔站",
  "HDRSO-Cronshaw": "HDRSO-克朗肖站",
  "HDRSO-Cronshaw on Hurston": "赫斯顿上的HDRSO-克朗肖站",
  "HDRSO-Foster": "HDRSO-福斯特站",
  "HDRSO-Foster on Hurston": "赫斯顿上的HDRSO-福斯特站",
  "HDRSO-Franz": "HDRSO-弗兰兹站",
  "HDRSO-Franz on Hurston": "赫斯顿上的HDRSO-弗兰兹站",
  "HDRSO-Giblin": "HDRSO-吉布林站",
  "HDRSO-Giblin on Hurston": "赫斯顿上的HDRSO-吉布林站",
  "HDRSO-Hosley": "HDRSO-霍斯利站",
  "HDRSO-Hosley on Hurston": "赫斯顿上的HDRSO-霍斯利站",
  "HDRSO-Malloy": "HDRSO-马洛伊站",
  "HDRSO-Malloy on Hurston": "赫斯顿上的HDRSO-马洛伊站",
  "HDRSO-Marling": "HDRSO-马林站",
  "HDRSO-Marling on Hurston": "赫斯顿上的HDRSO-马林站",
  "HDRSO-McKuen": "HDRSO-麦昆站",
  "HDRSO-McKuen on Hurston": "赫斯顿上的HDRSO-麦昆站",
  "HDRSO-Newman": "HDRSO-纽曼站",
  "HDRSO-Newman on Hurston": "赫斯顿上的HDRSO-纽曼站",
  "HDRSO-Olliff": "HDRSO-奥利弗站",
  "HDRSO-Olliff on Hurston": "赫斯顿上的HDRSO-奥利弗站",
  "HDRSO-Pearce": "HDRSO-皮尔斯站",
  "HDRSO-Pearce on Hurston": "赫斯顿上的HDRSO-皮尔斯站",
  "HDRSO-Sheppard": "HDRSO-谢泼德站",
  "HDRSO-Sheppard on Hurston": "赫斯顿上的HDRSO-谢泼德站",
  "HDRSO-Sims": "HDRSO-西姆斯站",
  "HDRSO-Sims on Hurston": "赫斯顿上的HDRSO-西姆斯站",
  "HDRSO-Stott": "HDRSO-斯托特站",
  "HDRSO-Stott on Hurston": "赫斯顿上的HDRSO-斯托特站",
  "HDRSO-Tillman": "HDRSO-蒂尔曼站",
  "HDRSO-Tillman on Hurston": "赫斯顿上的HDRSO-蒂尔曼站",
  "HDRSO-Walker": "HDRSO-沃克站",
  "HDRSO-Walker on Hurston": "赫斯顿上的HDRSO-沃克站",
  "HDRSO-Wyatt": "HDRSO-怀亚特站",
  "HDRSO-Wyatt on Hurston": "赫斯顿上的HDRSO-怀亚特站",
  "HDSF-Adlai": "HDSF-阿德莱站",
  "HDSF-Adlai on Hurston": "赫斯顿上的HDSF-阿德莱站",
  "HDSF-Barnabas": "HDSF-巴纳巴斯站",
  "HDSF-Barnabas on Hurston": "赫斯顿上的HDSF-巴纳巴斯站",
  "HDSF-Breckinridge": "HDSF-布雷肯里奇站",
  "HDSF-Breckinridge on Hurston": "赫斯顿上的HDSF-布雷肯里奇站",
  "HDSF-Colfax": "HDSF-科尔法克斯站",
  "HDSF-Colfax on Hurston": "赫斯顿上的HDSF-科尔法克斯站",
  "HDSF-Damaris": "HDSF-达莫里斯站",
  "HDSF-Damaris on Hurston": "赫斯顿上的HDSF-达莫里斯站",
  "HDSF-Elbridge": "HDSF-埃尔布里奇站",
  "HDSF-Elbridge on Hurston": "HDSF-赫斯顿上的埃尔布里奇站",
  "HDSF-Hendricks": "HDSF-亨得利斯克站",
  "HDSF-Hendricks on Hurston": "赫斯顿上的HDSF-亨得利斯克站",
  "HDSF-Hiram": "HDSF-海勒姆站",
  "HDSF-Hiram on Hurston": "赫斯顿上的HDSF-海勒姆站",
  "HDSF-Hobart": "HDSF-霍巴特站",
  "HDSF-Hobart on Hurston": "赫斯顿上HDSF-的霍巴特站",
  "HDSF-Ishmael": "HDSF-以赛玛利站",
  "HDSF-Ishmael on Hurston": "赫斯顿上的HDSF-以赛玛利站",
  "HDSF-Millerand": "HDSF-米尔兰德站",
  "HDSF-Millerand on Hurston": "赫斯顿上的HDSF-米尔兰德站",
  "HDSF-Rufus": "HDSF-卢福斯站",
  "HDSF-Rufus on Hurston": "赫斯顿上的HDSF-卢福斯站",
  "HDSF-Sherman": "HDSF-谢尔曼站",
  "HDSF-Sherman on Hurston": "赫斯顿上的HDSF-谢尔曼站",
  "HDSF-Tamar": "HDSF-塔玛站",
  "HDSF-Tamar on Hurston": "赫斯顿上的HDSF-塔玛站",
  "HDSF-Tompkins": "HDSF-汤普金斯站",
  "HDSF-Tompkins on Hurston": "赫斯顿上的HDSF-汤普金斯站",
  "HDSF-Zacharia on Hurston": "赫斯顿上的HDSF-撒加利亚站",
  "HDSF-Zacharias": "HDSF-撒加利亚站",
  "HDSRO-Bramen on Hurston": "赫斯顿上的布拉曼哨所",
  "HMR-A on Hartmoore Platform near Orison": "位于奥里森附近哈特莫尔平台上的HMR-A",
  "HMR-B on Hartmoore Platform near Orison": "位于奥里森附近哈特莫尔平台上的HMR-B",
  "HMR-C on Hartmoore Platform near Orison": "位于奥里森附近哈特莫尔平台上的HMR-C",
  "HMR-D on Hartmoore Platform near Orison": "位于奥里森附近哈特莫尔平台上的HMR-D",
  "HMR-E on Hartmoore Platform near Orison": "位于奥里森附近哈特莫尔平台上的HMR-E",
  "HMR-F on Hartmoore Platform near Orison": "位于奥里森附近哈特莫尔平台上的HMR-F",
  "HMR-G on Hartmoore Platform near Orison": "位于奥里森附近哈特莫尔平台上的HMR-G",
  "HMR-H on Hartmoore Platform near Orison": "位于奥里森附近哈特莫尔平台上的HMR-H",
  "HMR-I on Hartmoore Platform near Orison": "位于奥里森附近哈特莫尔平台上的HMR-I",
  "Half Stack": "半丘",
  "Half Stack on Yela": "耶拉上的半丘",
  "Hangar 11": "机库 11",
  "Hangar 11 inside Orbituary above Pyro III": "派罗III上空的轨道讣闻站内的11号机库",
  "Hangar 12": "机库 12",
  "Hangar 12 inside Patch City at the L3 Lagrange of Pyro III": "派罗III的L3拉格朗日点的补丁城内的12号机库",
  "Hangar 12 inside Starlight Service Station at the L1 Lagrange of Pyro III": "派罗III的L1拉格朗日点的星光服务站内的12号机库",
  "Hangar 13": "机库 13",
  "Hangar 13 inside Checkmate at the L4 Lagrange of Pyro II": "位于派罗II的L4拉格朗日点的死局空间站内的13号机库",
  "Hangar 13 inside Dudley & Daughters at the L4 Lagrange of Pyro VI": "派罗VI的L4拉格朗日点的达德利父女空间站内的13号机库",
  "Hangar 13 inside Endgame at the L3 Lagrange of Pyro VI": "位于派罗VI的L3拉格朗日点的终局空间站内的13号机库",
  "Hangar 13 inside Gaslight at the L2 Lagrange of Pyro V": "派罗V的L2拉格朗日点的煤气灯空间站内的13号机库",
  "Hangar 13 inside Megumi Refueling at the L5 Lagrange of Pyro VI": "派罗VI的L5拉格朗日点的恩惠加油站内的13号机库",
  "Hangar 13 inside PYAM-FARSTAT-1-2 at the L2 Lagrange of Pyro I": "位于派罗I的L2拉格朗日点的焰联-远程站-1-2内的13号机库",
  "Hangar 13 inside PYAM-FARSTAT-1-3 at the L3 Lagrange of Pyro I": "位于派罗I的L3拉格朗日点的焰联-远程站-1-3内的13号机库",
  "Hangar 13 inside PYAM-FARSTAT-1-5 at the L5 Lagrange of Pyro I": "位于派罗I的L5拉格朗日点的焰联-远程站-1-5内的13号机库",
  "Hangar 13 inside PYAM-FARSTAT-2-0 above Pyro II": "位于派罗II上空的焰联-远程站-2-0内的13号机库",
  "Hangar 13 inside PYAM-FARSTAT-2-3 at the L3 Lagrange of Pyro II": "位于派罗II的L3拉格朗日点的焰联-远程站-2-3内的13号机库",
  "Hangar 13 inside PYAM-FARSTAT-3-5 at the L5 Lagrange of Pyro III": "位于派罗III的L5拉格朗日点的焰联-远程站-3-5内的13号机库",
  "Hangar 13 inside PYAM-FARSTAT-5-1 at the L1 Lagrange of Pyro V": "位于派罗V的L1拉格朗日点的焰联-远程站-5-1内的13号机库",
  "Hangar 13 inside PYAM-FARSTAT-5-3 at the L3 Lagrange of Pyro V": "位于派罗V的L3拉格朗日点的焰联-远程站-5-3内的13号机库",
  "Hangar 13 inside PYAM-FARSTAT-6-2 at the L2 Lagrange of Pyro VI": "位于派罗VI的L2拉格朗日点的焰联-远程站-6-2内的13号机库",
  "Hangar 13 inside Rat's Nest at the L5 Lagrange of Pyro V": "位于派罗V的L5拉格朗日点的鼠巢空间站内的13号机库",
  "Hangar 13 inside Rod's Fuel 'N Supplies at the L4 Lagrange of Pyro V": "派罗V的L4拉格朗日点的路德补给站内的13号机库",
  "Hard Knocks": "铁拳擂台",
  "Hard Knocks on Calliope": "卡利俄佩上的铁拳擂台",
  "Harper's Point": "竖琴手之角",
  "Harper's Point on microTech": "微科星上的竖琴手之角",
  "Hartmoore Platform": "哈特莫尔平台",
  "Hartmoore Platform at Inspiration Park near Orison": "位于奥里森的灵感园区的哈特莫尔平台",
  "Hasbin Hall": "哈斯宾厅",
  "Hasbin Hall on Calliope": "卡利俄佩上的哈斯宾厅",
  "Hela's Regret": "海拉遗地",
  "Hela's Regret on microTech": "微科星上的海拉遗地",
  "Hickes Research Outpost": "希克斯研究站",
  "Hickes Research Outpost on Cellin": "赛琳上的希克斯研究站",
  "High Course Station at Hurston's L5 Lagrange point": "位于赫斯顿的L5拉格朗日点的高速路线站",
  "Hospice": "善终之所",
  "Hospice on Daymar": "戴玛尔上的善终之所",
  "Humboldt Mines": "洪保德矿站",
  "Humboldt Mines on Lyria": "莉瑞雅上的洪保德矿站",
  "Hurston": "赫斯顿",
  "Hurston Cave": "赫斯顿洞穴",
  "Hurston Derelict Outpost": "赫斯顿废弃前哨站",
  "IO-North Admin Office": "IO北区行政办公室",
  "IO-North Admin Office in Area18": "18区的IO北区行政办公室",
  "Ignis": "伊格尼斯",
  "Ignis Cave": "伊格尼斯洞穴",
  "Ita": "依塔",
  "Ita Cave": "依塔的洞穴",
  "Ita Derelict Outpost": "依塔废弃前哨站",
  "Jackson's Swap": "杰克森交易站",
  "Jackson's Swap on Pyro II": "派罗II上的杰克森交易站",
  "Julep Ravine Aid Shelter": "朱利普峡谷援助避难所",
  "Julep Ravine Aid Shelter on Cellin": "赛琳上的朱利普峡谷援助避难所",
  "Jumptown": "跃动小镇",
  "Jumptown on Daymar": "戴玛尔上的跃动小镇",
  "Kabir's Post": "卡比尔驿站",
  "Kabir's Post on Pyro 5a": "派罗5a上的卡比尔驿站",
  "Kant's Peak": "康德峰",
  "Kant's Peak on Clio": "克利俄上的康德峰",
  "Kareah": "加利亚",
  "Keeger Belt Cluster": "基格小行星带小行星群",
  "Keeger Belt Wreck Site": "基格小行星带残骸地点",
  "Kelo Bottom": "科洛谷底",
  "Kelo Bottom on microTech": "微科星上的科洛谷底",
  "Kinder Plots": "容善镇",
  "Kinder Plots on Pyro VI": "派罗VI上的容善镇",
  "Klescher Rehabilitation": "克莱舍尔劳教所",
  "Klescher Rehabilitation Facilities on Aberdeen": "位于阿伯丁上的克莱舍尔劳教所",
  "Kosso Basin Aid Shelter": "科索盆地援助避难所",
  "Kosso Basin Aid Shelter on Yela": "耶拉上的科索盆地援助避难所",
  "Kudre Ore": "库德雷矿井",
  "Kudre Ore on Daymar": "戴玛尔上的库雷德矿井",
  "L19 Admin Office in Lorville": "罗威尔L19行政办公室",
  "L19 Habs in Lorville": "罗威尔的L19居住区",
  "L19 Metro Station in Lorville": "罗威尔L19地铁站",
  "Lamina OLP": "薄片 激光站",
  "Lamina Orbital Laser Platform above Daymar": "戴玛尔上的薄片 轨道激光平台",
  "Lamina PAF-I": "薄片 校准站-I",
  "Lamina PAF-II": "薄片 校准站-II",
  "Lamina PAF-III": "薄片 校准站-III",
  "Lamina Platform Alignment Facility I on Daymar": "戴玛尔上的薄片 平台校准设施I",
  "Lamina Platform Alignment Facility II on Daymar": "戴玛尔上的薄片 平台校准设施II",
  "Lamina Platform Alignment Facility III on Daymar": "戴玛尔上的薄片 平台校准设施III",
  "Landing Pad Locker": "停机坪储物柜",
  "Last Day": "弥留处",
  "Last Day on Lyria": "莉瑞雅上的弥留处",
  "Last Ditch": "最终防线",
  "Last Ditch on Pyro II": "派罗II上的最终防线",
  "Last Landings": "终陆镇",
  "Last Landings on Pyro VI": "派罗VI上的终陆镇",
  "Lazarus Complex Phoenix-I": "拉撒路综合体 不死鸟-I",
  "Lazarus Complex Phoenix-I on Pyro I": "派罗I上的拉撒路综合体 不死鸟-I",
  "Lazarus Complex Phoenix-II": "拉撒路综合体 不死鸟-II",
  "Lazarus Complex Phoenix-II on Pyro I": "派罗I上的拉撒路综合体 不死鸟-II",
  "Lazarus Complex Phoenix-III": "拉撒路综合体 不死鸟-III",
  "Lazarus Complex Phoenix-III on Pyro I": "派罗I上的拉撒路综合体 不死鸟-III",
  "Lazarus Complex Tithonus-I": "拉撒路综合体 提托诺斯-I",
  "Lazarus Complex Tithonus-I on Pyro I": "派罗I上的拉撒路综合体 提托诺斯-I",
  "Lazarus Complex Tithonus-II": "拉撒路综合体 提托诺斯-II",
  "Lazarus Complex Tithonus-II on Pyro I": "派罗I上的拉撒路综合体 提托诺斯-II",
  "Lazarus Complex Tithonus-III": "拉撒路综合体 提托诺斯-III",
  "Lazarus Complex Tithonus-III on Pyro I": "派罗I上的拉撒路综合体 提托诺斯-III",
  "Lazarus Transport Hub Phoenix-I": "拉撒路交通站 不死鸟-I",
  "Lazarus Transport Hub Phoenix-I on Pyro I": "派罗I上的拉撒路交通站 不死鸟-I",
  "Lazarus Transport Hub Phoenix-II": "拉撒路交通站 不死鸟-II",
  "Lazarus Transport Hub Phoenix-II on Pyro I": "派罗I上的拉撒路交通站 不死鸟-II",
  "Lazarus Transport Hub Phoenix-III": "拉撒路交通站 不死鸟-III",
  "Lazarus Transport Hub Phoenix-III on Pyro I": "派罗I上的拉撒路交通站 不死鸟-III",
  "Lazarus Transport Hub Tithonus-I": "拉撒路交通站 提托诺斯-I",
  "Lazarus Transport Hub Tithonus-I on Pyro I": "派罗I上的拉撒路交通站 提托诺斯-I",
  "Lazarus Transport Hub Tithonus-II": "拉撒路交通站 提托诺斯-II",
  "Lazarus Transport Hub Tithonus-II on Pyro I": "派罗I上的拉撒路交通站 提托诺斯-II",
  "Lazarus Transport Hub Tithonus-III": "拉撒路交通站 提托诺斯-III",
  "Lazarus Transport Hub Tithonus-III on Pyro I": "派罗I上的拉撒路交通站 提托诺斯-III",
  "Levski": "列夫斯基",
  "Lively Pathway Station at ArcCorp's L2 Lagrange point": "位于弧光星的L2拉格朗日点的活力小径站",
  "Long Forest Station at microTech's L2 Lagrange point": "位于微科星的L2拉格朗日点的长林站",
  "Lorville": "罗威尔",
  "Lorville Gate 01": "罗威尔1号城门",
  "Lorville Gate 02": "罗威尔2号城门",
  "Lorville Gate 03": "罗威尔3号城门",
  "Lorville Gate 04": "罗威尔4号城门",
  "Lorville Gate 05": "罗威尔5号城门",
  "Lorville Gate 06": "罗威尔6号城门",
  "Lorville on Hurston": "赫斯顿上的罗威尔",
  "Loveridge Mineral Reserve": "洛维里奇矿站",
  "Loveridge Mineral Reserve on Lyria": "莉瑞雅上的洛维里奇矿站",
  "Lowdown": "实信镇",
  "Lowdown on Hurston": "赫斯顿上的实信镇",
  "Ludlow": "勒德洛镇",
  "Ludlow on Hurston": "赫斯顿上的勒德洛镇",
  "Lyria": "莉瑞雅",
  "Lyria Derelict Outpost": "莉瑞雅废弃前哨站",
  "M&V Bar": "M&V酒吧",
  "M&V Bar in Lorville": "罗威尔的M&V酒吧",
  "MT DataCenter 2UB-RB9-5": "微科数据中心 2UB-RB9-5",
  "MT DataCenter 2UB-RB9-5 on microTech": "微科星上的微科数据中心 2UB-RB9-5",
  "MT DataCenter 4HJ-LVE-A": "微科数据中心 4HJ-LVE-A",
  "MT DataCenter 4HJ-LVE-A on microTech": "微科星上的微科数据中心 4HJ-LVE-A",
  "MT DataCenter 5WQ-R2V-C": "微科数据中心 5WQ-R2V-C",
  "MT DataCenter 5WQ-R2V-C on microTech": "微科星上的微科数据中心 5WQ-R2V-C",
  "MT DataCenter 8FK-Q2X-K": "微科数据中心 8FK-Q2X-K",
  "MT DataCenter 8FK-Q2X-K on microTech": "微科星上的微科数据中心 8FK-Q2X-K",
  "MT DataCenter D79-ECG-R": "微科数据中心 D79-ECG-R",
  "MT DataCenter D79-ECG-R on microTech": "微科星上的微科数据中心 D79-ECG-R",
  "MT DataCenter E2Q-NSG-Y": "微科数据中心 E2Q-NSG-Y",
  "MT DataCenter E2Q-NSG-Y on microTech": "微科星上的微科数据中心 E2Q-NSG-Y",
  "MT DataCenter KH3-AAE-L": "微科数据中心 KH3-AAE-L",
  "MT DataCenter KH3-AAE-L on microTech": "微科上的微科数据中心 KH3-AAE-L",
  "MT DataCenter L8P-JUC-8": "微科数据中心 L8P-JUC-8",
  "MT DataCenter L8P-JUC-8 on microTech": "微科上的微科数据中心L8P-JUC-8",
  "MT DataCenter QVX-J88-J": "微科数据中心 QVX-J88-J",
  "MT DataCenter QVX-J88-J on microTech": "微科星上的微科数据中心 QVX-J88-J",
  "MT DataCenter TMG-XEV-2": "微科数据中心 TMG-XEV-2",
  "MT DataCenter TMG-XEV-2 on microTech": "微科星上的微科数据中心 TMG-XEV-2",
  "MT OpCenter TLI-4": "微科运营中心 TLI-4",
  "MT OpCenter TLI-4 on microTech": "微科星上的微科运营中心 TLI-4",
  "MT Planetary Services": "微科星球公务部",
  "MT Planetary Services in the New Babbage Plaza": "新巴贝奇市民广场里的微科星球公务部",
  "MT SecurityCenter 4HJ-LVE-A": "微科安全中心 4HJ-LVE-A",
  "MT SecurityCenter 4HJ-LVE-A on microTech": "微科星上的微科安全中心 4HJ-LVE-A",
  "MT SecurityCenter 6EE-GVH-9": "微科安全中心 6EE-GVH-9",
  "MT SecurityCenter 6EE-GVH-9 on Calliope": "卡利俄佩上的微科安全中心 6EE-GVH-9",
  "MT SecurityCenter 9PL-Q42-K": "微科安全中心 9PL-Q42-K",
  "MT SecurityCenter 9PL-Q42-K on microTech": "微科星上的微科安全中心 9PL-Q42-K",
  "MT SecurityCenter 9WB-HV7-P": "微科安全中心 9WB-HV7-P",
  "MT SecurityCenter 9WB-HV7-P on microTech": "微科星上的微科安全中心 9WB-HV7-P",
  "MT SecurityCenter BH5-KEH-6": "微科安全中心 BH5-KEH-6",
  "MT SecurityCenter BH5-KEH-6 on microTech": "微科星上的微科安全中心 BH5-KEH-6",
  "MT SecurityCenter CTB-B3U-1": "微科安全中心 CTB-B3U-1",
  "MT SecurityCenter CTB-B3U-1 on Calliope": "卡利俄佩上的微科安全中心 CTB-B3U-1",
  "MT SecurityCenter D66-CRW-F": "微科安全中心 D66-CRW-F",
  "MT SecurityCenter D66-CRW-F on microTech": "微科星上的微科安全中心 D66-CRW-F",
  "MT SecurityCenter DRC-F2S-6": "微科安全中心 DRC-F2S-6",
  "MT SecurityCenter DRC-F2S-6 on microTech": "微科星上的微科安全中心 DRC-F2S-6",
  "MT SecurityCenter DXC-25G-L": "微科安全中心 DXC-25G-L",
  "MT SecurityCenter DXC-25G-L on Calliope": "卡利俄佩上的微科安全中心 DXC-25G-L",
  "MT SecurityCenter E6C-BRT-M": "微科安全中心 E6C-BRT-M",
  "MT SecurityCenter E6C-BRT-M on microTech": "微科星上的微科安全中心 E6C-BRT-M",
  "MT SecurityCenter FQ5-URX-8": "微科安全中心 FQ5-URX-8",
  "MT SecurityCenter FQ5-URX-8 on Calliope": "卡利俄佩上的微科安全中心 FQ5-URX-8",
  "MT SecurityCenter GSW-NM3-E": "微科安全中心 GSW-NM3-E",
  "MT SecurityCenter GSW-NM3-E on microTech": "微科星上的微科安全中心 GSW-NM3-E",
  "MT SecurityCenter H36-YBG-R": "微科安全中心 H36-YBG-R",
  "MT SecurityCenter H36-YBG-R on Calliope": "卡利俄佩上的微科安全中心 H36-YBG-R",
  "MT SecurityCenter JWB-D9L-4": "微科安全中心 JWB-D9L-4",
  "MT SecurityCenter JWB-D9L-4 on Calliope": "卡利俄佩上的微科安全中心 JWB-D9L-4",
  "MT SecurityCenter KWS-GPZ-5": "微科安全中心 KWS-GPZ-5",
  "MT SecurityCenter KWS-GPZ-5 on Calliope": "卡利俄佩上的微科安全中心 KWS-GPZ-5",
  "MT SecurityCenter OEE-5RG-5": "微科安全中心 OEE-5RG-5",
  "MT SecurityCenter OEE-5RG-5 on microTech": "微科星上的微科安全中心 OEE-5RG-5",
  "MT SecurityCenter PLM-9YW-Q": "微科安全中心 PLM-9YW-Q",
  "MT SecurityCenter PLM-9YW-Q on Calliope": "卡利俄佩上的微科安全中心 PLM-9YW-Q",
  "MT SecurityCenter SLP-VC3-W": "微科安全中心 SLP-VC3-W",
  "MT SecurityCenter SLP-VC3-W on microTech": "微科星上的微科安全中心 SLP-VC3-W",
  "MT SecurityCenter UDB-Z4W-2": "微科安全中心 UDB-Z4W-2",
  "MT SecurityCenter UDB-Z4W-2 on microTech": "微科星上的微科安全中心 UDB-Z4W-2",
  "MT SecurityCenter VD9-87R-P": "微科安全中心 VD9-87R-P",
  "MT SecurityCenter VD9-87R-P on Calliope": "卡利俄佩上的微科安全中心 VD9-87R-P",
  "MT SecurityCenter XGT-33W-7": "微科安全中心 XGT-33W-7",
  "MT SecurityCenter XGT-33W-7 on microTech": "微科星上的微科安全中心 XGT-33W-7",
  "Magda": "玛格达",
  "Magda Cave": "玛格达的洞穴",
  "Magda Derelict Outpost": "玛格达废弃前哨站",
  "Mainline": "主线",
  "Mainline on Yela": "耶拉上的主线",
  "Maintenace Area-02 inside Endgame at the L3 Lagrange of Pyro VI": "位于派罗VI的L3拉格朗日点的终局空间站内的维修区-02",
  "Maintenance Area-01": "维修区-01",
  "Maintenance Area-01 inside Checkmate at the L4 Lagrange of Pyro II": "位于派罗II的L4拉格朗日点的死局空间站内的维修区-01",
  "Maintenance Area-01 inside Dudley & Daughters at the L4 Lagrange of Pyro VI": "位于派罗VI的L4拉格朗日点的达德利父女空间站内的维修区-01",
  "Maintenance Area-01 inside Endgame at the L3 Lagrange of Pyro VI": "位于派罗VI的L3拉格朗日点的终局空间站内的维修区-01",
  "Maintenance Area-01 inside Gaslight at the L2 Lagrange of Pyro V": "位于派罗V的L2拉格朗日点的煤气灯空间站内的维修区-01",
  "Maintenance Area-01 inside Megumi Refueling at the L5 Lagrange of Pyro VI": "位于派罗VI的L5拉格朗日点的恩惠加油站内的维修区-01",
  "Maintenance Area-01 inside Orbituary above Pyro III": "位于派罗III上空的轨道讣闻站内的维修区-01",
  "Maintenance Area-01 inside Patch City at the L3 Lagrange of Pyro III": "位于派罗III的L3拉格朗日点的补丁城内的维修区-01",
  "Maintenance Area-01 inside Rat's Nest at the L5 Lagrange of Pyro V": "位于派罗V的L5拉格朗日点的鼠巢空间站内的维修区-01",
  "Maintenance Area-01 inside Rod's Fuel 'N Supplies at the L4 Lagrange of Pyro V": "位于派罗V的L4拉格朗日点的路德补给站内的维修区-01",
  "Maintenance Area-02": "维修区-02",
  "Maintenance Area-02 inside Checkmate at the L4 Lagrange of Pyro II": "位于派罗II的L4拉格朗日点的死局空间站内的维修区-02",
  "Maintenance Area-02 inside Dudley & Daughters at the L4 Lagrange of Pyro VI": "位于派罗VI的L4拉格朗日点的达德利父女空间站内的维修区-02",
  "Maintenance Area-02 inside Gaslight at the L2 Lagrange of Pyro V": "位于派罗V的L2拉格朗日点的煤气灯空间站内的维修区-02",
  "Maintenance Area-02 inside Megumi Refueling at the L5 Lagrange of Pyro VI": "位于派罗VI的L5拉格朗日点的恩惠加油站内的维修区-02",
  "Maintenance Area-02 inside Orbituary above Pyro III": "位于派罗III上空的轨道讣闻站内的维修区-02",
  "Maintenance Area-02 inside Patch City at the L3 Lagrange of Pyro III": "位于派罗III的L3拉格朗日点的补丁城内的维修区-02",
  "Maintenance Area-02 inside Rat's Nest at the L5 Lagrange of Pyro V": "位于派罗V的L5拉格朗日点的鼠巢空间站内的维修区-02",
  "Maintenance Area-02 inside Rod's Fuel 'N Supplies at the L4 Lagrange of Pyro V": "位于派罗V的L4拉格朗日点的路德补给站内的维修区-02",
  "Maintenance Area-03": "维修区-03",
  "Maintenance Area-03 inside Checkmate at the L4 Lagrange of Pyro II": "位于派罗II的L4拉格朗日点的死局空间站内的维修区-03",
  "Maintenance Area-03 inside Orbituary above Pyro III": "位于派罗III上空的轨道讣闻站内的维修区-03",
  "Maker's Point": "制造点",
  "Maker's Point on Hurston": "赫斯顿上的制造点",
  "Megumi Refueling": "恩惠加油站",
  "Megumi Refueling Clinic": "恩惠加油站诊所",
  "Megumi Refueling Entrance": "恩惠加油站入口",
  "Megumi Refueling Habs": "恩惠加油站居住区",
  "Megumi Refueling at the L5 Lagrange of Pyro VI": "派罗VI的L5拉格朗日点的恩惠加油站",
  "Melodic Fields Station at Hurston's L4 Lagrange point": "位于赫斯顿的L4拉格朗日点的旋律领域站",
  "MicroTech": "微科公司",
  "Minlo Spire": "明洛塔",
  "Minlo Spire on Daymar": "戴玛尔上的明洛塔",
  "Modern Express Station at ArcCorp's L3 Lagrange point": "位于弧光星的L3拉格朗日点的摩登快车站",
  "Modern Icarus Station at microTech's L5 Lagrange point": "位于微科星的L5拉格朗日点的现代伊卡洛斯站",
  "Mogote Aid Shelter": "莫格特援助避难所",
  "Mogote Aid Shelter on Cellin": "赛琳上的莫格特援助避难所",
  "Monox": "殁氧星",
  "Moreland Hills": "莫兰山",
  "Moreland Hills on microTech": "微科星上的莫兰山",
  "NB Int. Spaceport": "新巴贝奇星际空港",
  "NB Int. Spaceport on microTech": "微科星上的新巴贝奇星际空港",
  "NT-999-XV on Cellin": "赛琳上的 NT-999-XV",
  "NT-999-XVI on Daymar": "戴玛尔上的 NT-999-XVI",
  "NT-999-XXII on Yela": "耶拉上的NT-999-XXII",
  "Nakamura Valley Aid Shelter": "中村谷援助避难所",
  "Nakamura Valley Aid Shelter on Yela": "耶拉上的中谷村援助避难所",
  "Narena's Rest": "纳蕾娜驿站",
  "Narena's Rest on Pyro III": "派罗III上的纳蕾娜驿站",
  "Nevermind": "无谓镇",
  "Nevermind on Magda": "玛格达上的无谓镇",
  "New Babbage": "新巴贝奇",
  "New Babbage on microTech": "微科星上的新巴贝奇",
  "Nuiqsut Emergency Shelter": "努伊克苏特紧急避难所",
  "Nuiqsut Emergency Shelter on microTech": "微科星上的努伊克苏特紧急避难所",
  "Nyx": "尼克斯",
  "Olisar": "奥丽莎",
  "Onyx Facility S1A1": "玛瑙 设施 S1A1",
  "Onyx Facility S1A1 on Arial": "艾瑞尔上的玛瑙 设施 S1A1",
  "Onyx Facility S1A10": "玛瑙 设施 S1A10",
  "Onyx Facility S1A10 on Arial": "艾瑞尔上的玛瑙 设施 S1A10",
  "Onyx Facility S1A2": "玛瑙 设施 S1A2",
  "Onyx Facility S1A2 on Arial": "艾瑞尔上的玛瑙 设施 S1A2",
  "Onyx Facility S1A3": "玛瑙 设施 S1A3",
  "Onyx Facility S1A3 on Arial": "艾瑞尔上的玛瑙 设施 S1A3",
  "Onyx Facility S1A4": "玛瑙 设施 S1A4",
  "Onyx Facility S1A4 on Arial": "艾瑞尔上的玛瑙 设施 S1A4",
  "Onyx Facility S1A5": "玛瑙 设施 S1A5",
  "Onyx Facility S1A5 on Arial": "艾瑞尔上的玛瑙 设施 S1A5",
  "Onyx Facility S1A6": "玛瑙 设施 S1A6",
  "Onyx Facility S1A6  on Arial": "艾瑞尔上的玛瑙 设施 S1A6",
  "Onyx Facility S1A7": "玛瑙 设施 S1A7",
  "Onyx Facility S1A7 on Arial": "艾瑞尔上的玛瑙 设施 S1A7",
  "Onyx Facility S1A8": "玛瑙 设施 S1A8",
  "Onyx Facility S1A8 on Arial": "艾瑞尔上的玛瑙 设施 S1A8",
  "Onyx Facility S1A9": "玛瑙 设施 S1A9",
  "Onyx Facility S1A9 on Arial": "艾瑞尔上的玛瑙 设施 S1A9",
  "Onyx Facility S1B1": "玛瑙 设施 S1B1",
  "Onyx Facility S1B1 on Aberdeen": "阿伯丁上的玛瑙 设施 S1B1",
  "Onyx Facility S1B10": "玛瑙 设施 S1B10",
  "Onyx Facility S1B10 on Aberdeen": "阿伯丁上的玛瑙 设施 S1B10",
  "Onyx Facility S1B2": "玛瑙 设施 S1B2",
  "Onyx Facility S1B2 on Aberdeen": "阿伯丁上的玛瑙 设施 S1B2",
  "Onyx Facility S1B3": "玛瑙 设施 S1B3",
  "Onyx Facility S1B3 on Aberdeen": "阿伯丁上的玛瑙 设施 S1B3",
  "Onyx Facility S1B4": "玛瑙 设施 S1B4",
  "Onyx Facility S1B4 on Aberdeen": "阿伯丁上的玛瑙 设施 S1B4",
  "Onyx Facility S1B5": "玛瑙 设施 S1B5",
  "Onyx Facility S1B5 on Aberdeen": "阿伯丁上的玛瑙 设施 S1B5",
  "Onyx Facility S1B6": "玛瑙 设施 S1B6",
  "Onyx Facility S1B6 on Aberdeen": "阿伯丁上的玛瑙 设施 S1B6",
  "Onyx Facility S1B7": "玛瑙 设施 S1B7",
  "Onyx Facility S1B7 on Aberdeen": "阿伯丁上的玛瑙 设施 S1B7",
  "Onyx Facility S1B8": "玛瑙 设施 S1B8",
  "Onyx Facility S1B8 on Aberdeen": "阿伯丁上的玛瑙 设施 S1B8",
  "Onyx Facility S1B9": "玛瑙 设施 S1B9",
  "Onyx Facility S1B9 on Aberdeen": "阿伯丁上的玛瑙 设施 S1B9",
  "Onyx Facility S1C1": "玛瑙 设施 S1C1",
  "Onyx Facility S1C1 on Magda": "玛格达上的玛瑙 设施 S1C1",
  "Onyx Facility S1C10": "玛瑙 设施 S1C10",
  "Onyx Facility S1C10 on Magda": "玛格达上的玛瑙 设施 S1C10",
  "Onyx Facility S1C2": "玛瑙 设施 S1C2",
  "Onyx Facility S1C2 on Magda": "玛格达上的玛瑙 设施 S1C2",
  "Onyx Facility S1C3": "玛瑙 设施 S1C3",
  "Onyx Facility S1C3 on Magda": "玛格达上的玛瑙 设施 S1C3",
  "Onyx Facility S1C4": "玛瑙 设施 S1C4",
  "Onyx Facility S1C4 on Magda": "玛格达上的玛瑙 设施 S1C4",
  "Onyx Facility S1C5": "玛瑙 设施 S1C5",
  "Onyx Facility S1C5 on Magda": "玛格达上的玛瑙 设施 S1C5",
  "Onyx Facility S1C6": "玛瑙 设施 S1C6",
  "Onyx Facility S1C6 on Magda": "玛格达上的玛瑙 设施 S1C6",
  "Onyx Facility S1C7": "玛瑙 设施 S1C7",
  "Onyx Facility S1C7 on Magda": "玛格达上的玛瑙 设施 S1C7",
  "Onyx Facility S1C8": "玛瑙 设施 S1C8",
  "Onyx Facility S1C8 on Magda": "玛格达上的玛瑙 设施 S1C8",
  "Onyx Facility S1C9": "玛瑙 设施 S1C9",
  "Onyx Facility S1C9 on Magda": "玛格达上的玛瑙 设施 S1C9",
  "Onyx Facility S1D1": "玛瑙 设施 S1D1",
  "Onyx Facility S1D1 on Ita": "依塔上的玛瑙 设施 S1D1",
  "Onyx Facility S1D10": "玛瑙 设施 S1D10",
  "Onyx Facility S1D10 on Ita": "依塔上的玛瑙 设施 S1D10",
  "Onyx Facility S1D2": "玛瑙 设施 S1D2",
  "Onyx Facility S1D2 on Ita": "依塔上的玛瑙 设施 S1D2",
  "Onyx Facility S1D3": "玛瑙 设施 S1D3",
  "Onyx Facility S1D3 on Ita": "依塔上的玛瑙 设施 S1D3",
  "Onyx Facility S1D4": "玛瑙 设施 S1D4",
  "Onyx Facility S1D4 on Ita": "依塔上的玛瑙 设施 S1D4",
  "Onyx Facility S1D5": "玛瑙 设施 S1D5",
  "Onyx Facility S1D5 on Ita": "依塔上的玛瑙 设施 S1D5",
  "Onyx Facility S1D6": "玛瑙 设施 S1D6",
  "Onyx Facility S1D6 on Ita": "依塔上的玛瑙 设施 S1D6",
  "Onyx Facility S1D7": "玛瑙 设施 S1D7",
  "Onyx Facility S1D7 on Ita": "依塔上的玛瑙 设施 S1D7",
  "Onyx Facility S1D8": "玛瑙 设施 S1D8",
  "Onyx Facility S1D8 on Ita": "依塔上的玛瑙 设施 S1D8",
  "Onyx Facility S1D9": "玛瑙 设施 S1D9",
  "Onyx Facility S1D9 on Ita": "依塔上的玛瑙 设施 S1D9",
  "Onyx Facility S2A1": "玛瑙 设施 S2A1",
  "Onyx Facility S2A1 on Cellin": "赛琳上的玛瑙 设施 S2A1",
  "Onyx Facility S2A10": "玛瑙 设施 S2A10",
  "Onyx Facility S2A10 on Cellin": "赛琳上的玛瑙 设施 S2A10",
  "Onyx Facility S2A2": "玛瑙 设施 S2A2",
  "Onyx Facility S2A2 on Cellin": "赛琳上的玛瑙 设施 S2A2",
  "Onyx Facility S2A3": "玛瑙 设施 S2A3",
  "Onyx Facility S2A3 on Cellin": "赛琳上的玛瑙 设施 S2A3",
  "Onyx Facility S2A4": "玛瑙 设施 S2A4",
  "Onyx Facility S2A4 on Cellin": "赛琳上的玛瑙 设施 S2A4",
  "Onyx Facility S2A5": "玛瑙 设施 S2A5",
  "Onyx Facility S2A5 on Cellin": "赛琳上的玛瑙 设施 S2A5",
  "Onyx Facility S2A6": "玛瑙 设施 S2A6",
  "Onyx Facility S2A6 on Cellin": "赛琳上的玛瑙 设施 S2A6",
  "Onyx Facility S2A7": "玛瑙 设施 S2A7",
  "Onyx Facility S2A7 on Cellin": "赛琳上的玛瑙 设施 S2A7",
  "Onyx Facility S2A8": "玛瑙 设施 S2A8",
  "Onyx Facility S2A8 on Cellin": "赛琳上的玛瑙 设施 S2A8",
  "Onyx Facility S2A9": "玛瑙 设施 S2A9",
  "Onyx Facility S2A9 on Cellin": "赛琳上的玛瑙 设施 S2A9",
  "Onyx Facility S2B1": "玛瑙 设施 S2B1",
  "Onyx Facility S2B1 on Daymar": "戴玛尔上的玛瑙 设施 S2B1",
  "Onyx Facility S2B10": "玛瑙 设施 S2B10",
  "Onyx Facility S2B10 on Daymar": "戴玛尔上的玛瑙 设施 S2B10",
  "Onyx Facility S2B2": "玛瑙 设施 S2B2",
  "Onyx Facility S2B2 on Daymar": "戴玛尔上的玛瑙 设施 S2B2",
  "Onyx Facility S2B3": "玛瑙 设施 S2B3",
  "Onyx Facility S2B3 on Daymar": "戴玛尔上的玛瑙 设施 S2B3",
  "Onyx Facility S2B4": "玛瑙 设施 S2B4",
  "Onyx Facility S2B4 on Daymar": "戴玛尔上的玛瑙 设施 S2B4",
  "Onyx Facility S2B5": "玛瑙 设施 S2B5",
  "Onyx Facility S2B5 on Daymar": "戴玛尔上的玛瑙 设施 S2B5",
  "Onyx Facility S2B6": "玛瑙 设施 S2B6",
  "Onyx Facility S2B6 on Daymar": "戴玛尔上的玛瑙 设施 S2B6",
  "Onyx Facility S2B7": "玛瑙 设施 S2B7",
  "Onyx Facility S2B7 on Daymar": "戴玛尔上的玛瑙 设施 S2B7",
  "Onyx Facility S2B8": "玛瑙 设施 S2B8",
  "Onyx Facility S2B8 on Daymar": "戴玛尔上的玛瑙 设施 S2B8",
  "Onyx Facility S2B9": "玛瑙 设施 S2B9",
  "Onyx Facility S2B9 on Daymar": "戴玛尔上的玛瑙 设施 S2B9",
  "Onyx Facility S2C1": "玛瑙 设施 S2C1",
  "Onyx Facility S2C1 on Yela": "耶拉上的玛瑙 设施 S2C1",
  "Onyx Facility S2C10": "玛瑙 设施 S2C10",
  "Onyx Facility S2C10 on Yela": "耶拉上的玛瑙 设施 S2C10",
  "Onyx Facility S2C2": "玛瑙 设施 S2C2",
  "Onyx Facility S2C2 on Yela": "耶拉上的玛瑙 设施 S2C2",
  "Onyx Facility S2C3": "玛瑙 设施 S2C3",
  "Onyx Facility S2C3 on Yela": "耶拉上的玛瑙 设施 S2C3",
  "Onyx Facility S2C4": "玛瑙 设施 S2C4",
  "Onyx Facility S2C4 on Yela": "耶拉上的玛瑙 设施 S2C4",
  "Onyx Facility S2C5": "玛瑙 设施 S2C5",
  "Onyx Facility S2C5 on Yela": "耶拉上的玛瑙 设施 S2C5",
  "Onyx Facility S2C6": "玛瑙 设施 S2C6",
  "Onyx Facility S2C6 on Yela": "耶拉上的玛瑙 设施 S2C6",
  "Onyx Facility S2C7": "玛瑙 设施 S2C7",
  "Onyx Facility S2C7 on Yela": "耶拉上的玛瑙 设施 S2C7",
  "Onyx Facility S2C8": "玛瑙 设施 S2C8",
  "Onyx Facility S2C8 on Yela": "耶拉上的玛瑙 设施 S2C8",
  "Onyx Facility S2C9": "玛瑙 设施 S2C9",
  "Onyx Facility S2C9 on Yela": "耶拉上的玛瑙 设施 S2C9",
  "Onyx Facility S3A1": "玛瑙 设施 S3A1",
  "Onyx Facility S3A1 on Lyria": "莉瑞雅上的玛瑙 设施 S3A1",
  "Onyx Facility S3A10": "玛瑙 设施 S3A10",
  "Onyx Facility S3A10 on Lyria": "莉瑞雅上的玛瑙 设施 S3A10",
  "Onyx Facility S3A2": "玛瑙 设施 S3A2",
  "Onyx Facility S3A2 on Lyria": "莉瑞雅上的玛瑙 设施 S3A2",
  "Onyx Facility S3A3": "玛瑙 设施 S3A3",
  "Onyx Facility S3A3 on Lyria": "莉瑞雅上的玛瑙 设施 S3A3",
  "Onyx Facility S3A4": "玛瑙 设施 S3A4",
  "Onyx Facility S3A4 on Lyria": "莉瑞雅上的玛瑙 设施 S3A4",
  "Onyx Facility S3A5": "玛瑙 设施 S3A5",
  "Onyx Facility S3A5 on Lyria": "莉瑞雅上的玛瑙 设施 S3A5",
  "Onyx Facility S3A6": "玛瑙 设施 S3A6",
  "Onyx Facility S3A6 on Lyria": "莉瑞雅上的玛瑙 设施 S3A6",
  "Onyx Facility S3A7": "玛瑙 设施 S3A7",
  "Onyx Facility S3A7 on Lyria": "莉瑞雅上的玛瑙 设施 S3A7",
  "Onyx Facility S3A8": "玛瑙 设施 S3A8",
  "Onyx Facility S3A8 on Lyria": "莉瑞雅上的玛瑙 设施 S3A8",
  "Onyx Facility S3A9": "玛瑙 设施 S3A9",
  "Onyx Facility S3A9 on Lyria": "莉瑞雅上的玛瑙 设施 S3A9",
  "Onyx Facility S3B1": "玛瑙 设施 S3B1",
  "Onyx Facility S3B1 on Wala": "瓦菈上的玛瑙 设施 S3B1",
  "Onyx Facility S3B10": "玛瑙 设施 S3B10",
  "Onyx Facility S3B10 on Wala": "瓦菈上的玛瑙 设施 S3B10",
  "Onyx Facility S3B2": "玛瑙 设施 S3B2",
  "Onyx Facility S3B2 on Wala": "瓦菈上的玛瑙 设施 S3B2",
  "Onyx Facility S3B3": "玛瑙 设施 S3B3",
  "Onyx Facility S3B3 on Wala": "瓦菈上的玛瑙 设施 S3B3",
  "Onyx Facility S3B4": "玛瑙 设施 S3B4",
  "Onyx Facility S3B4 on Wala": "瓦菈上的玛瑙 设施 S3B4",
  "Onyx Facility S3B5": "玛瑙 设施 S3B5",
  "Onyx Facility S3B5 on Wala": "瓦菈上的玛瑙 设施 S3B5",
  "Onyx Facility S3B6": "玛瑙 设施 S3B6",
  "Onyx Facility S3B6 on Wala": "瓦菈上的玛瑙 设施 S3B6",
  "Onyx Facility S3B7": "玛瑙 设施 S3B7",
  "Onyx Facility S3B7 on Wala": "瓦菈上的玛瑙 设施 S3B7",
  "Onyx Facility S3B8": "玛瑙 设施 S3B8",
  "Onyx Facility S3B8 on Wala": "瓦菈上的玛瑙 设施 S3B8",
  "Onyx Facility S3B9": "玛瑙 设施 S3B9",
  "Onyx Facility S3B9 on Wala": "瓦菈上的玛瑙 设施 S3B9",
  "Onyx Facility S4A1": "玛瑙 设施 S4A1",
  "Onyx Facility S4A1 on Calliope": "卡利俄佩上的玛瑙 设施 S4A1",
  "Onyx Facility S4A10": "玛瑙 设施 S4A10",
  "Onyx Facility S4A10 on Calliope": "卡利俄佩上的玛瑙 设施 S4A10",
  "Onyx Facility S4A2": "玛瑙 设施 S4A2",
  "Onyx Facility S4A2 on Calliope": "卡利俄佩上的玛瑙 设施 S4A2",
  "Onyx Facility S4A3": "玛瑙 设施 S4A3",
  "Onyx Facility S4A3 on Calliope": "卡利俄佩上的玛瑙 设施 S4A3",
  "Onyx Facility S4A4": "玛瑙 设施 S4A4",
  "Onyx Facility S4A4 on Calliope": "卡利俄佩上的玛瑙 设施 S4A4",
  "Onyx Facility S4A5": "玛瑙 设施 S4A5",
  "Onyx Facility S4A5 on Calliope": "卡利俄佩上的玛瑙 设施 S4A5",
  "Onyx Facility S4A6": "玛瑙 设施 S4A6",
  "Onyx Facility S4A6 on Calliope": "卡利俄佩上的玛瑙 设施 S4A6",
  "Onyx Facility S4A7": "玛瑙 设施 S4A7",
  "Onyx Facility S4A7 on Calliope": "卡利俄佩上的玛瑙 设施 S4A7",
  "Onyx Facility S4A8": "玛瑙 设施 S4A8",
  "Onyx Facility S4A8 on Calliope": "卡利俄佩上的玛瑙 设施 S4A8",
  "Onyx Facility S4A9": "玛瑙 设施 S4A9",
  "Onyx Facility S4A9 on Calliope": "卡利俄佩上的玛瑙 设施 S4A9",
  "Onyx Facility S4B1": "玛瑙 设施 S4B1",
  "Onyx Facility S4B1 on Clio": "克利俄上的玛瑙 设施 S4B1",
  "Onyx Facility S4B10": "玛瑙 设施 S4B10",
  "Onyx Facility S4B10 on Clio": "克利俄上的玛瑙 设施 S4B10",
  "Onyx Facility S4B2": "玛瑙 设施 S4B2",
  "Onyx Facility S4B2 on Clio": "克利俄上的玛瑙 设施 S4B2",
  "Onyx Facility S4B3": "玛瑙 设施 S4B3",
  "Onyx Facility S4B3 on Clio": "克利俄上的玛瑙 设施 S4B3",
  "Onyx Facility S4B4": "玛瑙 设施 S4B4",
  "Onyx Facility S4B4 on Clio": "克利俄上的玛瑙 设施 S4B4",
  "Onyx Facility S4B5": "玛瑙 设施 S4B5",
  "Onyx Facility S4B5 on Clio": "克利俄上的玛瑙 设施 S4B5",
  "Onyx Facility S4B6": "玛瑙 设施 S4B6",
  "Onyx Facility S4B6 on Clio": "克利俄上的玛瑙 设施 S4B6",
  "Onyx Facility S4B7": "玛瑙 设施 S4B7",
  "Onyx Facility S4B7 on Clio": "克利俄上的玛瑙 设施 S4B7",
  "Onyx Facility S4B8": "玛瑙 设施 S4B8",
  "Onyx Facility S4B8 on Clio": "克利俄上的玛瑙 设施 S4B8",
  "Onyx Facility S4B9": "玛瑙 设施 S4B9",
  "Onyx Facility S4B9 on Clio": "克利俄上的玛瑙 设施 S4B9",
  "Onyx Facility S4C1": "玛瑙 设施 S4C1",
  "Onyx Facility S4C1 on Euterpe": "欧忒耳佩上的玛瑙 设施 S4C1",
  "Onyx Facility S4C10": "玛瑙 设施 S4C10",
  "Onyx Facility S4C10 on Euterpe": "欧忒耳佩上的玛瑙 设施 S4C10",
  "Onyx Facility S4C2": "玛瑙 设施 S4C2",
  "Onyx Facility S4C2 on Euterpe": "欧忒耳佩上的玛瑙 设施 S4C2",
  "Onyx Facility S4C3": "玛瑙 设施 S4C3",
  "Onyx Facility S4C3 on Euterpe": "欧忒耳佩上的玛瑙 设施 S4C3",
  "Onyx Facility S4C4": "玛瑙 设施 S4C4",
  "Onyx Facility S4C4 on Euterpe": "欧忒耳佩上的玛瑙 设施 S4C4",
  "Onyx Facility S4C5": "玛瑙 设施 S4C5",
  "Onyx Facility S4C5 on Euterpe": "欧忒耳佩上的玛瑙 设施 S4C5",
  "Onyx Facility S4C6": "玛瑙 设施 S4C6",
  "Onyx Facility S4C6 on Euterpe": "欧忒耳佩上的玛瑙 设施 S4C6",
  "Onyx Facility S4C7": "玛瑙 设施 S4C7",
  "Onyx Facility S4C7 on Euterpe": "欧忒耳佩上的玛瑙 设施 S4C7",
  "Onyx Facility S4C8": "玛瑙 设施 S4C8",
  "Onyx Facility S4C8 on Euterpe": "欧忒耳佩上的玛瑙 设施 S4C8",
  "Onyx Facility S4C9": "玛瑙 设施 S4C9",
  "Onyx Facility S4C9 on Euterpe": "欧忒耳佩上的玛瑙 设施 S4C9",
  "Operations Depot Lyria-1": "运营仓库 莉瑞娅-1",
  "Operations Depot Lyria-5": "运营仓库 莉瑞娅-5",
  "Operations Depot on Lyria": "莉瑞雅上的运营仓库",
  "Operations Office": "运营办公室",
  "Orbituary": "轨道讣闻站",
  "Orbituary Clinic": "轨道讣闻站诊所",
  "Orbituary Entrance": "轨道讣闻站入口",
  "Orbituary Habs": "轨道讣闻站居住区",
  "Orbituary Refinery": "轨道讣闻站精炼站",
  "Orbituary above Pyro III": "派罗III上空的轨道讣闻站",
  "Orison": "奥里森",
  "Orison in Crusader": "十字军上的奥里森",
  "Ostler's Claim": "奥斯特勒领地",
  "Ostler's Claim on Pyro II": "派罗II上的奥斯特勒领地",
  "Outpost 54": "前哨站 54",
  "Outpost 54 on microTech": "微科星上的54号前哨站",
  "PYAM-FARSTAT-1-2": "焰联-远程站-1-2",
  "PYAM-FARSTAT-1-2 Clinic": "焰联-远程站-1-2诊所",
  "PYAM-FARSTAT-1-2 Entrance": "焰联-远程站-1-2 入口",
  "PYAM-FARSTAT-1-2 Habs": "焰联-远程站-1-2居住区",
  "PYAM-FARSTAT-1-2 at the L2 Lagrange of Pyro I": "位于派罗I的L2拉格朗日点的焰联-远程站-1-2",
  "PYAM-FARSTAT-1-3": "焰联-远程站-1-3",
  "PYAM-FARSTAT-1-3 Clinic": "焰联-远程站-1-3诊所",
  "PYAM-FARSTAT-1-3 Entrance": "焰联-远程站-1-3 入口",
  "PYAM-FARSTAT-1-3 Habs": "焰联-远程站-1-3居住区",
  "PYAM-FARSTAT-1-3 at the L3 Lagrange of Pyro I": "位于派罗I的L3拉格朗日点的焰联-远程站-1-3",
  "PYAM-FARSTAT-1-5": "焰联-远程站-1-5",
  "PYAM-FARSTAT-1-5 Clinic": "焰联-远程站-1-5诊所",
  "PYAM-FARSTAT-1-5 Entrance": "焰联-远程站-1-5 入口",
  "PYAM-FARSTAT-1-5 Habs": "焰联-远程站-1-5居住区",
  "PYAM-FARSTAT-1-5 at the L5 Lagrange of Pyro I": "位于派罗I的L5拉格朗日点的焰联-远程站-1-5",
  "PYAM-FARSTAT-2-0": "焰联-远程站-2-0",
  "PYAM-FARSTAT-2-0 Clinic": "焰联-远程站-2-0诊所",
  "PYAM-FARSTAT-2-0 Entrance": "焰联-远程站-2-0 入口",
  "PYAM-FARSTAT-2-0 Habs": "焰联-远程站-2-0居住区",
  "PYAM-FARSTAT-2-0 above Pyro II": "位于派罗II上空的焰联-远程站-2-0",
  "PYAM-FARSTAT-2-3": "焰联-远程站-2-3",
  "PYAM-FARSTAT-2-3 Clinic": "焰联-远程站-2-3诊所",
  "PYAM-FARSTAT-2-3 Entrance": "焰联-远程站-2-3 入口",
  "PYAM-FARSTAT-2-3 Habs": "焰联-远程站-2-3居住区",
  "PYAM-FARSTAT-2-3 at the L3 Lagrange of Pyro II": "位于派罗II的L3拉格朗日点的焰联-远程站-2-3",
  "PYAM-FARSTAT-3-5": "焰联-远程站-3-5",
  "PYAM-FARSTAT-3-5 Clinic": "焰联-远程站-3-5诊所",
  "PYAM-FARSTAT-3-5 Entrance": "焰联-远程站-3-5入口",
  "PYAM-FARSTAT-3-5 Habs": "焰联-远程站-3-5居住区",
  "PYAM-FARSTAT-3-5 at the L5 Lagrange of Pyro III": "位于派罗III的L5拉格朗日点的焰联-远程站-3-5",
  "PYAM-FARSTAT-5-1": "焰联-远程站-5-1",
  "PYAM-FARSTAT-5-1 Clinic": "焰联-远程站-5-1诊所",
  "PYAM-FARSTAT-5-1 Entrance": "焰联-远程站-5-1入口",
  "PYAM-FARSTAT-5-1 Habs": "焰联-远程站-5-1居住区",
  "PYAM-FARSTAT-5-1 at the L1 Lagrange of Pyro V": "位于派罗V的L1拉格朗日点的焰联-远程站-5-1",
  "PYAM-FARSTAT-5-3": "焰联-远程站-5-3",
  "PYAM-FARSTAT-5-3  Clinic": "焰联-远程站-5-3诊所",
  "PYAM-FARSTAT-5-3  Entrance": "焰联-远程站-5-3入口",
  "PYAM-FARSTAT-5-3  Habs": "焰联-远程站-5-3居住区",
  "PYAM-FARSTAT-5-3 at the L3 Lagrange of Pyro V": "位于派罗V的L3拉格朗日点的焰联-远程站-5-3",
  "PYAM-FARSTAT-6-2": "焰联-远程站-6-2",
  "PYAM-FARSTAT-6-2 Clinic": "焰联-远程站-6-2诊所",
  "PYAM-FARSTAT-6-2 Entrance": "焰联-远程站-6-2入口",
  "PYAM-FARSTAT-6-2 Habs": "焰联-远程站-6-2居住区",
  "PYAM-FARSTAT-6-2 at the L2 Lagrange of Pyro VI": "位于派罗VI的L2拉格朗日点的焰联-远程站-6-2",
  "Paradise Cove": "天堂湾",
  "Paradise Cove on Wala": "瓦菈上的天堂湾",
  "Patch City": "补丁城",
  "Patch City Clinic": "补丁城诊所",
  "Patch City Entrance": "补丁城入口",
  "Patch City Habs": "补丁城居住区",
  "Patch City at the L3 Lagrange of Pyro III": "派罗III的L3拉格朗日点的补丁城",
  "People's Service Station Alpha": "人民服务空间站 阿尔法",
  "People's Service Station Alpha in the Keeger Belt": "位于基格小行星带的人民服务空间站阿尔法",
  "People's Service Station Delta": "人民服务空间站 德尔塔",
  "People's Service Station Delta in the Keeger Belt": "位于基格小行星带的人民服务空间站德尔塔",
  "People's Service Station Lambda": "人民服务空间站 拉姆达",
  "People's Service Station Lambda in the Keeger Belt": "位于基格小行星带的人民服务空间站拉姆达",
  "People's Service Station Omicron": "人民服务空间站 奥密克容",
  "People's Service Station Omicron in the Keeger Belt": "位于基格小行星带的人民服务空间站奥密克容",
  "People's Service Station Theta": "人民服务空间站 西塔",
  "People's Service Station Theta in the Keeger Belt": "位于基格小行星带的人民服务空间站西塔",
  "Picker's Field": "拾荒地",
  "Picker's Field on Hurston": "赫斯顿上的拾荒地",
  "Point Wain Emergency Shelter": "维恩地区紧急避难所",
  "Point Wain Emergency Shelter on microTech": "微科星上的维恩地区紧急避难所",
  "Port Olisar": "奥丽莎空间站",
  "Port Tressler": "特雷斯勒空间站",
  "Port Tressler above microTech": "微科星上空的特雷斯勒空间站",
  "Prophet's Peak": "神使峰",
  "Prophet's Peak on Pyro 5c": "派罗5c上的神使峰",
  "Prospect Depot": "展望仓库",
  "Prospect Depot on Pyro III": "派罗 III上的展望仓库",
  "Pyro": "派罗",
  "Pyro 5a Abandoned Outpost": "派罗 5a 废弃前哨站",
  "Pyro 5b Abandoned Outpost": "派罗 5b 废弃前哨站",
  "Pyro 5c Abandoned Outpost": "派罗 5c 废弃前哨站",
  "Pyro 5d Abandoned Outpost": "派罗 5d 废弃前哨站",
  "Pyro 5e Abandoned Outpost": "派罗 5e 废弃前哨站",
  "Pyro 5f Abandoned Outpost": "派罗 5f 废弃前哨站",
  "Pyro I": "派罗 I",
  "Pyro I Abandoned Outpost": "派罗 I 废弃前哨站",
  "Pyro I Cave": "派罗 I 洞穴",
  "Pyro II Abandoned Outpost": "派罗 II 废弃前哨站",
  "Pyro II Cave": "派罗 II 洞穴",
  "Pyro III Abandoned Outpost": "派罗 III 废弃前哨站",
  "Pyro III Cave": "派罗 III 洞穴",
  "Pyro IV": "派罗 IV",
  "Pyro IV Abandoned Outpost": "派罗 IV 废弃前哨站",
  "Pyro IV Cave": "派罗 IV 洞穴",
  "Pyro V": "派罗 V",
  "Pyro V Abandoned Outpost": "派罗 V 废弃前哨站",
  "Pyro V Cave": "派罗 V 洞穴",
  "Pyro VI Abandoned Outpost": "派罗 VI 废弃前哨站",
  "Pyro VI Cave": "派罗 VI 洞穴",
  "QV Breaker Station": "QV碎岩站",
  "QV Breaker Station BRK-127": "QV碎岩站 BRK-127",
  "QV Breaker Station BRK-127 in the Glaciem Ring": "位于冰川环带的QV碎岩站BRK-127",
  "QV Breaker Station BRK-184": "QV碎岩站 BRK-184",
  "QV Breaker Station BRK-184 in the Glaciem Ring": "位于冰川环带的QV碎岩站BRK-184",
  "QV Breaker Station BRK-204": "QV碎岩站 BRK-204",
  "QV Breaker Station BRK-204 in the Glaciem Ring": "位于冰川环带的QV碎岩站BRK-204",
  "QV Breaker Station BRK-235": "QV碎岩站 BRK-235",
  "QV Breaker Station BRK-235 in the Glaciem Ring": "位于冰川环带的QV碎岩站BRK-235",
  "QV Breaker Station BRK-267": "QV碎岩站 BRK-267",
  "QV Breaker Station BRK-267 in the Glaciem Ring": "位于冰川环带的QV碎岩站BRK-267",
  "QV Breaker Station BRK-284": "QV碎岩站 BRK-284",
  "QV Breaker Station BRK-284 in the Glaciem Ring": "位于冰川环带的QV碎岩站BRK-284",
  "QV Breaker Station BRK-304": "QV碎岩站 BRK-304",
  "QV Breaker Station BRK-304 in the Glaciem Ring": "位于冰川环带的QV碎岩站BRK-304",
  "QV Breaker Station BRK-320": "QV碎岩站 BRK-320",
  "QV Breaker Station BRK-320 in the Glaciem Ring": "位于冰川环带的QV碎岩站BRK-320",
  "QV Breaker Station BRK-425": "QV碎岩站 BRK-425",
  "QV Breaker Station BRK-425 in the Glaciem Ring": "位于冰川环带的QV碎岩站BRK-425",
  "QV Breaker Station BRK-437": "QV碎岩站 BRK-437",
  "QV Breaker Station BRK-437 in the Glaciem Ring": "位于冰川环带的QV碎岩站BRK-437",
  "QV Breaker Station BRK-521": "QV碎岩站 BRK-521",
  "QV Breaker Station BRK-521 in the Glaciem Ring": "位于冰川环带的QV碎岩站BRK-521",
  "QV Breaker Station BRK-542": "QV碎岩站 BRK-542",
  "QV Breaker Station BRK-542 in the Glaciem Ring": "位于冰川环带的QV碎岩站BRK-542",
  "QV Breaker Station BRK-546": "QV碎岩站 BRK-546",
  "QV Breaker Station BRK-546 in the Glaciem Ring": "位于冰川环带的QV碎岩站BRK-546",
  "QV Breaker Station BRK-563": "QV碎岩站 BRK-563",
  "QV Breaker Station BRK-563 in the Glaciem Ring": "位于冰川环带的QV碎岩站BRK-563",
  "QV Breaker Station BRK-608": "QV碎岩站 BRK-608",
  "QV Breaker Station BRK-608 in the Glaciem Ring": "位于冰川环带的QV碎岩站 BRK-608",
  "QV Breaker Station BRK-711": "QV碎岩站 BRK-711",
  "QV Breaker Station BRK-711 in the Glaciem Ring": "位于冰川环带的QV碎岩站BRK-711",
  "QV Breaker Station BRK-782": "QV碎岩站 BRK-782",
  "QV Breaker Station BRK-782 in the Glaciem Ring": "位于冰川环带的QV碎岩站BRK-782",
  "QV Breaker Station BRK-879": "QV碎岩站 BRK-879",
  "QV Breaker Station BRK-879 in the Glaciem Ring": "位于冰川环带的QV碎岩站BRK-879",
  "QV Breaker Station BRK-970": "QV碎岩站 BRK-970",
  "QV Breaker Station BRK-970 in the Glaciem Ring": "位于冰川环带的QV碎岩站BRK-970",
  "QV Breaker Station BRK-985": "QV碎岩站 BRK-985",
  "QV Breaker Station BRK-985 in the Glaciem Ring": "位于冰川环带的QV碎岩站BRK-985",
  "Rappel": "索降镇",
  "Rappel on Hurston": "赫斯顿上的索降镇",
  "Rat's Nest": "鼠巢空间站",
  "Rat's Nest Clinic": "鼠巢空间站诊所",
  "Rat's Nest Entrance": "鼠巢空间站入口",
  "Rat's Nest Habs": "鼠巢空间站居住区",
  "Rat's Nest at the L5 Lagrange of Pyro V": "位于派罗V的L5拉格朗日点的鼠巢空间站",
  "Raven's Roost": "渡鸦栖",
  "Raven's Roost on MicroTech": "微科星上的渡鸦栖",
  "Rayari": "拉亚利",
  "Rayari Anvik Research Outpost": "拉亚利-安维克研究站",
  "Rayari Anvik Research Outpost on Calliope": "卡利俄佩上的拉亚利-安维克研究站",
  "Rayari Cantwell Research Outpost": "拉亚利-坎特韦尔研究站",
  "Rayari Cantwell Research Outpost on Clio": "克利俄上的拉亚利-坎特韦尔研究站",
  "Rayari Deltana Research Outpost": "拉亚利 德尔塔纳科究前哨站",
  "Rayari Deltana Research Outpost on microTech": "微科星上的拉亚利-德尔塔纳研究站",
  "Rayari Kaltag Research Outpost": "拉亚利-卡尔塔格研究站",
  "Rayari Kaltag Research Outpost on Calliope": "卡利俄佩上的拉亚利-卡尔塔格研究站",
  "Rayari Livengood Research Outpost": "拉亚利 莱文古德科究前哨站",
  "Rayari Livengood Research Outpost on microtech": "微科星上的拉亚利-利文古德研究站",
  "Rayari McGrath Research Outpost": "拉亚利-麦格拉思研究站",
  "Rayari McGrath Research Outpost on Clio": "克利俄上的拉亚利-麦格拉思研究站",
  "Razor's Edge": "剃刀悬崖",
  "Razor's Edge on microTech": "微科星上的剃刀悬崖",
  "Reclamation & Disposal": "“回收和处理”",
  "Reclamation & Disposal Orinth": "奥林森回收站",
  "Reclamation & Disposal Orinth on Hurston": "赫斯顿上的奥林森回收站",
  "Reclamation and Disposal in Lorville": "罗威尔回收处理站",
  "Red Crossroads Station at microTech's L4 Lagrange point": "位于微科星的L4拉格朗日点的红色十字路口站",
  "Refueling Station": "加油站",
  "Regiment Downs": "军团陵",
  "Regiment Downs on Calliope": "卡利俄佩上的军团陵",
  "Rico's Remains": "里科遗迹",
  "Rico's Remains on Hurston": "赫斯顿上的里科遗迹",
  "Riker Memorial Spaceport": "瑞克纪念空港",
  "Riker Memorial Spaceport in Area18": "18区上的瑞克纪念空港",
  "Rock Bottom": "石头滩",
  "Rock Bottom on Lyria": "莉瑞雅上的石头滩",
  "Rod's Fuel 'N Supplies": "路德补给站",
  "Rod's Fuel 'N Supplies Clinic": "路德补给站诊所",
  "Rod's Fuel 'N Supplies Entrance": "路德补给站入口",
  "Rod's Fuel 'N Supplies Habs": "路德补给站居住区",
  "Rod's Fuel 'N Supplies at the L4 Lagrange of Pyro V": "派罗V的L4拉格朗日点的路德补给站",
  "Rolo's Crater": "罗洛陨坑",
  "Rolo's Crater on Yela": "耶拉上的罗洛陨坑",
  "Rough Landing": "砺石地",
  "Rough Landing on Pyro VI": "派罗VI上的砺石地",
  "Ruin Station": "废墟空间站",
  "Ruin Station Clinic": "废墟空间站诊所",
  "Ruin Station Entrance": "废墟空间站入口",
  "Ruin Station Habs": "废墟空间站居住区",
  "Ruin Station Refinery": "废墟空间站精炼站",
  "Ruin Station above Pyro VI": "派罗 VI 上空的废墟空间站",
  "Ruptura OLP": "破碎 激光站",
  "Ruptura Orbital Laser Platform above Aberdeen": "阿伯丁上的破碎 轨道激光平台",
  "Ruptura PAF-I": "破碎 校准站-I",
  "Ruptura PAF-II": "破碎 校准站-II",
  "Ruptura PAF-III": "破碎 校准站-III",
  "Ruptura Platform Alignment Facility I on Aberdeen": "阿伯丁上的破碎 平台校准设施I",
  "Ruptura Platform Alignment Facility II on Aberdeen": "阿伯丁上的破碎 平台校准设施II",
  "Ruptura Platform Alignment Facility III on Aberdeen": "阿伯丁上的破碎 轨道激光平台III",
  "Rustville": "锈迹镇",
  "Rustville on Pyro I": "派罗I上的锈迹镇",
  "Ruto's Associate": "鲁托的助理",
  "Ruto's Associate in the Escape Tunnel": "鲁托在逃生地道中的同伙",
  "Ruto's Satellite": "鲁托的卫星",
  "Ruto's Satellite near Barton Flats on Aberdeen": "鲁托的卫星位于阿伯丁的巴顿公寓",
  "SNK-A on Solanki Platform near Orison": "位于奥里森附近索兰奇平台上的SNK-A",
  "SNK-B on Solanki Platform near Orison": "位于奥里森附近索兰奇平台上的SNK-B",
  "SNK-C on Solanki Platform near Orison": "位于奥里森附近索兰奇平台上的SNK-C",
  "SNK-D on Solanki Platform near Orison": "位于奥里森附近索兰奇平台上的SNK-D",
  "Sacren's Plot": "萨克伦领地",
  "Sacren's Plot on Pyro IV": "派罗IV上的萨克伦领地。",
  "Sakura Sun Goldenrod Workcenter": "樱日一枝黄花工作中心",
  "Sakura Sun Goldenrod Workcenter on microTech": "微科星上的樱日集团一枝黄花工作中心",
  "Sakura Sun Magnolia Workcenter": "樱日木兰花工作中心",
  "Sakura Sun Magnolia Workcenter on Hurston": "位于斯坦顿的樱日集团木兰花工作中心",
  "Samson & Son's Salvage Center": "参孙父子回收站",
  "Samson & Son's Salvage Center on Wala": "瓦菈上的参孙废品回收站",
  "Scraper's Turn": "财奴湾",
  "Scraper's Turn on Pyro VI": "派罗VI上的财奴湾",
  "Scuttle": "沉舟处",
  "Scuttle on Wala": "瓦菈上的沉舟处",
  "Sector 1": "1区",
  "Sector 2": "2区",
  "Security Post": "安保站",
  "Security Post Awala": "阿瓦拉安保站",
  "Security Post Awala on Cellin": "赛琳上的阿瓦拉安保站",
  "Security Post Birbari": "比尔巴利安保站",
  "Security Post Birbari on Cellin": "赛琳上的比尔巴利安保站",
  "Security Post Chilad": "奇拉得安保站",
  "Security Post Chilad on Cellin": "赛琳上的奇拉得安保站",
  "Security Post Criska": "克里斯卡安保站",
  "Security Post Criska on Cellin": "赛琳上的克里斯卡安保站",
  "Security Post Dawu": "达乌安保站",
  "Security Post Dawu on Daymar": "戴玛尔上的达乌安保站",
  "Security Post Dipur": "迪普尔安保站",
  "Security Post Dipur on Cellin": "赛琳上的迪普尔安保站",
  "Security Post Erden": "埃尔登安保站",
  "Security Post Erden on Daymar": "戴玛尔上的埃尔登安保站",
  "Security Post Gandan": "甘丹安保站",
  "Security Post Gandan on Cellin": "赛琳上的甘丹安保站",
  "Security Post Hasik": "哈西克安保站",
  "Security Post Hasik on Yela": "耶拉上的哈西克安保站",
  "Security Post Iteke": "伊特克安保站",
  "Security Post Iteke on Yela": "耶拉上的伊特克安保站",
  "Security Post Kareah": "加利亚安保站",
  "Security Post Kareah around Cellin": "赛琳附近的加利亚安保空间站",
  "Security Post Klipra": "克利普拉安保站",
  "Security Post Klipra on Yela": "耶拉上的克利普拉安保站",
  "Security Post Kota": "科塔安保站",
  "Security Post Kota on Cellin": "赛琳上的科塔安保站",
  "Security Post Lespin": "莱斯平安保站",
  "Security Post Lespin on Cellin": "赛琳上的莱斯平安保站",
  "Security Post Menian": "米尼恩安保站",
  "Security Post Menian on Daymar": "戴玛尔上的米尼恩安保站",
  "Security Post Moka": "莫卡安保站",
  "Security Post Moka on Yela": "耶拉上的莫卡安保站",
  "Security Post Moluto": "莫鲁托安保站",
  "Security Post Moluto on Daymar": "戴玛尔上的莫鲁托安保站",
  "Security Post Opal": "欧珀安保站",
  "Security Post Opal on Yela": "耶拉上的欧珀安保站",
  "Security Post Pakote": "帕科特安保站",
  "Security Post Pakote on Cellin": "赛琳上的帕科特安保站",
  "Security Post Peska": "佩斯卡安保站",
  "Security Post Peska on Yela": "耶拉上的佩斯卡安保站",
  "Security Post Prashad": "普拉沙德安保站",
  "Security Post Prashad on Daymar": "戴玛尔上的普拉沙德安保站",
  "Security Post Reawick": "里威克安保站",
  "Security Post Reawick on Daymar": "戴玛尔上的里威克安保站",
  "Security Post Saktigar": "萨基加尔安保站",
  "Security Post Saktigar on Cellin": "赛琳上的萨基加尔安保站",
  "Security Post Sharga": "沙尔嘎安保站",
  "Security Post Sharga on Cellin": "赛琳上的沙尔嘎安保站",
  "Security Post Tavan": "塔万安保站",
  "Security Post Tavan on Daymar": "戴玛尔上的塔万安保站",
  "Security Post Thaquray": "塔库赖安保站",
  "Security Post Thaquray on Daymar": "戴玛尔上的塔库赖安保站",
  "Security Post Triolet": "特里奥莱安保站",
  "Security Post Triolet on Yela": "耶拉上的特里奥莱安保站",
  "Security Post Ulaga": "乌拉加安保站",
  "Security Post Ulaga on Daymar": "戴玛尔上的乌拉加安保站",
  "Security Post Walvis": "沃尔维斯安保站",
  "Security Post Walvis on Yela": "耶拉上的沃尔维斯安保站",
  "Security Post Wan": "万安保站",
  "Security Post Wan on Yela": "耶拉上的万安保站",
  "Security Post Yafa": "雅法安保站",
  "Security Post Yafa on Daymar": "戴玛尔上的雅法安保站",
  "Seer's Canyon": "先觉者峡谷",
  "Seer's Canyon on Pyro 5b": "派罗5b上的先觉者峡谷",
  "Seraphim Station": "炽天使空间站",
  "Seraphim Station above Crusader": "十字军上空的炽天使空间站",
  "Service Entrance": "服务入口",
  "Shadowfall": "影落镇",
  "Shadowfall on Pyro III": "派罗III上的影落镇",
  "Shady Glen Farms": "荫谷农场",
  "Shady Glen Farms on Wala": "瓦菈上的荫谷农场",
  "Shallow Fields Station at Crusader's L4 Lagrange point": "位于十字军的L4拉格朗日点的轻浅田野站",
  "Shallow Frontier Station at microTech's L1 Lagrange point": "位于微科星的L1拉格朗日点的浅边站",
  "Shanks": "奇袭地",
  "Shanks on Euterpe": "欧忒耳佩上的奇袭地",
  "Shepherd's Rest": "牧人驿站",
  "Shepherd's Rest on Pyro III": "派罗III上的牧人驿站",
  "Shipping Hub": "航运中心",
  "Shubin Mining Facility SAL-2": "舒宾采矿设施 SAL-2",
  "Shubin Mining Facility SAL-2 on Lyria": "莉瑞雅上的舒宾采矿设施SAL-2",
  "Shubin Mining Facility SAL-5": "舒宾采矿设施 SAL-5",
  "Shubin Mining Facility SAL-5 on Lyria": "莉瑞雅上的舒宾采矿设施SAL-5",
  "Shubin Mining Facility SCD-1": "舒宾采矿设施 SCD-1",
  "Shubin Mining Facility SCD-1 on Daymar": "戴玛尔上的舒宾采矿设施SCD-1",
  "Shubin Mining Facility SM0-10": "舒宾采矿设施 SM0-10",
  "Shubin Mining Facility SM0-10 on microTech": "微科星上的舒宾采矿设施 SM0-10",
  "Shubin Mining Facility SM0-13": "舒宾采矿设施 SM0-13",
  "Shubin Mining Facility SM0-13 on microTech": "微科星上的舒宾采矿设施SM0-13",
  "Shubin Mining Facility SM0-18": "舒宾采矿设施 SM0-18",
  "Shubin Mining Facility SM0-18 on microTech": "微科星上的舒宾采矿设施 SM0-18",
  "Shubin Mining Facility SM0-22": "舒宾采矿设施 SM0-22",
  "Shubin Mining Facility SM0-22 on microTech": "微科星上的舒宾采矿设施SM0-22",
  "Shubin Mining Facility SMCa-6": "舒宾采矿设施 SMCa-6",
  "Shubin Mining Facility SMCa-6 on Calliope": "卡利俄佩上的舒宾采矿设施SMCa-6",
  "Shubin Mining Facility SMCa-8": "舒宾采矿设施 SMCa-8",
  "Shubin Mining Facility SMCa-8 on Calliope": "卡利俄佩上的舒宾采矿设施SMCa-8",
  "Shubin Processing Facility SPAL-12": "舒宾加工设施 SPAL-12",
  "Shubin Processing Facility SPAL-12 on Lyria": "莉瑞雅上的舒宾加工设施 SPAL-12",
  "Shubin Processing Facility SPAL-16": "舒宾加工设施 SPAL-16",
  "Shubin Processing Facility SPAL-16 on Lyria": "莉瑞雅上的舒宾加工设施 SPAL-16",
  "Shubin Processing Facility SPAL-21": "舒宾加工设施 SPAL-21",
  "Shubin Processing Facility SPAL-21 on Lyria": "莉瑞雅上的舒宾加工设施 SPAL-21",
  "Shubin Processing Facility SPAL-3": "舒宾加工设施 SPAL-3",
  "Shubin Processing Facility SPAL-3 on Lyria": "莉瑞雅上的舒宾加工设施 SPAL-3",
  "Shubin Processing Facility SPAL-7": "舒宾加工设施 SPAL-7",
  "Shubin Processing Facility SPAL-7 on Lyria": "莉瑞雅上的舒宾加工设施 SPAL-7",
  "Shubin Processing Facility SPAL-9": "舒宾加工设施 SPAL-9",
  "Shubin Processing Facility SPAL-9 on Lyria": "莉瑞雅上的舒宾加工设施 SPAL-9",
  "Shubin Processing Facility SPMC-1": "舒宾加工设施 SPMC-1",
  "Shubin Processing Facility SPMC-1 on Calliope": "卡利俄佩上的舒宾矿业设施 SPMC-1",
  "Shubin Processing Facility SPMC-10": "舒宾加工设施 SPMC-10",
  "Shubin Processing Facility SPMC-10 on Calliope": "卡利俄佩上的舒宾矿业设施 SPMC-10",
  "Shubin Processing Facility SPMC-11": "舒宾加工设施 SPMC-11",
  "Shubin Processing Facility SPMC-11 on Calliope": "卡利俄佩上的舒宾矿业设施 SPMC-11",
  "Shubin Processing Facility SPMC-14": "舒宾加工设施 SPMC-14",
  "Shubin Processing Facility SPMC-14 on Calliope": "卡利俄佩上的舒宾矿业设施 SPMC-14",
  "Shubin Processing Facility SPMC-3": "舒宾加工设施 SPMC-3",
  "Shubin Processing Facility SPMC-3 on Calliope": "卡利俄佩上的舒宾矿业设施 SPMC-3",
  "Shubin Processing Facility SPMC-5": "舒宾加工设施 SPMC-5",
  "Shubin Processing Facility SPMC-5 on Calliope": "卡利俄佩上的舒宾矿业设施 SPMC-5",
  "Shubin's Daymar outpost": "舒宾的戴玛尔前哨站",
  "Slowburn Depot": "惩忿仓库",
  "Slowburn Depot on Pyro II": "派罗 II上的惩忿仓库",
  "Smokestack": "烟囱站",
  "Smokestack on Arial": "艾瑞尔上的烟囱站",
  "Solanki Platform": "索兰奇平台",
  "Solanki Platform at Inspiration Park near Orison": "位于奥里森的灵感园区的索兰奇平台",
  "Stag's Rut": "雄鹿谷",
  "Stag's Rut on Pyro I": "派罗I上的雄鹿谷",
  "Stanton": "斯坦顿",
  "Stanton Gateway": "斯坦顿星门",
  "Starfarer wreck site": "星际远航者残骸地点",
  "Starlight Service Station": "星光服务站",
  "Starlight Service Station Clinic": "星光服务站诊所",
  "Starlight Service Station Entrance": "星光服务站入口",
  "Starlight Service Station Habs": "星光服务站居住区",
  "Starlight Service Station at the L1 Lagrange of Pyro III": "位于派罗III的L1拉格朗日点的星光空间服务站",
  "Stone's Throw": "狭地镇",
  "Stone's Throw on Cellin": "赛琳上的狭地镇",
  "Stonetree": "石林镇",
  "Stonetree on Pyro VI": "派罗VI上的石林镇",
  "Storage Depot": "仓储区",
  "Sunset Mesa": "日落方山",
  "Sunset Mesa on Pyro II": "派罗II上的日落方山",
  "Supply Gap": "补给处",
  "Supply Gap on Pyro VI": "派罗VI上的补给处",
  "TPF on Daymar": "戴玛尔上的TPF",
  "Talarine Divide Aid Shelter": "塔拉林峡谷援助避难所",
  "Talarine Divide Aid Shelter on Yela": "耶拉上的塔拉林峡谷援助避难所",
  "Tamdon Plains Aid Shelter": "坦登平原援助避难所",
  "Tamdon Plains Aid Shelter on Daymar": "戴玛尔上的坦登平原援助避难所",
  "Teasa Spaceport": "蒂莎空港",
  "Teasa Spaceport in Lorville": "罗威尔的蒂莎空港",
  "Technology Support Services": "技术支持服务部门",
  "Technology Support Services on the Admin Center near Orison": "位于奥里森行政中心上的技术支持部门",
  "Technotics on Grim HEX": "六角湾的技术通告商店",
  "Teddy's Playhouse": "泰迪的玩具屋",
  "Teddy's Playhouse on Lyria": "莉瑞雅上的泰迪的玩具屋",
  "Terminus": "端点星",
  "Terra Mills": "泰拉磨坊",
  "Terra Mills HydroFarm": "泰拉磨坊水培种植站",
  "Terra Mills HydroFarm on Cellin": "赛琳上的泰拉磨坊水培种植站",
  "The Barrens": "荒原",
  "The Barrens on microTech": "微科星上的荒原",
  "The Dregs": "残邑",
  "The Golden Riviera": "金碧湾",
  "The Golden Riviera on Pyro III": "派罗III上的金碧湾",
  "The Grove": "僻园",
  "The Grove on Aberdeen": "阿伯丁上的僻园",
  "The Hollows": "空谷",
  "The Hollows on Cellin": "赛琳上的空谷",
  "The Shades": "荫蔽处",
  "The Shades on Ita": "依塔上的荫蔽处",
  "The Yard": "“庭院”",
  "The Yard on Pyro III": "派罗III上的庭院",
  "Thimblerig": "坑蒙庄",
  "Thimblerig on Ita": "依塔上的坑蒙庄",
  "Thundering Express Station at Hurston's L3 Lagrange point": "位于赫斯顿L3拉格朗日点的雷霆快车站",
  "Tram & Myers": "泰姆&迈尔斯",
  "Tram & Myers Mining": "泰姆&迈尔斯矿站",
  "Tram & Myers Mining on Cellin": "赛琳上的泰姆&迈尔斯矿站",
  "Tremonte": "特雷蒙特",
  "Tremonte on Clio": "克利俄上的特雷蒙特",
  "Trilo": "三曲镇",
  "Trilo on Hurston": "赫斯顿上的三曲镇",
  "Vatra": "瓦塔拉",
  "Vatra Cave": "瓦塔拉洞穴",
  "Vivere OLP": "存活 激光站",
  "Vivere Orbital Laser Platform above Aberdeen": "阿伯丁上的存活 轨道激光平台",
  "Vivere PAF-I": "存活 校准站-I",
  "Vivere PAF-II": "存活 校准站-II",
  "Vivere PAF-III": "存活 校准站-III",
  "Vivere Platform Alignment Facility I on Aberdeen": "阿伯丁上的存活 平台校准设施I",
  "Vivere Platform Alignment Facility II on Aberdeen": "阿伯丁上的存活 平台校准设施II",
  "Vivere Platform Alignment Facility III on Aberdeen": "阿伯丁上的存活 平台校准设施III",
  "Vuur Cave": "伏尔洞穴",
  "Wailing Rock": "泣岩",
  "Wailing Rock on Daymar": "戴玛尔上的泣岩",
  "Wala": "瓦菈",
  "Wala Cave": "瓦菈的洞穴",
  "Wala Derelict Outpost": "瓦菈废弃前哨站",
  "Wallace's Lab": "华莱士实验室",
  "Wallace's Lab at Grim HEX": "六角湾内的华莱士的实验室",
  "Wally's Bar": "沃利酒吧",
  "Wally's Bar in New Babbage": "新巴贝奇的沃利酒吧",
  "Washout": "败涂地",
  "Washout on Wala": "瓦菈上的败涂地",
  "Watcher's Depot": "守望者仓库",
  "Watcher's Depot on Pyro VI": "派罗 VI上的守望者仓库",
  "Weeping Cove": "泪湾",
  "Weeping Cove on Hurston": "赫斯顿上的泪湾",
  "Whistler's Crypt": "惠斯勒地穴",
  "Whistler's Crypt on Daymar": "在戴尔玛上的惠斯勒地穴",
  "Wide Forest Station at ArcCorp's L1 Lagrange point": "位于弧光星的L1拉格朗日点的广袤森林站",
  "Wikelo Emporium Dasi Station": "维克洛百货 达西站",
  "Wikelo Emporium Dasi Station near Hurston": "赫斯顿附近的维克洛百货 达西站",
  "Wikelo Emporium Kinga Station": "维克洛百货 金加站",
  "Wikelo Emporium Kinga Station near microTech": "微科星附近的维克洛百货 金加站",
  "Wikelo Emporium Selo Station": "维克洛百货 赛洛站",
  "Wikelo Emporium Selo Station near Yela": "耶拉附近的维克洛百货 赛洛站",
  "Wiley Flats": "威利平原",
  "Wiley Flats on Wala": "瓦菈上的威利平原",
  "Windfall": "风落镇",
  "Windfall on Pyro III": "派罗III上的风落镇",
  "Wolf Point Aid Shelter": "狼穴援助避难所",
  "Wolf Point Aid Shelter on Daymar": "戴玛尔上的狼穴援助避难所",
  "World's End": "天涯",
  "World's End on Lyria": "莉瑞雅上的天涯",
  "Yang's Place": "杨家庄",
  "Yang's Place on Pyro II": "派罗II上的杨家庄",
  "Yela": "耶拉",
  "Yela Derelict Outpost": "耶拉废弃前哨站",
  "Yela's Rayari lab": "耶拉的拉亚利实验室",
  "Yela's asteroid belt": "耶拉的小行星带",
  "Yellow Core Station at ArcCorp's L5 Lagrange point": "位于弧光星的L5拉格朗日点的黄色核心站",
  "Zephyr": "西风镇",
  "Zephyr on Hurston": "赫斯顿上的西风镇",
  "a Cave on Arial": "一个位于艾瑞尔的洞穴",
  "a Cave on Cellin": "一个位于赛琳的洞穴",
  "a Cry-Astro station": "一个寒宇站点",
  "a Hurston Weapons Testing Site above Aberdeen": "一个阿伯丁上空的赫斯顿武器测试点",
  "a Hurston Weapons Testing Site above Arial": "一个位于艾瑞尔上空的赫斯顿武器测试点",
  "a Hurston Weapons Testing Site above Ita": "一个依塔上空的赫斯顿武器测试点",
  "a Hurston Weapons Testing Site above Magda": "一个位于玛格达上空的赫斯顿武器测试点",
  "a Landing Pad Locker in Area18": "一个在18区上的停机坪储物柜",
  "a Landing Pad Locker in New Babbage": "一个新巴贝奇上的停机坪储物柜",
  "a Landing Pad Locker in Orison": "一个奥里森的停机坪储物柜",
  "a Landing Pad Locker on ArcCorp": "一个在弧光星上的停机坪储物柜",
  "a Landing Pad Locker on microTech": "一个微科星上的停机坪储物柜",
  "a Private Landing Pad": "一个私人停机坪",
  "a Private Landing Pad in Area18": "18区的私人停机坪",
  "a Private Landing Pad on ArcCorp": "一个在弧光星上的私人停机坪",
  "a QV Breaker Station in the Glaciem Ring": "位于冰川环带的一个QV碎岩站",
  "a Salvage Yard on Daymar": "一个在戴玛尔上的废品回收站",
  "a Salvage Yard on Euterpe": "欧忒耳佩上的回收站",
  "a Salvage Yard on Hurston": "一个赫斯顿上的废品回收站",
  "a Salvage Yard on Wala": "一个瓦菈上的废品回收站",
  "a Yela asteroid cluster": "耶拉(Yela)的一处小行星群",
  "a cave on Aberdeen": "一个阿伯丁上的洞穴",
  "a cave on Adir": "一个位于阿迪尔的洞穴",
  "a cave on Calliope": "一个卡利俄佩上的洞穴",
  "a cave on Clio": "一个克利俄上的洞穴",
  "a cave on Daymar": "一个戴玛尔上的洞穴",
  "a cave on Euterpe": "一个欧忒耳佩洞穴上的洞穴",
  "a cave on Fairo": "一个位于法伊罗的洞穴",
  "a cave on Fuego": "一个位于弗果的洞穴",
  "a cave on Hurston": "一个赫斯顿上的洞穴",
  "a cave on Ita": "依塔上的一个洞穴",
  "a cave on Magda": "玛格达上的一个洞穴",
  "a cave on Pyro I": "一个位于派罗 I 的洞穴",
  "a cave on Pyro II": "一个位于派罗 II 的洞穴",
  "a cave on Pyro III": "一个位于派罗 III 的洞穴",
  "a cave on Pyro IV": "一个位于派罗 IV 的洞穴",
  "a cave on Pyro V": "一个位于派罗 V 的洞穴",
  "a cave on Pyro VI": "一个位于派罗 VI 的洞穴",
  "a cave on Vatra": "一个位于瓦塔拉的洞穴",
  "a cave on Vuur": "一个位于伏尔的洞穴",
  "a cave on Wala": "瓦菈上的一个洞穴",
  "a cave on microTech": "一个在微科星上的洞穴",
  "a crash site": "一处坠毁地点",
  "a dead drop": "一个秘密站点",
  "a dead drop on Cellin": "赛琳的一个秘密站点",
  "a dead drop on Daymar": "戴玛尔上的一个秘密站点",
  "a dead drop on Yela": "耶拉的一个秘密站点",
  "a debris field above ArcCorp": "弧光星上的废品厂",
  "a debris field above Calliope": "卡利俄佩上的废品厂",
  "a debris field above Cellin": "赛琳上的废品厂",
  "a debris field above Clio": "克利俄上的废品厂",
  "a debris field above Crusader": "十字军上的废品厂",
  "a debris field above Daymar": "戴玛尔上的废品厂",
  "a debris field above Euterpe": "欧忒耳佩上的废品厂",
  "a debris field above Lyria": "莉瑞雅上的废品厂",
  "a debris field above Wala": "瓦菈上的废品厂",
  "a derelict outpost": "一个废弃前哨站",
  "a derelict outpost on Clio": "克利俄上的一个废弃前哨站",
  "a derelict outpost on Daymar": "戴玛尔上的一个废弃前哨站",
  "a derelict outpost on Euterpe": "欧忒耳佩上的一个废弃前哨站",
  "a derelict outpost on Hurston": "赫斯顿上的一个废弃前哨站",
  "a derelict outpost on Ita": "依塔上的一个废弃前哨站",
  "a derelict outpost on Lyria": "莉瑞雅上的一个废弃前哨站",
  "a derelict outpost on Magda": "玛格达上的一个废弃前哨站",
  "a derelict outpost on Wala": "瓦菈上的一个废弃前哨站",
  "a derelict outpost on Yela": "耶拉上的一个废弃前哨站",
  "a derelict outpost on microTech": "微科星上的废弃前哨站",
  "a local asteroid belt": "当地的小行星带",
  "a location in the Glaciem Ring": "位于冰川环带中的一处地点",
  "a location on Delamar": "位于德拉玛上的一处地点",
  "a mined asteroid cluster around Yela": "耶拉(Yela)的一处矿物小行星群",
  "a shelter on Cellin": "赛琳上的一个避难所",
  "a shelter on Daymar": "戴玛尔上的一个避难所",
  "a shelter on Yela": "耶拉上的一个避难所",
  "a shipwreck": "一个飞船残骸",
  "a site of potential scientific significance": "具有潜在科学意义的地点",
  "a specific point of interest": "一个特殊的兴趣点",
  "a stash house": "一个藏匿屋",
  "a stash house on Cellin": "赛琳上的一个藏匿屋",
  "a stash house on Daymar": "戴玛尔上的一个藏匿屋",
  "a stash house on Yela": "耶拉上的一个藏匿屋",
  "a wreck site": "一处残骸位置",
  "a wreck site in the Keeger Belt": "位于基格小行星带的一处残骸位置",
  "an abandoned outpost on Pyro 5a": "一个位于派罗 5a 的废弃前哨站",
  "an abandoned outpost on Pyro 5b": "一个位于派罗 5b 的废弃前哨站",
  "an abandoned outpost on Pyro 5c": "一个位于派罗 5c 的废弃前哨站",
  "an abandoned outpost on Pyro 5d": "一个位于派罗 5d 的废弃前哨站",
  "an abandoned outpost on Pyro 5e": "一个位于派罗 5e 的废弃前哨站",
  "an abandoned outpost on Pyro 5f": "一个位于派罗 5f 的废弃前哨站",
  "an abandoned outpost on Pyro I": "一个位于派罗 I 的废弃前哨站",
  "an abandoned outpost on Pyro II": "一个位于派罗 II 的废弃前哨站",
  "an abandoned outpost on Pyro III": "一个位于派罗 III 的废弃前哨站",
  "an abandoned outpost on Pyro IV": "一个位于派罗 IV 的废弃前哨站",
  "an abandoned outpost on Pyro V": "一个位于派罗 V 的废弃前哨站",
  "an abandoned outpost on Pyro VI": "一个位于派罗 VI 的废弃前哨站",
  "an asteroid cluster in the Glaciem Ring": "一群冰川环带中的小行星群",
  "an asteroid cluster in the Keeger Belt": "基格小行星带的一处小行星群",
  "cave on Ignis": "位于伊格尼斯的洞穴",
  "microTech Cave": "微科星洞穴",
  "microTech Derelict Outpost": "微科星废弃前哨站",
  "microTech Logistics Depot S4LD01": "微科物流仓库 S4LD01",
  "microTech Logistics Depot S4LD01 on microTech": "微科星上的微科物流仓库 S4LD01",
  "microTech Logistics Depot S4LD13": "微科物流仓库 S4LD13",
  "microTech Logistics Depot S4LD13 on microTech": "微科星上的微科公司物流仓库 S4LD13",
  "sections above Aberdeen's atmosphere": "在阿伯丁大气上的部分",
  "ship graveyards around Aberdeen": "阿伯丁附近的飞船墓地",
  "somewhere private": "私人领地",
  "specific coordinates": "具体坐标",
  "that dreadful Reclamation store": "骇人的回收商店",
  "the ArcCorp mining facility on Daymar": "弧光集团在戴玛尔上的采矿设施",
  "the ArcCorp outpost on Daymar": "弧光集团在戴玛尔上的前哨站",
  "the ArcCorp outpost on Yela": "弧光集团在耶拉上的前哨站",
  "the ArcCorp refinery on Daymar": "弧光集团在戴玛尔上的精炼站",
  "the Ariel wreck site": "艾瑞尔上的残骸地点",
  "the Calliope wreck site": "卡利俄佩上的残骸地点",
  "the Cellin farming outpost": "赛琳农业站",
  "the Cellin wreck site": "赛琳上的残骸地点",
  "the Central Core in the QV Breaker Station": "QV碎岩站的中央核心区",
  "the Clio wreck site": "克利俄上的残骸地点",
  "the Daymar Shubin outpost": "戴玛尔舒宾前哨站",
  "the Daymar wreck site": "戴玛尔上的残骸地点",
  "the Dregs on Arial": "艾瑞尔上的残邑",
  "the Euterpe wreck site": "欧忒耳佩上的残骸地点",
  "the Garden": "庭园",
  "the Garden on Daymar": "戴玛尔上的“庭园”",
  "the Glaciem Ring": "冰川环带",
  "the Hurston wreck site": "赫斯顿上的残骸地点",
  "the Ita wreck site": "依塔上的残骸地点",
  "the Keeger Belt": "基格小行星带",
  "the Lyria wreck site": "莉瑞雅上的残骸地点",
  "the Magda wreck site": "玛格达上的残骸地点",
  "the Operations office in the QV Breaker Station": "QV碎岩站的运营办公室",
  "the People's Alliance": "人民联盟",
  "the Port Olisar Transfer Hub": "奥丽莎空间站中转枢纽",
  "the Rayari lab on Cellin": "赛琳上的拉亚利实验室",
  "the Rayari lab on Yela": "耶拉的拉亚利实验室",
  "the Rayari outpost": "拉亚利前哨站",
  "the Rayari, Inc. outpost on Cellin": "拉亚利公司在赛琳上的前哨站",
  "the Rayari, Inc. outpost on Yela": "耶拉上的拉利亚公司前哨站",
  "the Sector 1 Engineering area in the QV Breaker Station": "QV碎岩站的1号工程区",
  "the Sector 2 Excavation area in the QV Breaker Station": "QV碎岩站的2号挖掘区",
  "the Service Entrance in the QV Breaker Station": "QV碎岩站的服务入口",
  "the Shubin mining facility on Daymar": "戴玛尔的舒宾采矿设施",
  "the Shubin ore refinery on Daymar": "戴玛尔上的舒宾矿石精炼站",
  "the Shubin outpost on Daymar": "戴玛尔的舒宾前哨站",
  "the Storage Depot in the QV Breaker Station": "QV碎岩站的仓储区",
  "the Terra Mills outpost on Cellin": "赛琳上的泰拉磨坊前哨站",
  "the Wala wreck site": "瓦菈上的残骸地点",
  "the Yela wreck site": "耶拉上的残骸地点",
  "the abandoned outpost on Cellin": "赛琳上被遗弃的前哨站",
  "the abandoned outpost on Daymar": "戴玛尔上被遗弃的前哨站",
  "the abandoned outpost on Yela": "耶拉上被遗弃的前哨站",
  "the abandoned section inside Checkmate at the L4 Lagrange of Pyro II": "位于派罗II的L4拉格朗日点的死局空间站内的废弃区域",
  "the abandoned section inside Dudley & Daughters at the L4 Lagrange of Pyro VI": "位于派罗VI的L4拉格朗日点的达德利父女空间站内的废弃区域",
  "the abandoned section inside Endgame at the L3 Lagrange of Pyro VI": "位于派罗VI的L3拉格朗日点的终局空间站内的废弃区域",
  "the abandoned section inside Gaslight at the L2 Lagrange of Pyro V": "派罗V的L2拉格朗日点的煤气灯空间站内的废弃区域",
  "the abandoned section inside Megumi Refueling at the L5 Lagrange of Pyro VI": "位于派罗VI的L5拉格朗日点的恩惠加油站内的废弃区域",
  "the abandoned section inside Orbituary above Pyro III": "位于派罗III上空的轨道讣闻站内的废弃区域",
  "the abandoned section inside PYAM-FARSTAT-1-2 at the L2 Lagrange of Pyro I": "位于派罗I的L2拉格朗日点的焰联-远程站-1-2内的废弃区域",
  "the abandoned section inside PYAM-FARSTAT-1-3 at the L3 Lagrange of Pyro I": "位于派罗I的L3拉格朗日点的焰联-远程站-1-3内的废弃区域",
  "the abandoned section inside PYAM-FARSTAT-1-5 at the L5 Lagrange of Pyro I": "位于派罗I的L5拉格朗日点的焰联-远程站-1-5内的废弃区域",
  "the abandoned section inside PYAM-FARSTAT-2-0 above Pyro II": "位于派罗II上空的焰联-远程站-2-0内的废弃区域",
  "the abandoned section inside PYAM-FARSTAT-2-3 at the L3 Lagrange of Pyro II": "位于派罗II的L3拉格朗日点的焰联-远程站-2-3内的废弃区域",
  "the abandoned section inside PYAM-FARSTAT-3-5 at the L5 Lagrange of Pyro III": "位于派罗III的L5拉格朗日点的焰联-远程站-3-5内的废弃区域",
  "the abandoned section inside PYAM-FARSTAT-5-1 at the L1 Lagrange of Pyro V": "位于派罗V的L1拉格朗日点的焰联-远程站-5-1内的废弃区域",
  "the abandoned section inside PYAM-FARSTAT-5-3 at the L3 Lagrange of Pyro V": "位于派罗V的L3拉格朗日点的焰联-远程站-5-3内的废弃区域",
  "the abandoned section inside PYAM-FARSTAT-6-2 at the L2 Lagrange of Pyro VI": "位于派罗VI的L2拉格朗日点的焰联-远程站-6-2内的废弃区域",
  "the abandoned section inside Patch City at the L3 Lagrange of Pyro III": "位于派罗III的L3拉格朗日点的补丁城内的废弃区域",
  "the abandoned section inside Rat's Nest at the L5 Lagrange of Pyro V": "位于派罗V的L5拉格朗日点的鼠巢空间站内的废弃区域",
  "the abandoned section inside Rod's Fuel 'N Supplies at the L4 Lagrange of Pyro V": "位于派罗V的L4拉格朗日点的路德补给站内的废弃区域",
  "the asteroid field orbiting Yela": "环绕耶拉的小行星带",
  "the asteroids surrounding Delamar": "德拉玛周围的小行星堆",
  "the asteroids surrounding Yela": "耶拉周围的小行星堆",
  "the clinic inside Checkmate at the L4 Lagrange of Pyro II": "位于派罗II的L4拉格朗日点的死局空间站内的诊所",
  "the clinic inside Dudley & Daughters at the L4 Lagrange of Pyro VI": "位于派罗VI的L4拉格朗日点的达德利父女空间站内的诊所",
  "the clinic inside Endgame at the L3 Lagrange of Pyro VI": "位于派罗VI的L3拉格朗日点的终局空间站内的诊所",
  "the clinic inside Gaslight at the L2 Lagrange of Pyro V": "位于派罗V的L2拉格朗日点的煤气灯空间站内的诊所",
  "the clinic inside Megumi Refueling at the L5 Lagrange of Pyro VI": "位于派罗VI的L5拉格朗日点的恩惠加油站内的诊所",
  "the clinic inside Orbituary above Pyro III": "位于派罗III上空的轨道讣闻站内的诊所",
  "the clinic inside PYAM-FARSTAT-1-2 at the L2 Lagrange of Pyro I": "位于派罗I的L2拉格朗日点的焰联-远程站-1-2内的诊所",
  "the clinic inside PYAM-FARSTAT-1-3 at the L3 Lagrange of Pyro I": "位于派罗I的L3拉格朗日点的焰联-远程站-1-3内的诊所",
  "the clinic inside PYAM-FARSTAT-1-5 at the L5 Lagrange of Pyro I": "位于派罗I的L5拉格朗日点的焰联-远程站-1-5内的诊所",
  "the clinic inside PYAM-FARSTAT-2-0 above Pyro II": "位于派罗II上空的焰联-远程站-2-0内的诊所",
  "the clinic inside PYAM-FARSTAT-2-3 at the L3 Lagrange of Pyro II": "位于派罗II的L3拉格朗日点的焰联-远程站-2-3内的诊所",
  "the clinic inside PYAM-FARSTAT-3-5 at the L5 Lagrange of Pyro III": "位于派罗III的L5拉格朗日点的焰联-远程站-3-5内的诊所",
  "the clinic inside PYAM-FARSTAT-5-1 at the L1 Lagrange of Pyro V": "位于派罗V的L1拉格朗日点的焰联-远程站-5-1内的诊所",
  "the clinic inside PYAM-FARSTAT-5-3 at the L3 Lagrange of Pyro V": "位于派罗V的L3拉格朗日点的焰联-远程站-5-3内的诊所",
  "the clinic inside PYAM-FARSTAT-6-2 at the L2 Lagrange of Pyro VI": "位于派罗VI的L2拉格朗日点的焰联-远程站-6-2内的诊所",
  "the clinic inside Patch City at the L3 Lagrange of Pyro III": "位于派罗III的L3拉格朗日点的补丁城内的诊所",
  "the clinic inside Rat's Nest at the L5 Lagrange of Pyro V": "位于派罗V的L5拉格朗日点的鼠巢空间站内的诊所",
  "the clinic inside Rod's Fuel 'N Supplies at the L4 Lagrange of Pyro V": "位于派罗V的L4拉格朗日点的路德补给站内的诊所",
  "the clinic inside Ruin Station above Pyro VI": "位于派罗VI上空的废墟空间站内的诊所",
  "the clinic inside Starlight Service Station at the L1 Lagrange of Pyro III": "位于派罗III的L1拉格朗日点的星光服务站内的诊所",
  "the drug lab on Daymar": "戴玛尔上的毒品站",
  "the entrance inside Checkmate at the L4 Lagrange of Pyro II": "位于派罗II的L4拉格朗日点的死局空间站内的入口",
  "the entrance inside Dudley & Daughters at the L4 Lagrange of Pyro VI": "位于派罗VI的L4拉格朗日点的达德利父女空间站内的入口",
  "the entrance inside Endgame at the L3 Lagrange of Pyro VI": "位于派罗VI的L3拉格朗日点的终局空间站内的入口",
  "the entrance inside Gaslight at the L2 Lagrange of Pyro V": "位于派罗V的L2拉格朗日点的煤气灯空间站内的入口",
  "the entrance inside Megumi Refueling at the L5 Lagrange of Pyro VI": "位于派罗VI的L5拉格朗日点的恩惠加油站内的入口",
  "the entrance inside Orbituary above Pyro III": "位于派罗III上空的轨道讣闻站内的入口",
  "the entrance inside PYAM-FARSTAT-1-2 at the L2 Lagrange of Pyro I": "位于派罗I的L2拉格朗日点的焰联-远程站-1-2内的入口",
  "the entrance inside PYAM-FARSTAT-1-3 at the L3 Lagrange of Pyro I": "位于派罗I的L3拉格朗日点的焰联-远程站-1-3内的入口",
  "the entrance inside PYAM-FARSTAT-1-5 at the L5 Lagrange of Pyro I": "位于派罗I的L5拉格朗日点的焰联-远程站-1-5内的入口",
  "the entrance inside PYAM-FARSTAT-2-0 above Pyro II": "位于派罗II上空的焰联-远程站-2-0内的入口",
  "the entrance inside PYAM-FARSTAT-2-3 at the L3 Lagrange of Pyro II": "位于派罗II的L3拉格朗日点的焰联-远程站-2-3内的入口",
  "the entrance inside PYAM-FARSTAT-3-5 at the L5 Lagrange of Pyro III": "位于派罗III的L5拉格朗日点的焰联-远程站-3-5内的入口",
  "the entrance inside PYAM-FARSTAT-5-1 at the L1 Lagrange of Pyro V": "位于派罗V的L1拉格朗日点的焰联-远程站-5-1内的入口",
  "the entrance inside PYAM-FARSTAT-5-3 at the L3 Lagrange of Pyro V": "位于派罗V的L3拉格朗日点的焰联-远程站-5-3内的入口",
  "the entrance inside PYAM-FARSTAT-6-2 at the L2 Lagrange of Pyro VI": "位于派罗VI的L2拉格朗日点的焰联-远程站-6-2内的入口",
  "the entrance inside Patch City at the L3 Lagrange of Pyro III": "位于派罗III的L3拉格朗日点的补丁城内的入口",
  "the entrance inside Rat's Nest at the L5 Lagrange of Pyro V": "位于派罗V的L5拉格朗日点的鼠巢空间站内的入口",
  "the entrance inside Rod's Fuel 'N Supplies at the L4 Lagrange of Pyro V": "位于派罗V的L4拉格朗日点的路德补给站内的入口",
  "the entrance inside Ruin Station above Pyro VI": "位于派罗VI上空的废墟空间站内的入口",
  "the entrance inside Starlight Service Station at the L1 Lagrange of Pyro III": "位于派罗III的L1拉格朗日点的星光服务站内的入口",
  "the farm": "种植站",
  "the farm on Cellin": "赛琳的农场",
  "the farm on Daymar": "戴玛尔上的种植站",
  "the farming outpost on Cellin": "赛琳的农业站",
  "the habs inside Checkmate at the L4 Lagrange of Pyro II": "位于派罗II的L4拉格朗日点的死局空间站内的居住区",
  "the habs inside Dudley & Daughters at the L4 Lagrange of Pyro VI": "位于派罗VI的L4拉格朗日点的达德利父女空间站内的居住区",
  "the habs inside Endgame at the L3 Lagrange of Pyro VI": "位于派罗VI的L3拉格朗日点的终局空间站内的居住区",
  "the habs inside Gaslight at the L2 Lagrange of Pyro V": "位于派罗V的L2拉格朗日点的煤气灯空间站内的居住区",
  "the habs inside Megumi Refueling at the L5 Lagrange of Pyro VI": "位于派罗VI的L5拉格朗日点的恩惠加油站内的居住区",
  "the habs inside Orbituary above Pyro III": "位于派罗III上空的轨道讣闻站内的居住区",
  "the habs inside PYAM-FARSTAT-1-2 at the L2 Lagrange of Pyro I": "位于派罗I的L2拉格朗日点的焰联-远程站-1-2内的居住区",
  "the habs inside PYAM-FARSTAT-1-3 at the L3 Lagrange of Pyro I": "位于派罗I的L3拉格朗日点的焰联-远程站-1-3内的居住区",
  "the habs inside PYAM-FARSTAT-1-5 at the L5 Lagrange of Pyro I": "位于派罗I的L5拉格朗日点的焰联-远程站-1-5内的居住区",
  "the habs inside PYAM-FARSTAT-2-0 above Pyro II": "位于派罗II上空的焰联-远程站-2-0内的居住区",
  "the habs inside PYAM-FARSTAT-2-3 at the L3 Lagrange of Pyro II": "位于派罗II的L3拉格朗日点的焰联-远程站-2-3内的居住区",
  "the habs inside PYAM-FARSTAT-3-5 at the L5 Lagrange of Pyro III": "位于派罗III的L5拉格朗日点的焰联-远程站-3-5内的居住区",
  "the habs inside PYAM-FARSTAT-5-1 at the L1 Lagrange of Pyro V": "位于派罗V的L1拉格朗日点的焰联-远程站-5-1内的居住区",
  "the habs inside PYAM-FARSTAT-5-3 at the L3 Lagrange of Pyro V": "位于派罗V的L3拉格朗日点的焰联-远程站-5-3的居住区",
  "the habs inside PYAM-FARSTAT-6-2 at the L2 Lagrange of Pyro VI": "位于派罗VI的L2拉格朗日点的焰联-远程站-6-2内的居住区",
  "the habs inside Patch City at the L3 Lagrange of Pyro III": "派罗III的L3拉格朗日点的补丁城内的居住区",
  "the habs inside Rat's Nest at the L5 Lagrange of Pyro V": "位于派罗V的L5拉格朗日点的鼠巢空间站内的居住区",
  "the habs inside Rod's Fuel 'N Supplies at the L4 Lagrange of Pyro V": "位于派罗V的L4拉格朗日点的路德补给站内的居住区",
  "the habs inside Ruin Station above Pyro VI": "位于派罗VI上空的废墟空间站内的居住区",
  "the habs inside Starlight Service Station at the L1 Lagrange of Pyro III": "位于派罗III的L1拉格朗日点的星光服务站内的居住区",
  "the hydroponics farm on Cellin": "赛琳的水培农场",
  "the lab": "实验室",
  "the lab on Yela": "耶拉的科研站",
  "the maintenance area inside PYAM-FARSTAT-1-2 at the L2 Lagrange of Pyro I": "位于派罗I的L2拉格朗日点的焰联-远程站-1-2内的维修区",
  "the maintenance area inside PYAM-FARSTAT-1-3 at the L3 Lagrange of Pyro I": "位于派罗I的L3拉格朗日点的焰联-远程站-1-3内的维修区",
  "the maintenance area inside PYAM-FARSTAT-1-5 at the L5 Lagrange of Pyro I": "位于派罗I的L5拉格朗日点的焰联-远程站-1-5内的维修区",
  "the maintenance area inside PYAM-FARSTAT-2-0 above Pyro II": "位于派罗II上空的焰联-远程站-2-0内的维修区",
  "the maintenance area inside PYAM-FARSTAT-2-3 at the L3 Lagrange of Pyro II": "位于派罗II的L3拉格朗日点的焰联-远程站-2-3内的维修区",
  "the maintenance area inside PYAM-FARSTAT-3-5 at the L5 Lagrange of Pyro III": "位于派罗III的L5拉格朗日点的焰联-远程站-3-5内的维修区",
  "the maintenance area inside PYAM-FARSTAT-5-1 at the L1 Lagrange of Pyro V": "位于派罗V的L1拉格朗日点的焰联-远程站-5-1内的维修区",
  "the maintenance area inside PYAM-FARSTAT-5-3 at the L3 Lagrange of Pyro V": "位于派罗V的L3拉格朗日点的焰联-远程站-5-3内的维修区",
  "the maintenance area inside PYAM-FARSTAT-6-2 at the L2 Lagrange of Pyro VI": "位于派罗VI的L2拉格朗日点的焰联-远程站-6-2内的维修区",
  "the microTech wreck site": "微科星上的残骸地点",
  "the mine on Daymar": "戴玛尔的矿区",
  "the mining facility": "采矿设施",
  "the mining facility on Yela": "耶拉上的采矿设施",
  "the mining outpost": "采矿站",
  "the mining outpost on Daymar": "戴玛尔的采矿站",
  "the mining outpost on Yela": "耶拉的采矿站",
  "the refinery inside Checkmate at the L4 Lagrange of Pyro II": "位于派罗II的L4拉格朗日点的死局空间站内的精炼站",
  "the refinery inside Orbituary above Pyro III": "位于派罗III上空的轨道讣闻站内的精炼站",
  "the refinery inside Ruin Station above Pyro VI": "位于派罗VI上空的废墟空间站内的精炼站",
  "the refinery outpost on Daymar": "戴玛尔的精炼站",
  "the refinery outpost on Yela": "耶拉上的精炼站",
  "the research outpost": "科研站",
  "the research outpost on Cellin": "赛琳上的研究前哨站",
  "the research outpost on Yela": "耶拉的科研站",
  "the wreck site on Aberdeen": "位于阿伯丁的残骸地点",
  "the wreck site on Ariel": "位于艾瑞尔的残骸地点",
  "the wreck site on Calliope": "位于卡利俄佩的残骸地点",
  "the wreck site on Cellin": "位于赛琳的残骸地点",
  "the wreck site on Clio": "位于克利俄的残骸地点",
  "the wreck site on Daymar": "位于戴玛尔的残骸地点",
  "the wreck site on Euterpe": "位于欧忒耳佩的残骸地点",
  "the wreck site on Hurston": "赫斯顿上的残骸地点",
  "the wreck site on Ita": "位于依塔的残骸地点",
  "the wreck site on Lyria": "位于莉瑞雅的残骸地点",
  "the wreck site on Magda": "位于玛格达的残骸地点",
  "the wreck site on Wala": "位于瓦菈的残骸地点",
  "the wreck site on Yela": "位于耶拉的残骸地点",
  "the wreck site on microTech": "位于微科星的残骸地点",
  "this chemist on Yela": "耶拉上的化学实验室",
  "this quiet, out-of-the-way place": "僻静之地",
  "wreck site near ArcCorp": "弧光星附近的残骸地点",
  "wreck site near Crusader": "十字军附近的残骸地点",
  "wreck site near Hurston": "赫斯顿附近的残骸地点",
  "wreck site near MicroTech": "微科星附近的残骸地点",
};

export function getLocationZh(enName: string | null): string {
  if (!enName) return "";
  return LOCATION_EN_TO_ZH[enName] || enName;
}
