// Auto-generated from 地名对照.xlsx
const LOCATION_EN_TO_ZH: Record<string, string> = {
  "ARC-L1 Wide Forest Station": "弧光-L1 广袤森林站",
  "ARC-L2 Lively Pathway Station": "弧光-L2 活力小径站",
  "ARC-L3 Modern Express Station": "弧光-L3 摩登快车站",
  "ARC-L4 Faint Glen Station": "弧光-L4 黯淡幽谷站",
  "ARC-L5 Yellow Core Station": "弧光-L5 黄色核心站",
  "Area 18": "18区",
  "Baijini Point": "拜基尼空间站",
  "CRU-L1 Ambitious Dream Station": "十字军-L1 雄心伟梦站",
  "CRU-L4 Shallow Fields Station": "十字军-L4 轻浅田野站",
  "CRU-L5 Beautiful Glen Station": "十字军-L5 美丽峡谷站",
  "Checkmate Station": "死局空间站",
  "Dudley & Daughters": "达德利父女空间站",
  "Endgame": "终局空间站",
  "Everus Harbor": "埃弗勒斯空间站",
  "Gaslight": "煤气灯空间站",
  "Green Imperial Housing Exchange": "格林皇家 Housing Exchange",
  "HUR-L1 Green Glade Station": "赫斯顿-L1 绿色林地站",
  "HUR-L2 Faithful Dream Station": "赫斯顿-L2 坚贞梦想站",
  "HUR-L3 Thundering Express Station": "赫斯顿-L3 雷霆快车站",
  "HUR-L4 Melodic Fields Station": "赫斯顿-L4 旋律领域站",
  "HUR-L5 High Course Station": "赫斯顿-L5 高速路线站",
  "Levski": "列夫斯基",
  "Lorville": "罗威尔",
  "MIC-L1 Shallow Frontier Station": "微科-L1 浅边站",
  "MIC-L2 Long Forest Station": "微科-L2 长林站",
  "MIC-L3 Endless Odyssey Station": "微科-L3 无尽漫游站",
  "MIC-L4 Red Crossroads Station": "微科-L4 红色十字路口站",
  "MIC-L5 Modern Icarus Station": "微科-L5 现代伊卡洛斯站",
  "Megumi Refueling": "恩惠加油站",
  "New Babbage": "新巴贝奇",
  "Nyx": "尼克斯",
  "Nyx Gateway (Pyro)": "Nyx (Pyro)",
  "Nyx Gateway (Stanton)": "Nyx (Stanton)",
  "Orbituary": "轨道讣闻站",
  "Orison": "十字军上的奥里森",
  "Patch City": "补丁城",
  "People's Service Station Alpha": "人民服务空间站 阿尔法",
  "People's Service Station Delta": "人民服务空间站 德尔塔",
  "People's Service Station Lambda": "人民服务空间站 拉姆达",
  "People's Service Station Theta": "人民服务空间站 西塔",
  "Port Olisar": "奥丽莎空间站",
  "Port Tressler": "特雷斯勒空间站",
  "Pyro": "派罗",
  "Pyro Gateway (Nyx)": "Pyro (Nyx)",
  "Pyro Gateway (Stanton)": "Pyro (Stanton)",
  "Rat's Nest": "鼠巢空间站",
  "Rod's Fuel 'N Supplies": "路德补给站",
  "Ruin Station": "废墟空间站",
  "Seraphim Station": "炽天使空间站",
  "Stanton": "斯坦顿",
  "Stanton Gateway (Nyx)": "斯坦顿星门 (Nyx)",
  "Stanton Gateway (Pyro)": "斯坦顿星门 (Pyro)",
  "Starlight Service Station": "星光服务站",
  "Terra Gateway (Stanton)": "Terra (Stanton)",
};

export function getLocationZh(enName: string | null): string {
  if (!enName) return "";
  return LOCATION_EN_TO_ZH[enName] || enName;
}
