// Ship name Chinese translations from 对照.xlsx (official SC localization)
const SHIP_ZH: Record<string, string> = {
  'MISC Hull E': '武藏 货轮 E',
  'MISC Hull D': '武藏 货轮 D',
  'Anvil Odin': '铁砧 奥丁',
  'MISC Hull C': '武藏 货轮 C',
  'Drake Kraken': '德雷克 海妖',
  'Banu Merchantman': '巴努 商船',
  'Drake Ironclad': '德雷克 铁甲',
  'Drake Ironclad Assault': '德雷克 铁甲 突袭',
  'Aegis Idris-P': '圣盾 伊德里斯-P',
  'Aegis Idris-M': '圣盾 伊德里斯-M',
  'C.O. Pioneer': '联合外域 开拓者',
  'Drake Kraken Privateer': '德雷克 海妖 私掠',
  'Crusader C2 Hercules Starlifter': '十字军 大力神 C2 星际运输船',
  'Gatac Railen': '盖塔克 锐伦',
  'RSI Arrastra': 'RSI 阿拉斯塔',
  'Drake Caterpillar': '德雷克 毛虫',
  'Drake Caterpillar Best In Show Edition': '德雷克 毛虫 展会版',
  'Drake Caterpillar Pirate Edition': '德雷克 毛虫 海盗版',
  'RSI Polaris': 'RSI 北极星',
  'Crusader M2 Hercules Starlifter': '十字军 大力神 M2 星际运输船',
  'MISC Hull B': '武藏 货轮 B',
  'MISC Endeavor': '武藏 奋进',
  'Anvil Carrack': '铁砧 克拉克',
  'Anvil Carrack Expedition': '铁砧 克拉克 远征',
  'Aegis Reclaimer': '圣盾 回收者',
  'Anvil Liberator': '铁砧 解放者',
  'Origin 890 Jump': '起源 890 跃动',
  'RSI Orion': 'RSI 猎户座',
  'Crusader Genesis Starliner': '十字军 创世纪 星际航线',
  'MISC Starfarer': '武藏 星际远航者',
  'MISC Starfarer Gemini': '武藏 星际远航者 双子座',
  'RSI Hermes': 'RSI 赫尔墨斯',
  'MISC Odyssey': '武藏 奥德赛',
  'Anvil Crucible': '铁砧 坩埚',
  'Crusader A2 Hercules Starlifter': '十字军 大力神 A2 星际运输船',
  'MISC Starlancer MAX': '武藏 星际枪骑兵 MAX',
  'Argo MOTH': '南船座 飞蛾',
  'Argo RAFT': '南船座 木筏',
  'Aegis Reclaimer Best In Show Edition': '圣盾 回收者 展会版',
  'Anvil Asgard': '铁砧 阿斯加德',
  'RSI Constellation Taurus': 'RSI 星座 金牛座',
  'MISC Expanse': '武藏 无垠',
  'RSI Zeus Mk II CL': 'RSI 宙斯 MK II CL',
  'MISC Freelancer MAX': '武藏 自由枪骑兵 MAX',
  'Crusader Mercury Star Runner': '十字军 墨丘利 星际快运船',
  'RSI Constellation Andromeda': 'RSI 星座 仙女座',
  'RSI Constellation Aquila': 'RSI 星座 天鹰座',
  'Argo MOLE Carbon Edition': '南船座 鼹鼠 碳纤版',
  'Argo MOLE Talus Edition': '南船座 鼹鼠 岩屑版',
  'RSI Perseus': 'RSI 英仙座',
  'MISC Starlancer TAC': '武藏 星际枪骑兵 TAC',
  'Gatac Tyilui': '盖塔克 缇律',
  'Anvil Valkyrie': '铁砧 女武神',
  'RSI Constellation Phoenix': 'RSI 星座 凤凰座',
  'RSI Constellation Phoenix Emerald': 'RSI 星座 凤凰座 翡翠绿',
  'Aegis Retaliator': '圣盾 报复者',
  'Aegis Retaliator Bomber': '圣盾 报复者 轰炸',
  'Drake Corsair': '德雷克 海盗船',
  'MISC Freelancer': '武藏 自由枪骑兵',
  'RSI Galaxy': 'RSI 银河',
  'MISC Hull A': '武藏 货轮 A',
  'Aegis Nautilus': '圣盾 鹦鹉螺',
  'Aegis Nautilus Solstice Edition': '圣盾 鹦鹉螺 至日版',
  'Crusader C1 Spirit': '十字军 星灵 C1',
  'Drake Golem Ox': '德雷克 魔像 OX',
  'Aegis Tiburon': '圣盾 狂鲨',
  'Drake Cutlass Black': '德雷克 黑弯刀',
  'Drake Cutlass Black Best In Show Edition': '德雷克 黑弯刀 展会版',
  'Origin 600i Explorer': '起源 600i 探索版',
  'Origin 400i': '起源 400i',
  'Origin 600i Executive Edition': '起源 600i 行政版',
  'Aegis Hammerhead': '圣盾 锤头鲨',
  'Aegis Hammerhead Best In Show Edition': '圣盾 锤头鲨 展会版',
  'MISC Freelancer DUR': '武藏 自由枪骑兵 DUR',
  'MISC Freelancer MIS': '武藏 自由枪骑兵 MIS',
  'RSI Apollo Medivac': 'RSI 阿波罗 医疗',
  'RSI Apollo Triage': 'RSI 阿波罗 分诊',
  'Argo MOLE': '南船座 鼹鼠',
  'RSI Zeus Mk II ES': 'RSI 宙斯 MK II ES',
  'Drake Golem': '德雷克 魔像',
  'Esperia Prowler Utility': '埃斯佩里亚 徘徊者 多功能',
  "Grey's Market Shiv": '灰色市场 匕首',
  'Anvil Valkyrie Liberator Edition': '铁砧 女武神 解放版',
  'C.O. Nomad': '联合外域 游牧者',
  'Origin 600i Touring': '起源 600i 旅行版',
  'RSI Zeus Mk II MR': 'RSI 宙斯 MK II MR',
  'Argo MPUV Tractor': '南船座 MPUV 牵引',
  'MISC Fortune': '武藏 财运',
  'Origin 315p': '起源 315p',
  'Drake Cutlass Blue': '德雷克 蓝弯刀',
  'Drake Cutlass Red': '德雷克 红弯刀',
  'Argo SRV': '南船座 SRV',
  'Aegis Vulcan': '圣盾 火神',
  'Drake Vulture': '德雷克 秃鹫',
  'Drake Clipper': '德雷克 快帆',
  'Origin 300i': '起源 300i',
  'Aegis Avenger Titan': '圣盾 复仇者 泰坦',
  'Aegis Avenger Titan Renegade': '圣盾 复仇者 泰坦变节者',
  'Crusader Intrepid': '十字军 无畏',
  'Origin 135c': '起源 135c',
  'RSI Aurora Mk I CL': 'RSI 极光 CL Mk I',
  'MISC Reliant Kore': '武藏 信赖 基础',
  'Gatac Syulen': '盖塔克 速伦',
  'RSI Salvation': 'RSI 拯救',
  'RSI Aurora Mk I SE': 'RSI 极光 Mk I SE',
  'Origin 325a': '起源 325a',
  'Origin 350r': '起源 350r',
  'Anvil C8 Pisces': '铁砧 C8 双鱼座',
  'Anvil C8X Pisces Expedition': '铁砧 C8X 双鱼座 远征',
  'Drake Cutter': '德雷克 小刀',
  'C.O. Mustang Alpha': '联合外域 野马-阿尔法',
  'C.O. Mustang Alpha Vindicator': '联合外域 野马-阿尔法 辩护版',
  'Anvil Paladin': '铁砧 圣骑士',
  'RSI Aurora Mk I ES': 'RSI 极光 ES Mk I',
  'RSI Aurora Mk I LN': 'RSI 极光 LN Mk I',
  'RSI Aurora Mk I LX': 'RSI 极光 LX Mk I',
  'RSI Aurora Mk I MR': 'RSI 极光 MR Mk I',
  'Origin 100i': '起源 100i',
  'Origin 125a': '起源 125a',
  'Drake Cutter Scout': '德雷克 小刀 侦察',
  'Drake Cutter Rambler': '德雷克 小刀 漫步者',
  'Anvil F7C Hornet Mk II': '铁砧 F7C 大黄蜂 Mk II',
  'Argo MPUV Cargo': '南船座 MPUV 货运',
  'Aegis Redeemer': '圣盾 救赎者',
  'Origin M80': '起源 M80',
  'MISC Reliant Tana': '武藏 信赖 武装',
};

export function getShipZh(enName: string): string {
  return SHIP_ZH[enName] || enName;
}
