// Terminal name translations
const TERMINAL_EN_TO_ZH: Record<string, string> = {
  "Admin - ARC-L1": "管理中心 - 弧光-L1",
  "Admin - ARC-L2": "管理中心 - 弧光-L2",
  "Admin - ARC-L3": "管理中心 - 弧光-L3",
  "Admin - ARC-L4": "管理中心 - 弧光-L4",
  "Admin - ARC-L5": "管理中心 - 弧光-L5",
  "Admin - Baijini Point": "管理中心 - 拜基尼空间站",
  "Admin - CRU-L1": "管理中心 - 十字军-L1",
  "Admin - CRU-L4": "管理中心 - 十字军-L4",
  "Admin - CRU-L5": "管理中心 - 十字军-L5",
  "Admin - Checkmate": "管理中心 - 死局空间站",
  "Admin - Dudley & Daughters": "管理中心 - 达德利父女空间站",
  "Admin - Endgame": "管理中心 - 终局空间站",
  "Admin - Everus Harbor": "管理中心 - 埃弗勒斯空间站",
  "Admin - Gaslight": "管理中心 - 煤气灯空间站",
  "Admin - GrimHEX": "管理中心 - 六角湾",
  "Admin - HUR-L1": "管理中心 - 赫斯顿-L1",
  "Admin - HUR-L2": "管理中心 - 赫斯顿-L2",
  "Admin - HUR-L3": "管理中心 - 赫斯顿-L3",
  "Admin - HUR-L4": "管理中心 - 赫斯顿-L4",
  "Admin - HUR-L5": "管理中心 - 赫斯顿-L5",
  "Admin - L19 Residences - Metro Center - Lorville": "管理员 - L19 居住区 - 地铁中心 - 罗威尔",
  "Admin - MIC-L1": "管理中心 - 微科-L1",
  "Admin - MIC-L2": "管理中心 - 微科-L2",
  "Admin - MIC-L3": "管理中心 - 微科-L3",
  "Admin - MIC-L4": "管理中心 - 微科-L4",
  "Admin - MIC-L5": "管理中心 - 微科-L5",
  "Admin - Megumi Refueling": "管理中心 - 恩惠加油站",
  "Admin - Nyx Gateway (斯坦顿)": "管理中心 - 尼克斯之门 (斯坦顿)",
  "Admin - Nyx Gateway (派罗)": "管理中心 - 尼克斯之门 (派罗)",
  "Admin - Orbituary": "管理中心 - 轨道讣闻站",
  "Admin - Patch City": "管理中心 - 补丁城",
  "Admin - People's Service Station Alpha": "管理中心 - 人民服务空间站 阿尔法",
  "Admin - People's Service Station Delta": "管理中心 - 人民服务空间站 德尔塔",
  "Admin - People's Service Station Lambda": "管理中心 - 人民服务空间站 拉姆达",
  "Admin - People's Service Station Theta": "管理中心 - 人民服务空间站 西塔",
  "Admin - Port Olisar": "管理中心 - 奥丽莎空间站",
  "Admin - Port Tressler": "管理中心 - 特雷斯勒空间站",
  "Admin - Pyro Gateway (尼克斯)": "管理中心 - 派罗之门 (尼克斯)",
  "Admin - Pyro Gateway (斯坦顿)": "管理中心 - 派罗之门 (斯坦顿)",
  "Admin - Rat's Nest": "管理中心 - 鼠巢空间站",
  "Admin - Rod's Fuel 'N Supplies": "管理中心 - 路德补给站",
  "Admin - Ruin Station": "管理中心 - 废墟空间站",
  "Admin - Seraphim": "管理中心 - 塞拉芬",
  "Admin - Stanton Gateway (尼克斯)": "管理中心 - 斯坦顿之门 (尼克斯)",
  "Admin - Stanton Gateway (派罗)": "管理中心 - 斯坦顿之门 (派罗)",
  "Admin - Starlight Service": "管理中心 - 星光服务站",
  "Admin - Terra Gateway (斯坦顿)": "管理中心 - 泰拉之门 (斯坦顿)",
  "Admin - UEX Station": "管理中心 - UEX空间站",
  "ArcCorp Mining Area 045": "弧光集团采矿站 045",
  "ArcCorp Mining Area 048": "弧光集团采矿站 048",
  "ArcCorp Mining Area 056": "弧光集团采矿站 056",
  "ArcCorp Mining Area 061": "弧光集团采矿站 061",
  "ArcCorp Mining Area 141": "弧光集团采矿站 141",
  "ArcCorp Mining Area 157": "弧光集团采矿站 157",
  "Ashland": "灰烬之地",
  "Benson Mining Outpost": "本森采矿前哨站",
  "Bountiful Harvest Hydroponics": "丰收水培种植站",
  "Brio's Breaker Yard": "布里奥的拆船场",
  "Bud's Growery": "巴德种植园",
  "Bueno Ravine": "布埃诺峡谷",
  "CBD - Central Business District - Lorville": "中央商务区 - 罗威尔",
  "Canard View": "鸭翼观景处",
  "Chawla's Beach": "乔拉海滩",
  "Deakins Research Outpost": "迪金斯科研前哨站",
  "Devlin Scrap and Salvage": "德夫林废品回收站",
  "Dinger's Depot": "丁格仓库",
  "Dumper's Depot - Area 18": "倾卸者仓库 - 18区",
  "Dumper's Depot - GrimHEX": "倾卸者仓库 - 六角湾",
  "Fallow Field": "休耕地",
  "Feo Canyon Depot": "费奥山谷仓库",
  "Gallete Family Farms": "加莱特家庭种植站",
  "Gray Gardens Depot": "灰园仓库",
  "HDMS-Anderson": "HDMS-安德森站",
  "HDMS-Bezdek": "HDMS-贝兹德克站",
  "HDMS-Edmond": "HDMS-埃得蒙德站",
  "HDMS-Hadley": "HDMS-哈德利站",
  "HDMS-Hahn": "HDMS-哈恩站",
  "HDMS-Lathan": "HDMS-莱森站",
  "HDMS-Norgaard": "HDMS-诺加德站",
  "HDMS-Oparei": "HDMS-奥派雷站",
  "HDMS-Perlman": "HDMS-佩尔曼站",
  "HDMS-Pinewood": "HDMS-派恩伍德站",
  "HDMS-Ryder": "HDMS-莱德站",
  "HDMS-Stanhope": "HDMS-斯坦霍普站",
  "HDMS-Thedus": "HDMS-赛达斯站",
  "HDMS-Woodruff": "HDMS-伍德拉夫站",
  "Hickes Research Outpost": "希克斯研究站",
  "Humboldt Mines": "洪保德矿站",
  "INS Jericho - Pyro Gateway": "INS-杰里科 - 派罗星门",
  "IO North Tower - Area 18": "IO North Tower - 18区",
  "Jackson's Swap": "杰克森交易站",
  "Jumptown": "跃动小镇",
  "Kudre Ore": "库德雷矿井",
  "Last Landings": "终陆镇",
  "Levski": "列夫斯基",
  "Locker Room - CRU-L4": "更衣室 - 十字军-L4",
  "Loveridge Mineral Reserve": "洛维里奇矿站",
  "Maintenance Room - CRU-L5": "维修 Room - 十字军-L5",
  "MicroTech Planetary Services - Commons - New Babbage": "微科星 Planetary Services - 普通s - 新巴贝奇",
  "NT-999-XX": "NT-999-XX",
  "NT-999-XXII": "NT-999-XXII",
  "Nuen Waste Management": "努恩废物管理中心",
  "Orison Municipal Services - Providence Platform - Orison": "奥里森 Municipal Services - 天意平台 - 奥里森",
  "Outpost 54": "前哨站 54",
  "Paradise Cove": "天堂湾",
  "Platinum Bay - ARC-L1": "白金湾 - 弧光-L1",
  "Platinum Bay - Baijini Point": "白金湾 - 拜基尼空间站",
  "Platinum Bay - CRU-L1": "白金湾 - 十字军-L1",
  "Platinum Bay - CRU-L4": "白金湾 - 十字军-L4",
  "Platinum Bay - CRU-L5": "白金湾 - 十字军-L5",
  "Platinum Bay - Everus Harbor": "白金湾 - 埃弗勒斯空间站",
  "Platinum Bay - HUR-L2": "白金湾 - 赫斯顿-L2",
  "Platinum Bay - HUR-L3": "白金湾 - 赫斯顿-L3",
  "Platinum Bay - HUR-L5": "白金湾 - 赫斯顿-L5",
  "Platinum Bay - Nyx Gateway (斯坦顿)": "白金湾 - 尼克斯之门 (斯坦顿)",
  "Platinum Bay - Nyx Gateway (派罗)": "白金湾 - 尼克斯之门 (派罗)",
  "Platinum Bay - Port Tressler": "白金湾 - 特雷斯勒空间站",
  "Platinum Bay - Pyro Gateway (尼克斯)": "白金湾 - 派罗之门 (尼克斯)",
  "Platinum Bay - Pyro Gateway (斯坦顿)": "白金湾 - 派罗之门 (斯坦顿)",
  "Platinum Bay - Stanton Gateway (尼克斯)": "白金湾 - 斯坦顿之门 (尼克斯)",
  "Platinum Bay - Stanton Gateway (派罗)": "白金湾 - 斯坦顿之门 (派罗)",
  "Platinum Bay - Terra Gateway (斯坦顿)": "白金湾 - 泰拉之门 (斯坦顿)",
  "Private Property": "Private Property",
  "Prospect Depot": "展望仓库",
  "Raven's Roost": "渡鸦栖",
  "Rayari Anvik Research Outpost": "拉亚利-安维克研究站",
  "Rayari Cantwell Research Outpost": "拉亚利-坎特韦尔研究站",
  "Rayari Deltana Research Outpost": "拉亚利 德尔塔纳科究前哨站",
  "Rayari Kaltag Research Outpost": "拉亚利-卡尔塔格研究站",
  "Rayari McGrath Research Outpost": "拉亚利-麦格拉思研究站",
  "Reclamation and Disposal Orinth": "奥林森回收站",
  "Rust - Dunboro": "Ru秒t - 顿波罗镇",
  "Rust - Pickers Field": "Rust - Pickers Field",
  "Rustville": "锈迹镇",
  "Sacren's Plot": "萨克伦领地",
  "Samson & Son's Salvage Center": "参孙父子回收站",
  "Scarper's Turn": "财奴湾",
  "Scrap - Rappel": "废料 - 索降镇",
  "Seer's Canyon": "先觉者峡谷",
  "Shady Glen": "Shady Glen",
  "Shepherd's Rest": "牧人驿站",
  "Shubin Mining Facility SAL-2": "舒宾采矿设施 SAL-2",
  "Shubin Mining Facility SAL-5": "舒宾采矿设施 SAL-5",
  "Shubin Mining Facility SCD-1": "舒宾采矿设施 SCD-1",
  "Shubin Mining Facility SM0-10": "舒宾采矿设施 SM0-10",
  "Shubin Mining Facility SM0-13": "舒宾采矿设施 SM0-13",
  "Shubin Mining Facility SM0-18": "舒宾采矿设施 SM0-18",
  "Shubin Mining Facility SM0-22": "舒宾采矿设施 SM0-22",
  "Shubin Mining Facility SMCa-6": "舒宾采矿设施 SMCa-6",
  "Shubin Mining Facility SMCa-8": "舒宾采矿设施 SMCa-8",
  "Slowburn Depot": "惩忿仓库",
  "Sunset Mesa": "日落方山",
  "TDD - Trade and Development Division - Area 18": "TDD - 贸易&发展司 - 18区",
  "TDD - Trade and Development Division - Cloudview Center - Orison": "TDD - 贸易&发展司 - 云景中心 - 奥里森",
  "TDD - Trade and Development Division - Commons - New Babbage": "TDD - 贸易&发展司 - 普通s - 新巴贝奇",
  "Terra Mills Hydrofarm": "泰拉磨坊 Hydrofarm",
  "The Golden Riviera": "金碧湾",
  "The Necropolis": "\\\"墓地\\\"",
  "The Orphanage": "孤儿院",
  "Tram & Myers Mining": "泰姆&迈尔斯矿站",
  "Watcher's Depot": "守望者仓库",
};

export function getTerminalZh(enName: string): string { return TERMINAL_EN_TO_ZH[enName] || enName; }
