// Terminal name translations
const TERMINAL_EN_TO_ZH: Record<string, string> = {
  "Admin - ARC-L1": "管理中心 - 弧光-L1",
  "Admin - ARC-L2": "管理中心 - 弧光-L2",
  "Admin - ARC-L3": "管理中心 - 弧光-L3",
  "Admin - ARC-L4": "管理中心 - 弧光-L4",
  "Admin - ARC-L5": "管理中心 - 弧光-L5",
  "Admin - Baijini Point": "管理中心 - 拜基尼空间站",
  "Admin - CRU-L1": "管理中心 - 十字军-L1",
  "Admin - CRU-L4": "管理中心 - 十字军-L4",
  "Admin - CRU-L5": "管理中心 - 十字军-L5",
  "Admin - Checkmate": "管理中心 - 死局空间站",
  "Admin - Dudley & Daughters": "管理中心 - 达德利父女空间站",
  "Admin - Endgame": "管理中心 - 终局空间站",
  "Admin - Everus Harbor": "管理中心 - 埃弗勒斯空间站",
  "Admin - Gaslight": "管理中心 - 煤气灯空间站",
  "Admin - GrimHEX": "管理中心 - 六角湾",
  "Admin - HUR-L1": "管理中心 - 赫斯顿-L1",
  "Admin - HUR-L2": "管理中心 - 赫斯顿-L2",
  "Admin - HUR-L3": "管理中心 - 赫斯顿-L3",
  "Admin - HUR-L4": "管理中心 - 赫斯顿-L4",
  "Admin - HUR-L5": "管理中心 - 赫斯顿-L5",
  "Admin - L19 Residences - Metro Center - Lorville": "管理中心 - L19 居住区 - 地铁中心 - 罗威尔",
  "Admin - MIC-L1": "管理中心 - 微科-L1",
  "Admin - MIC-L2": "管理中心 - 微科-L2",
  "Admin - MIC-L3": "管理中心 - 微科-L3",
  "Admin - MIC-L4": "管理中心 - 微科-L4",
  "Admin - MIC-L5": "管理中心 - 微科-L5",
  "Admin - Megumi Refueling": "管理中心 - 恩惠加油站",
  "Admin - Nyx Gateway (Pyro)": "管理中心 - 尼克斯星门 (派罗)",
  "Admin - Nyx Gateway (Stanton)": "管理中心 - 尼克斯星门 (斯坦顿)",
  "Admin - Orbituary": "管理中心 - 轨道讣闻站",
  "Admin - Patch City": "管理中心 - 补丁城",
  "Admin - People's Service Station Alpha": "管理中心 - 人民服务空间站 阿尔法",
  "Admin - People's Service Station Delta": "管理中心 - 人民服务空间站 德尔塔",
  "Admin - People's Service Station Lambda": "管理中心 - 人民服务空间站 拉姆达",
  "Admin - People's Service Station Theta": "管理中心 - 人民服务空间站 西塔",
  "Admin - Port Olisar": "管理中心 - 奥丽莎空间站",
  "Admin - Port Tressler": "管理中心 - 特雷斯勒空间站",
  "Admin - Pyro Gateway (Nyx)": "管理中心 - 派罗星门 (尼克斯)",
  "Admin - Pyro Gateway (Stanton)": "管理中心 - 派罗星门 (斯坦顿)",
  "Admin - Rat's Nest": "管理中心 - 鼠巢空间站",
  "Admin - Rod's Fuel 'N Supplies": "管理中心 - 路德补给站",
  "Admin - Ruin Station": "管理中心 - 废墟空间站",
  "Admin - Seraphim": "管理中心 - 塞拉芬",
  "Admin - Stanton Gateway (Nyx)": "管理中心 - 斯坦顿星门 (尼克斯)",
  "Admin - Stanton Gateway (Pyro)": "管理中心 - 斯坦顿星门 (派罗)",
  "Admin - Starlight Service": "管理中心 - 星光服务",
  "Admin - Terra Gateway (Stanton)": "管理中心 - 特拉星门 (斯坦顿)",
  "CBD - Central Business District - Lorville": "CBD - 中央商务区 - 罗威尔",
  "Dumper's Depot - Area 18": "倾卸者仓库 - 18区",
  "Dumper's Depot - GrimHEX": "倾卸者仓库 - 六角湾",
  "INS Jericho - Pyro Gateway": "INS-杰里科 - 派罗星门",
  "IO North Tower - Area 18": "IO North Tower - 18区",
  "Levski": "列夫斯基",
  "Locker Room - CRU-L4": "更衣室 - 十字军-L4",
  "Maintenance Room - CRU-L5": "维修 Room - 十字军-L5",
  "MicroTech Planetary Services - Commons - New Babbage": "微科星 Planetary Services - 普通s - 新巴贝奇",
  "Orison Municipal Services - Providence Platform - Orison": "奥里森 Municipal Services - 天意平台 - 奥里森",
  "Platinum Bay - ARC-L1": "白金湾 - 弧光-L1",
  "Platinum Bay - Baijini Point": "白金湾 - 拜基尼空间站",
  "Platinum Bay - CRU-L1": "白金湾 - 十字军-L1",
  "Platinum Bay - CRU-L4": "白金湾 - 十字军-L4",
  "Platinum Bay - CRU-L5": "白金湾 - 十字军-L5",
  "Platinum Bay - Everus Harbor": "白金湾 - 埃弗勒斯空间站",
  "Platinum Bay - HUR-L2": "白金湾 - 赫斯顿-L2",
  "Platinum Bay - HUR-L3": "白金湾 - 赫斯顿-L3",
  "Platinum Bay - HUR-L5": "白金湾 - 赫斯顿-L5",
  "Platinum Bay - Nyx Gateway (Pyro)": "白金湾 - 尼克斯星门 (派罗)",
  "Platinum Bay - Nyx Gateway (Stanton)": "白金湾 - 尼克斯星门 (斯坦顿)",
  "Platinum Bay - Port Tressler": "白金湾 - 特雷斯勒空间站",
  "Platinum Bay - Pyro Gateway (Nyx)": "白金湾 - 派罗星门 (尼克斯)",
  "Platinum Bay - Pyro Gateway (Stanton)": "白金湾 - 派罗星门 (斯坦顿)",
  "Platinum Bay - Stanton Gateway (Nyx)": "白金湾 - 斯坦顿星门 (尼克斯)",
  "Platinum Bay - Stanton Gateway (Pyro)": "白金湾 - 斯坦顿星门 (派罗)",
  "Platinum Bay - Terra Gateway (Stanton)": "白金湾 - 特拉星门 (斯坦顿)",
  "TDD - Trade and Development Division - Area 18": "TDD - 贸易&发展司 - 18区",
  "TDD - Trade and Development Division - Cloudview Center - Orison": "TDD - 贸易&发展司 - 云景中心 - 奥里森",
  "TDD - Trade and Development Division - Commons - New Babbage": "TDD - 贸易&发展司 - 普通s - 新巴贝奇",
};

import { getLocationZh } from './location-zh';

export function getTerminalZh(enName: string): string {
  return TERMINAL_EN_TO_ZH[enName] || getLocationZh(enName);
}
