export const LOCATION_EN_TO_ZH: Record<string, string> = {
  "Admin - UEX Station": "管理中心 - UEX 站点",
  "ARC-L1 Wide Forest Station": "弧光-L1 广袤森林站",
  "ARC-L2 Lively Pathway Station": "弧光-L2 活力小径站",
  "ARC-L3 Modern Express Station": "弧光-L3 现代快车站",
  "ARC-L4 Faint Glen Station": "弧光-L4 微光峡谷站",
  "ARC-L5 Yellow Core Station": "弧光-L5 黄色核心站",
  "ArcCorp Mining Area 045": "弧光集团采矿站 045",
  "ArcCorp Mining Area 048": "弧光集团采矿站 048",
  "ArcCorp Mining Area 056": "弧光集团采矿站 056",
  "ArcCorp Mining Area 061": "弧光集团采矿站 061",
  "ArcCorp Mining Area 141": "弧光集团采矿站 141",
  "ArcCorp Mining Area 157": "弧光集团采矿站 157",
  "Area 18": "18区",
  "Ashland": "灰烬之地",
  "Baijini Point": "拜基尼空间站",
  "Benson Mining Outpost": "本森采矿前哨站",
  "Bountiful Harvest Hydroponics": "丰收水培种植站",
  "Brio's Breaker Yard": "布里奥的拆船场",
  "Bud's Growery": "巴德种植园",
  "Bueno Ravine": "布埃诺峡谷",
  "Canard View": "鸭翼观景处",
  "Chawla's Beach": "乔拉海滩",
  "Checkmate Station": "死局空间站",
  "CRU-L1 Ambitious Dream Station": "十字军-L1 雄心伟梦站",
  "CRU-L4 Shallow Fields Station": "十字军-L4 浅野站",
  "CRU-L5 Beautiful Glen Station": "十字军-L5 美丽峡谷站",
  "Deakins Research Outpost": "迪金斯科研前哨站",
  "Devlin Scrap and Salvage": "德夫林废品回收站",
  "Dinger's Depot": "丁格仓库",
  "Dudley & Daughters": "达德利父女空间站",
  "Endgame": "终局空间站",
  "Everus Harbor": "埃弗勒斯空间站",
  "Fallow Field": "休耕地",
  "Feo Canyon Depot": "费奥山谷仓库",
  "Gallete Family Farms": "加莱特家庭种植站",
  "Gaslight": "煤气灯空间站",
  "Gray Gardens Depot": "灰园仓库",
  "Green Imperial Housing Exchange": "格林皇家房屋交易所",
  "HDMS-Anderson": "HDMS-安德森站",
  "HDMS-Bezdek": "HDMS-贝兹德克站",
  "HDMS-Edmond": "HDMS-埃得蒙德站",
  "HDMS-Hadley": "HDMS-哈德利站",
  "HDMS-Hahn": "HDMS-哈恩站",
  "HDMS-Lathan": "HDMS-莱森站",
  "HDMS-Norgaard": "HDMS-诺加德站",
  "HDMS-Oparei": "HDMS-奥派雷站",
  "HDMS-Perlman": "HDMS-佩尔曼站",
  "HDMS-Pinewood": "HDMS-派恩伍德站",
  "HDMS-Ryder": "HDMS-莱德站",
  "HDMS-Stanhope": "HDMS-斯坦霍普站",
  "HDMS-Thedus": "HDMS-赛达斯站",
  "HDMS-Woodruff": "HDMS-伍德拉夫站",
  "Hickes Research Outpost": "希克斯研究站",
  "Humboldt Mines": "洪保德矿站",
  "HUR-L1 Green Glade Station": "赫斯顿-L1 绿色林地站",
  "HUR-L2 Faithful Dream Station": "赫斯顿-L2 忠实梦想站",
  "HUR-L3 Thundering Express Station": "赫斯顿-L3 雷鸣快车站",
  "HUR-L4 Melodic Fields Station": "赫斯顿-L4 悠扬田野站",
  "HUR-L5 High Course Station": "赫斯顿-L5 高轨站",
  "Jackson's Swap": "杰克森交易站",
  "Jumptown": "跃动小镇",
  "Kudre Ore": "库德雷矿井",
  "Last Landings": "终陆镇",
  "Levski": "列夫斯基",
  "Lorville": "罗威尔",
  "Loveridge Mineral Reserve": "洛维里奇矿站",
  "Megumi Refueling": "恩惠加油站",
  "MIC-L1 Shallow Frontier Station": "微科-L1 浅边境站",
  "MIC-L2 Long Forest Station": "微科-L2 长林站",
  "MIC-L3 Endless Odyssey Station": "微科-L3 无尽奥德赛站",
  "MIC-L4 Red Crossroads Station": "微科-L4 红色十字路站",
  "MIC-L5 Modern Icarus Station": "微科-L5 现代伊卡洛斯站",
  "New Babbage": "新巴贝奇",
  "NT-999-XX": "NT-999-XX",
  "NT-999-XXII": "NT-999-XXII",
  "Nuen Waste Management": "努恩废物管理中心",
  "Nyx Gateway (Pyro)": "尼克斯星门 (派罗)",
  "Nyx Gateway (Stanton)": "尼克斯星门 (斯坦顿)",
  "Orbituary": "轨道讣闻站",
  "Orison": "奥里森",
  "Outpost 54": "前哨站 54",
  "Paradise Cove": "天堂湾",
  "Patch City": "补丁城",
  "People's Service Station Alpha": "人民服务空间站 阿尔法",
  "People's Service Station Delta": "人民服务空间站 德尔塔",
  "People's Service Station Lambda": "人民服务空间站 拉姆达",
  "People's Service Station Theta": "人民服务空间站 西塔",
  "Port Olisar": "奥丽莎空间站",
  "Port Tressler": "特雷斯勒空间站",
  "Private Property": "私人领地",
  "Prospect Depot": "展望仓库",
  "Pyro Gateway (Nyx)": "派罗星门 (尼克斯)",
  "Pyro Gateway (Stanton)": "派罗星门 (斯坦顿)",
  "Rat's Nest": "鼠巢空间站",
  "Raven's Roost": "渡鸦栖",
  "Rayari Anvik Research Outpost": "拉亚利-安维克研究站",
  "Rayari Cantwell Research Outpost": "拉亚利-坎特韦尔研究站",
  "Rayari Deltana Research Outpost": "拉亚利-德尔塔纳研究前哨站",
  "Rayari Kaltag Research Outpost": "拉亚利-卡尔塔格研究站",
  "Rayari McGrath Research Outpost": "拉亚利-麦格拉思研究站",
  "Reclamation and Disposal Orinth": "奥林森回收站",
  "Rod's Fuel 'N Supplies": "路德补给站",
  "Ruin Station": "废墟空间站",
  "Rust - Dunboro": "锈迹镇 - 顿波罗镇",
  "Rust - Pickers Field": "锈迹镇 - 摘客场",
  "Rustville": "锈迹镇",
  "Sacren's Plot": "萨克伦领地",
  "Samson & Son's Salvage Center": "参孙父子回收站",
  "Scarper's Turn": "财奴湾",
  "Scrap - Rappel": "废料 - 索降镇",
  "Seer's Canyon": "先觉者峡谷",
  "Seraphim Station": "炽天使空间站",
  "Shady Glen": "幽暗谷",
  "Shepherd's Rest": "牧人驿站",
  "Shubin Mining Facility SAL-2": "舒宾采矿设施 SAL-2",
  "Shubin Mining Facility SAL-5": "舒宾采矿设施 SAL-5",
  "Shubin Mining Facility SCD-1": "舒宾采矿设施 SCD-1",
  "Shubin Mining Facility SM0-10": "舒宾采矿设施 SM0-10",
  "Shubin Mining Facility SM0-13": "舒宾采矿设施 SM0-13",
  "Shubin Mining Facility SM0-18": "舒宾采矿设施 SM0-18",
  "Shubin Mining Facility SM0-22": "舒宾采矿设施 SM0-22",
  "Shubin Mining Facility SMCa-6": "舒宾采矿设施 SMCa-6",
  "Shubin Mining Facility SMCa-8": "舒宾采矿设施 SMCa-8",
  "Slowburn Depot": "惩忿仓库",
  "Stanton Gateway (Nyx)": "斯坦顿星门 (尼克斯)",
  "Stanton Gateway (Pyro)": "斯坦顿星门 (派罗)",
  "Starlight Service Station": "星光服务站",
  "Sunset Mesa": "日落方山",
  "Terra Gateway (Stanton)": "泰拉星门 (斯坦顿)",
  "Terra Mills Hydrofarm": "泰拉磨坊水培农场",
  "The Golden Riviera": "金碧湾",
  "The Necropolis": "墓地",
  "The Orphanage": "孤儿院",
  "Tram & Myers Mining": "泰姆&迈尔斯矿站",
  "Watcher's Depot": "守望者仓库",

  // Star systems, planets, moons
  "Aberdeen": "阿伯丁",
  "ArcCorp": "弧光星",
  "Arial": "艾瑞尔",
  "Bloom": "盛放星",
  "Calliope": "卡利俄佩",
  "Cellin": "赛琳",
  "Clio": "克利俄",
  "Crusader": "十字军",
  "Daymar": "戴玛尔",
  "Euterpe": "欧忒耳佩",
  "Fairo": "法伊罗",
  "Hurston": "赫斯顿",
  "Ignis": "伊格尼斯",
  "Ita": "依塔",
  "Lyria": "莉瑞雅",
  "Magda": "玛格达",
  "MicroTech": "微科星",
  "Monox": "殁氧星",
  "Nyx": "尼克斯",
  "Pyro": "派罗",
  "Pyro I": "派罗 I",
  "Pyro IV": "派罗 IV",
  "Pyro V": "派罗 V",
  "Stanton": "斯坦顿",
  "Terminus": "端点星",
  "Vatra": "瓦塔拉",
  "Wala": "瓦菈",
  "Yela": "耶拉",

};

export function getLocationZh(enName: string | null): string {
  if (!enName) return "";
  return LOCATION_EN_TO_ZH[enName] || enName;
}
